// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer12_out_dout,
        layer12_out_empty_n,
        layer12_out_read,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap,
        layer13_out_TDATA,
        layer13_out_TVALID,
        layer13_out_TREADY
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] layer12_out_dout;
input   layer12_out_empty_n;
output   layer12_out_read;
input  [1:0] layer12_out_num_data_valid;
input  [1:0] layer12_out_fifo_cap;
output  [95:0] layer13_out_TDATA;
output   layer13_out_TVALID;
input   layer13_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer12_out_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer12_out_blk_n;
reg    layer13_out_TDATA_blk_n;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [7:0] data_fu_200_p1;
reg   [7:0] data_reg_532;
reg    ap_block_state1;
reg   [7:0] data_1_reg_537;
reg   [7:0] data_2_reg_542;
reg   [7:0] data_3_reg_547;
reg   [7:0] data_4_reg_552;
reg   [7:0] data_5_reg_557;
reg   [7:0] data_6_reg_562;
reg   [7:0] data_7_reg_567;
reg   [7:0] data_8_reg_572;
reg   [7:0] data_9_reg_577;
reg   [7:0] data_30_reg_582;
reg   [7:0] data_10_reg_587;
reg   [7:0] data_11_reg_592;
reg   [7:0] data_12_reg_597;
reg   [7:0] data_13_reg_602;
reg   [7:0] data_14_reg_607;
reg   [7:0] data_15_reg_612;
reg   [7:0] data_16_reg_617;
reg   [7:0] data_17_reg_622;
reg   [7:0] data_18_reg_627;
reg   [7:0] data_19_reg_632;
reg   [7:0] data_20_reg_637;
reg   [7:0] data_21_reg_642;
reg   [7:0] data_22_reg_647;
reg   [7:0] data_23_reg_652;
reg   [7:0] data_24_reg_657;
reg   [7:0] data_25_reg_662;
reg   [7:0] data_26_reg_667;
reg   [7:0] data_27_reg_672;
reg   [7:0] data_28_reg_677;
reg   [7:0] data_29_reg_682;
reg   [21:0] res_reg_687;
wire    ap_CS_fsm_state5;
reg   [21:0] res_1_reg_692;
reg   [21:0] res_2_reg_697;
wire    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_start;
wire    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_done;
wire    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_idle;
wire    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_ready;
wire   [21:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_return_0;
wire   [21:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_return_1;
wire   [21:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_return_2;
reg    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_start_reg;
reg   [6:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state2;
wire   [85:0] tmp_fu_516_p6;
wire    regslice_both_layer13_out_U_apdone_blk;
reg    ap_block_state7;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire   [95:0] layer13_out_TDATA_int_regslice;
reg    layer13_out_TVALID_int_regslice;
wire    layer13_out_TREADY_int_regslice;
wire    regslice_both_layer13_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_start_reg = 1'b0;
end

myproject_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_start),
    .ap_done(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_done),
    .ap_idle(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_idle),
    .ap_ready(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_ready),
    .data_0_val(data_reg_532),
    .data_1_val(data_1_reg_537),
    .data_2_val(data_2_reg_542),
    .data_3_val(data_3_reg_547),
    .data_4_val(data_4_reg_552),
    .data_5_val(data_5_reg_557),
    .data_6_val(data_6_reg_562),
    .data_7_val(data_7_reg_567),
    .data_8_val(data_8_reg_572),
    .data_9_val(data_9_reg_577),
    .data_10_val(data_30_reg_582),
    .data_11_val(data_10_reg_587),
    .data_12_val(data_11_reg_592),
    .data_13_val(data_12_reg_597),
    .data_14_val(data_13_reg_602),
    .data_15_val(data_14_reg_607),
    .data_16_val(data_15_reg_612),
    .data_17_val(data_16_reg_617),
    .data_18_val(data_17_reg_622),
    .data_19_val(data_18_reg_627),
    .data_20_val(data_19_reg_632),
    .data_21_val(data_20_reg_637),
    .data_22_val(data_21_reg_642),
    .data_23_val(data_22_reg_647),
    .data_24_val(data_23_reg_652),
    .data_26_val(data_24_reg_657),
    .data_27_val(data_25_reg_662),
    .data_28_val(data_26_reg_667),
    .data_29_val(data_27_reg_672),
    .data_30_val(data_28_reg_677),
    .data_31_val(data_29_reg_682),
    .ap_return_0(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_return_2)
);

myproject_regslice_both #(
    .DataWidth( 96 ))
regslice_both_layer13_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(layer13_out_TDATA_int_regslice),
    .vld_in(layer13_out_TVALID_int_regslice),
    .ack_in(layer13_out_TREADY_int_regslice),
    .data_out(layer13_out_TDATA),
    .vld_out(regslice_both_layer13_out_U_vld_out),
    .ack_out(layer13_out_TREADY),
    .apdone_blk(regslice_both_layer13_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_ready == 1'b1)) begin
            grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_10_reg_587 <= {{layer12_out_dout[95:88]}};
        data_11_reg_592 <= {{layer12_out_dout[103:96]}};
        data_12_reg_597 <= {{layer12_out_dout[111:104]}};
        data_13_reg_602 <= {{layer12_out_dout[119:112]}};
        data_14_reg_607 <= {{layer12_out_dout[127:120]}};
        data_15_reg_612 <= {{layer12_out_dout[135:128]}};
        data_16_reg_617 <= {{layer12_out_dout[143:136]}};
        data_17_reg_622 <= {{layer12_out_dout[151:144]}};
        data_18_reg_627 <= {{layer12_out_dout[159:152]}};
        data_19_reg_632 <= {{layer12_out_dout[167:160]}};
        data_1_reg_537 <= {{layer12_out_dout[15:8]}};
        data_20_reg_637 <= {{layer12_out_dout[175:168]}};
        data_21_reg_642 <= {{layer12_out_dout[183:176]}};
        data_22_reg_647 <= {{layer12_out_dout[191:184]}};
        data_23_reg_652 <= {{layer12_out_dout[199:192]}};
        data_24_reg_657 <= {{layer12_out_dout[215:208]}};
        data_25_reg_662 <= {{layer12_out_dout[223:216]}};
        data_26_reg_667 <= {{layer12_out_dout[231:224]}};
        data_27_reg_672 <= {{layer12_out_dout[239:232]}};
        data_28_reg_677 <= {{layer12_out_dout[247:240]}};
        data_29_reg_682 <= {{layer12_out_dout[255:248]}};
        data_2_reg_542 <= {{layer12_out_dout[23:16]}};
        data_30_reg_582 <= {{layer12_out_dout[87:80]}};
        data_3_reg_547 <= {{layer12_out_dout[31:24]}};
        data_4_reg_552 <= {{layer12_out_dout[39:32]}};
        data_5_reg_557 <= {{layer12_out_dout[47:40]}};
        data_6_reg_562 <= {{layer12_out_dout[55:48]}};
        data_7_reg_567 <= {{layer12_out_dout[63:56]}};
        data_8_reg_572 <= {{layer12_out_dout[71:64]}};
        data_9_reg_577 <= {{layer12_out_dout[79:72]}};
        data_reg_532 <= data_fu_200_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_1_reg_692 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_return_1;
        res_2_reg_697 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_return_2;
        res_reg_687 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_return_0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((layer13_out_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state7)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer12_out_blk_n = layer12_out_empty_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer12_out_read = 1'b1;
    end else begin
        layer12_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        layer13_out_TDATA_blk_n = layer13_out_TREADY_int_regslice;
    end else begin
        layer13_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer13_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        layer13_out_TVALID_int_regslice = 1'b1;
    end else begin
        layer13_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((layer13_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((layer12_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((layer13_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer13_out_U_apdone_blk == 1'b1));
end

assign data_fu_200_p1 = layer12_out_dout[7:0];

assign grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_start = grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s_fu_165_ap_start_reg;

assign layer13_out_TDATA_int_regslice = tmp_fu_516_p6;

assign layer13_out_TVALID = regslice_both_layer13_out_U_vld_out;

assign tmp_fu_516_p6 = {{{{{res_2_reg_697}, {10'd0}}, {res_1_reg_692}}, {10'd0}}, {res_reg_687}};

endmodule //myproject_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_s
