// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] data_0_val;
input  [7:0] data_1_val;
input  [7:0] data_2_val;
input  [7:0] data_3_val;
input  [7:0] data_4_val;
input  [7:0] data_5_val;
input  [7:0] data_6_val;
input  [7:0] data_7_val;
input  [7:0] data_8_val;
input  [7:0] data_9_val;
input  [7:0] data_10_val;
input  [7:0] data_11_val;
input  [7:0] data_12_val;
input  [7:0] data_13_val;
input  [7:0] data_14_val;
input  [7:0] data_15_val;
input  [7:0] data_16_val;
input  [7:0] data_17_val;
input  [7:0] data_18_val;
input  [7:0] data_19_val;
input  [7:0] data_20_val;
input  [7:0] data_21_val;
input  [7:0] data_22_val;
input  [7:0] data_23_val;
input  [7:0] data_24_val;
input  [7:0] data_26_val;
input  [7:0] data_27_val;
input  [7:0] data_28_val;
input  [7:0] data_29_val;
input  [7:0] data_30_val;
input  [7:0] data_31_val;
output  [21:0] ap_return_0;
output  [21:0] ap_return_1;
output  [21:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg  signed [7:0] data_5_val_read_reg_2238;
reg  signed [7:0] data_4_val_read_reg_2243;
reg  signed [7:0] data_1_val_read_reg_2248;
wire   [12:0] sub_ln73_1809_fu_398_p2;
reg   [12:0] sub_ln73_1809_reg_2253;
wire  signed [11:0] sext_ln73_1104_fu_412_p1;
reg  signed [11:0] sext_ln73_1104_reg_2258;
wire  signed [10:0] tmp_912_fu_456_p3;
reg  signed [10:0] tmp_912_reg_2263;
wire  signed [11:0] sext_ln73_1112_fu_536_p1;
reg  signed [11:0] sext_ln73_1112_reg_2268;
wire   [12:0] add_ln73_1_fu_612_p2;
reg   [12:0] add_ln73_1_reg_2273;
wire   [8:0] sub_ln73_480_fu_622_p2;
reg   [8:0] sub_ln73_480_reg_2278;
wire   [11:0] add_ln58_fu_628_p2;
reg   [11:0] add_ln58_reg_2283;
wire   [10:0] add_ln58_7666_fu_654_p2;
reg   [10:0] add_ln58_7666_reg_2288;
wire   [11:0] add_ln58_7669_fu_666_p2;
reg   [11:0] add_ln58_7669_reg_2293;
wire   [10:0] add_ln58_7671_fu_694_p2;
reg   [10:0] add_ln58_7671_reg_2298;
wire   [10:0] add_ln58_7673_fu_700_p2;
reg   [10:0] add_ln58_7673_reg_2303;
wire   [11:0] add_ln58_7677_fu_706_p2;
reg   [11:0] add_ln58_7677_reg_2308;
wire   [11:0] add_ln58_7696_fu_712_p2;
reg   [11:0] add_ln58_7696_reg_2313;
reg  signed [7:0] data_20_val_read_reg_2318;
wire    ap_CS_fsm_state2;
wire   [11:0] sub_ln73_1817_fu_785_p2;
reg   [11:0] sub_ln73_1817_reg_2324;
wire   [12:0] sub_ln73_1836_fu_1182_p2;
reg   [12:0] sub_ln73_1836_reg_2329;
wire   [12:0] add_ln58_7674_fu_1440_p2;
reg   [12:0] add_ln58_7674_reg_2334;
wire   [13:0] add_ln58_7678_fu_1475_p2;
reg   [13:0] add_ln58_7678_reg_2339;
wire   [12:0] sub_ln58_3096_fu_1515_p2;
reg   [12:0] sub_ln58_3096_reg_2344;
wire   [12:0] add_ln58_7682_fu_1541_p2;
reg   [12:0] add_ln58_7682_reg_2349;
wire   [12:0] add_ln58_7687_fu_1611_p2;
reg   [12:0] add_ln58_7687_reg_2354;
wire   [11:0] add_ln58_7690_fu_1617_p2;
reg   [11:0] add_ln58_7690_reg_2359;
wire   [11:0] add_ln58_7693_fu_1639_p2;
reg   [11:0] add_ln58_7693_reg_2364;
wire   [11:0] add_ln58_7702_fu_1693_p2;
reg   [11:0] add_ln58_7702_reg_2369;
wire  signed [8:0] add_ln58_7705_fu_1699_p2;
reg  signed [8:0] add_ln58_7705_reg_2374;
wire   [11:0] add_ln58_7709_fu_1729_p2;
reg   [11:0] add_ln58_7709_reg_2380;
wire   [11:0] add_ln58_7714_fu_1802_p2;
reg   [11:0] add_ln58_7714_reg_2385;
wire   [13:0] add_ln58_7716_fu_1808_p2;
reg   [13:0] add_ln58_7716_reg_2390;
wire   [11:0] sub_ln58_3103_fu_1814_p2;
reg   [11:0] sub_ln58_3103_reg_2395;
wire   [11:0] add_ln58_7720_fu_1849_p2;
reg   [11:0] add_ln58_7720_reg_2400;
wire  signed [8:0] add_ln58_7722_fu_1855_p2;
reg  signed [8:0] add_ln58_7722_reg_2405;
wire   [12:0] add_ln58_7724_fu_1881_p2;
reg   [12:0] add_ln58_7724_reg_2411;
wire   [11:0] add_ln58_7726_fu_1915_p2;
reg   [11:0] add_ln58_7726_reg_2416;
wire   [10:0] add_ln58_7728_fu_1941_p2;
reg   [10:0] add_ln58_7728_reg_2421;
wire   [12:0] sub_ln73_1832_fu_1970_p2;
reg   [12:0] sub_ln73_1832_reg_2426;
wire    ap_CS_fsm_state3;
wire   [15:0] add_ln58_7689_fu_2016_p2;
reg   [15:0] add_ln58_7689_reg_2431;
wire   [13:0] add_ln58_7703_fu_2040_p2;
reg   [13:0] add_ln58_7703_reg_2436;
wire   [11:0] add_ln58_7706_fu_2060_p2;
reg   [11:0] add_ln58_7706_reg_2441;
wire   [14:0] add_ln58_7723_fu_2117_p2;
reg   [14:0] add_ln58_7723_reg_2446;
wire   [12:0] add_ln58_7729_fu_2129_p2;
reg   [12:0] add_ln58_7729_reg_2451;
reg   [7:0] ap_port_reg_data_6_val;
reg   [7:0] ap_port_reg_data_9_val;
reg   [7:0] ap_port_reg_data_10_val;
reg   [7:0] ap_port_reg_data_11_val;
reg   [7:0] ap_port_reg_data_12_val;
reg   [7:0] ap_port_reg_data_13_val;
reg   [7:0] ap_port_reg_data_14_val;
reg   [7:0] ap_port_reg_data_15_val;
reg   [7:0] ap_port_reg_data_16_val;
reg   [7:0] ap_port_reg_data_17_val;
reg   [7:0] ap_port_reg_data_18_val;
reg   [7:0] ap_port_reg_data_20_val;
reg   [7:0] ap_port_reg_data_21_val;
reg   [7:0] ap_port_reg_data_22_val;
reg   [7:0] ap_port_reg_data_23_val;
reg   [7:0] ap_port_reg_data_24_val;
reg   [7:0] ap_port_reg_data_26_val;
reg   [7:0] ap_port_reg_data_27_val;
reg   [7:0] ap_port_reg_data_28_val;
reg   [7:0] ap_port_reg_data_29_val;
reg   [7:0] ap_port_reg_data_30_val;
reg   [7:0] ap_port_reg_data_31_val;
wire  signed [7:0] sext_ln73_fu_306_p0;
wire  signed [7:0] sext_ln73_1_fu_310_p0;
wire  signed [7:0] tmp_fu_314_p1;
wire   [10:0] tmp_fu_314_p3;
wire  signed [11:0] sext_ln73_1099_fu_322_p1;
wire  signed [7:0] tmp_906_fu_332_p1;
wire   [8:0] tmp_906_fu_332_p3;
wire   [11:0] sub_ln73_1806_fu_326_p2;
wire  signed [11:0] sext_ln73_1100_fu_340_p1;
wire  signed [7:0] tmp_907_fu_350_p1;
wire  signed [9:0] tmp_907_fu_350_p3;
wire  signed [10:0] sext_ln73_1101_fu_358_p1;
wire  signed [10:0] sext_ln73_1_fu_310_p1;
wire  signed [9:0] sext_ln73_fu_306_p1;
wire  signed [7:0] tmp_908_fu_374_p1;
wire   [11:0] tmp_908_fu_374_p3;
wire  signed [7:0] tmp_909_fu_386_p1;
wire   [9:0] tmp_909_fu_386_p3;
wire  signed [12:0] sext_ln73_1103_fu_394_p1;
wire  signed [12:0] sext_ln73_1102_fu_382_p1;
wire  signed [7:0] tmp_910_fu_404_p1;
wire   [10:0] tmp_910_fu_404_p3;
wire  signed [7:0] tmp_911_fu_416_p1;
wire   [8:0] tmp_911_fu_416_p3;
wire  signed [11:0] sext_ln73_1105_fu_424_p1;
wire  signed [7:0] sext_ln70_1572_fu_434_p0;
wire  signed [8:0] sext_ln70_1572_fu_434_p1;
wire   [9:0] shl_ln_fu_444_p3;
wire   [8:0] tmp_913_fu_468_p3;
wire  signed [11:0] sext_ln73_1106_fu_464_p1;
wire  signed [11:0] sext_ln73_1107_fu_476_p1;
wire  signed [7:0] sext_ln70_1573_fu_486_p0;
wire  signed [8:0] sext_ln70_1573_fu_486_p1;
wire  signed [7:0] sext_ln70_1574_fu_496_p0;
wire  signed [7:0] tmp_915_fu_500_p1;
wire   [9:0] tmp_915_fu_500_p3;
wire  signed [10:0] sext_ln73_1108_fu_508_p1;
wire   [10:0] sub_ln73_1813_fu_512_p2;
wire  signed [10:0] sext_ln70_1574_fu_496_p1;
wire  signed [7:0] sext_ln70_1576_fu_524_p0;
wire  signed [7:0] tmp_918_fu_528_p1;
wire   [10:0] tmp_918_fu_528_p3;
wire  signed [7:0] tmp_919_fu_540_p1;
wire   [8:0] tmp_919_fu_540_p3;
wire  signed [11:0] sext_ln73_1113_fu_548_p1;
wire  signed [11:0] sext_ln70_1576_fu_524_p1;
wire  signed [7:0] sext_ln70_1577_fu_564_p0;
wire  signed [7:0] sext_ln70_1578_fu_568_p0;
wire  signed [7:0] tmp_920_fu_572_p1;
wire  signed [10:0] tmp_920_fu_572_p3;
wire  signed [11:0] sext_ln70_1578_fu_568_p1;
wire  signed [11:0] sext_ln73_1114_fu_580_p1;
wire  signed [7:0] tmp_921_fu_590_p1;
wire   [8:0] tmp_921_fu_590_p3;
wire  signed [11:0] sext_ln73_1115_fu_598_p1;
wire  signed [12:0] sext_ln73_1116_fu_608_p1;
wire  signed [12:0] sext_ln70_1577_fu_564_p1;
wire  signed [8:0] sext_ln70_1594_fu_618_p1;
wire   [11:0] sub_ln73_1807_fu_344_p2;
wire   [10:0] add_ln73_fu_362_p2;
wire   [9:0] sub_ln73_1808_fu_368_p2;
wire   [9:0] add_ln58_7665_fu_640_p2;
wire   [8:0] sub_ln73_fu_438_p2;
wire   [10:0] add_ln58_7664_fu_634_p2;
wire  signed [10:0] sext_ln58_fu_650_p1;
wire   [11:0] sub_ln73_1811_fu_428_p2;
wire  signed [11:0] sext_ln58_370_fu_646_p1;
wire   [11:0] add_ln58_7668_fu_660_p2;
wire   [11:0] sub_ln73_1812_fu_480_p2;
wire  signed [8:0] sub_ln73_479_fu_490_p2;
wire  signed [7:0] sext_ln58_8962_fu_676_p0;
wire  signed [9:0] sext_ln58_8963_fu_680_p1;
wire  signed [9:0] sext_ln58_8962_fu_676_p1;
wire   [9:0] sub_ln58_fu_684_p2;
wire  signed [10:0] sext_ln58_8964_fu_690_p1;
wire  signed [10:0] sext_ln73_3_fu_452_p1;
wire   [10:0] sub_ln73_1814_fu_518_p2;
wire  signed [10:0] sext_ln58_8961_fu_672_p1;
wire   [11:0] sub_ln73_1818_fu_552_p2;
wire   [11:0] sub_ln73_1820_fu_584_p2;
wire   [11:0] sub_ln73_1819_fu_558_p2;
wire   [11:0] sub_ln73_1821_fu_602_p2;
wire  signed [11:0] sext_ln70_fu_718_p1;
wire   [10:0] tmp_914_fu_726_p3;
wire  signed [7:0] sext_ln70_1575_fu_737_p0;
wire  signed [7:0] tmp_916_fu_741_p1;
wire  signed [10:0] tmp_916_fu_741_p3;
wire  signed [12:0] sext_ln73_1109_fu_749_p1;
wire   [12:0] sub_ln73_1815_fu_753_p2;
wire  signed [12:0] sext_ln70_1575_fu_737_p1;
wire   [12:0] sub_ln73_1816_fu_759_p2;
wire  signed [7:0] tmp_917_fu_773_p1;
wire   [8:0] tmp_917_fu_773_p3;
wire  signed [11:0] sext_ln73_1111_fu_781_p1;
wire  signed [11:0] sext_ln73_1110_fu_769_p1;
wire  signed [7:0] sext_ln70_1579_fu_794_p0;
wire  signed [7:0] sext_ln70_1580_fu_798_p0;
wire  signed [7:0] tmp_922_fu_802_p1;
wire  signed [7:0] sext_ln70_1581_fu_810_p0;
wire  signed [7:0] sext_ln70_1582_fu_814_p0;
wire  signed [7:0] tmp_923_fu_818_p1;
wire   [10:0] tmp_923_fu_818_p3;
wire  signed [7:0] tmp_924_fu_830_p1;
wire   [8:0] tmp_924_fu_830_p3;
wire  signed [11:0] sext_ln73_1117_fu_826_p1;
wire  signed [11:0] sext_ln73_1118_fu_838_p1;
wire  signed [7:0] tmp_925_fu_848_p1;
wire   [9:0] tmp_925_fu_848_p3;
wire  signed [11:0] sext_ln73_1119_fu_856_p1;
wire   [11:0] sub_ln73_1823_fu_860_p2;
wire  signed [11:0] sext_ln70_1581_fu_810_p1;
wire  signed [7:0] sext_ln70_1583_fu_872_p0;
wire  signed [7:0] shl_ln73_2_fu_876_p1;
wire   [8:0] shl_ln73_2_fu_876_p3;
wire  signed [7:0] sext_ln70_1585_fu_888_p0;
wire  signed [7:0] tmp_926_fu_892_p1;
wire   [8:0] tmp_926_fu_892_p3;
wire  signed [9:0] sext_ln73_1120_fu_900_p1;
wire   [9:0] sub_ln73_1825_fu_904_p2;
wire  signed [7:0] sext_ln70_1586_fu_914_p0;
wire  signed [7:0] tmp_927_fu_918_p1;
wire   [9:0] tmp_927_fu_918_p3;
wire  signed [10:0] sext_ln73_1121_fu_926_p1;
wire   [10:0] sub_ln73_1826_fu_930_p2;
wire  signed [10:0] sext_ln70_1586_fu_914_p1;
wire  signed [7:0] sext_ln70_1587_fu_946_p0;
wire  signed [7:0] sext_ln70_1588_fu_950_p0;
wire  signed [7:0] tmp_928_fu_954_p1;
wire  signed [9:0] tmp_928_fu_954_p3;
wire  signed [11:0] sext_ln73_1123_fu_966_p1;
wire   [11:0] sub_ln73_1828_fu_970_p2;
wire  signed [11:0] sext_ln70_1587_fu_946_p1;
wire  signed [7:0] sext_ln70_1589_fu_982_p0;
wire  signed [7:0] sext_ln70_1590_fu_986_p0;
wire  signed [7:0] tmp_929_fu_990_p1;
wire   [9:0] tmp_929_fu_990_p3;
wire  signed [10:0] sext_ln73_1124_fu_998_p1;
wire  signed [10:0] sext_ln70_1590_fu_986_p1;
wire  signed [7:0] shl_ln73_3_fu_1008_p1;
wire   [8:0] shl_ln73_3_fu_1008_p3;
wire  signed [7:0] sext_ln70_1591_fu_1020_p0;
wire  signed [7:0] shl_ln73_4_fu_1024_p1;
wire  signed [7:0] tmp_930_fu_1032_p1;
wire  signed [7:0] sext_ln70_1592_fu_1040_p0;
wire  signed [7:0] tmp_931_fu_1044_p1;
wire  signed [7:0] sext_ln70_1593_fu_1052_p0;
wire  signed [7:0] tmp_932_fu_1056_p1;
wire   [8:0] tmp_932_fu_1056_p3;
wire  signed [7:0] shl_ln73_5_fu_1068_p1;
wire  signed [7:0] sext_ln70_1596_fu_1076_p0;
wire  signed [7:0] tmp_934_fu_1080_p1;
wire   [9:0] tmp_934_fu_1080_p3;
wire  signed [10:0] sext_ln73_1127_fu_1088_p1;
wire  signed [10:0] sext_ln70_1596_fu_1076_p1;
wire  signed [7:0] tmp_935_fu_1098_p1;
wire  signed [7:0] sext_ln73_16_fu_1106_p0;
wire  signed [7:0] sext_ln70_1597_fu_1110_p0;
wire  signed [7:0] tmp_936_fu_1114_p1;
wire   [10:0] tmp_936_fu_1114_p3;
wire  signed [7:0] tmp_937_fu_1126_p1;
wire   [8:0] tmp_937_fu_1126_p3;
wire  signed [11:0] sext_ln73_1128_fu_1122_p1;
wire  signed [11:0] sext_ln73_1129_fu_1134_p1;
wire  signed [7:0] sext_ln70_1599_fu_1148_p0;
wire  signed [7:0] tmp_938_fu_1152_p1;
wire   [10:0] tmp_938_fu_1152_p3;
wire  signed [12:0] sext_ln73_1130_fu_1160_p1;
wire  signed [7:0] tmp_939_fu_1170_p1;
wire  signed [8:0] tmp_939_fu_1170_p3;
wire   [12:0] sub_ln73_1835_fu_1164_p2;
wire  signed [12:0] sext_ln73_1131_fu_1178_p1;
wire   [8:0] tmp_940_fu_1192_p3;
wire   [9:0] shl_ln73_7_fu_1204_p3;
wire  signed [10:0] sext_ln73_1133_fu_1212_p1;
wire  signed [7:0] sext_ln70_1601_fu_1222_p0;
wire  signed [7:0] shl_ln73_8_fu_1226_p1;
wire   [8:0] shl_ln73_8_fu_1226_p3;
wire  signed [8:0] sext_ln70_1601_fu_1222_p1;
wire  signed [7:0] tmp_941_fu_1244_p1;
wire   [9:0] tmp_941_fu_1244_p3;
wire  signed [10:0] sext_ln73_1134_fu_1252_p1;
wire   [10:0] sub_ln73_1838_fu_1256_p2;
wire  signed [7:0] sext_ln73_21_fu_1266_p0;
wire  signed [7:0] tmp_942_fu_1270_p1;
wire   [8:0] tmp_942_fu_1270_p3;
wire  signed [9:0] sext_ln73_1135_fu_1278_p1;
wire  signed [7:0] tmp_943_fu_1288_p1;
wire   [10:0] tmp_943_fu_1288_p3;
wire  signed [7:0] tmp_944_fu_1300_p1;
wire   [8:0] tmp_944_fu_1300_p3;
wire  signed [11:0] sext_ln73_1136_fu_1296_p1;
wire  signed [11:0] sext_ln73_1137_fu_1308_p1;
wire  signed [7:0] sext_ln73_22_fu_1318_p0;
wire  signed [7:0] tmp_945_fu_1322_p1;
wire   [9:0] tmp_945_fu_1322_p3;
wire  signed [10:0] sext_ln73_1138_fu_1330_p1;
wire  signed [10:0] sext_ln73_22_fu_1318_p1;
wire  signed [7:0] sext_ln70_1602_fu_1340_p0;
wire  signed [7:0] tmp_946_fu_1344_p1;
wire   [10:0] tmp_946_fu_1344_p3;
wire  signed [11:0] sext_ln73_1139_fu_1352_p1;
wire   [11:0] sub_ln73_1841_fu_1356_p2;
wire  signed [11:0] sext_ln70_1602_fu_1340_p1;
wire  signed [7:0] shl_ln73_9_fu_1368_p1;
wire  signed [11:0] sext_ln58_8960_fu_1385_p1;
wire   [11:0] sub_ln73_1810_fu_721_p2;
wire  signed [12:0] sext_ln58_368_fu_1382_p1;
wire  signed [12:0] sext_ln58_8965_fu_1399_p1;
wire   [12:0] add_ln58_7670_fu_1394_p2;
wire   [12:0] add_ln58_7672_fu_1402_p2;
wire  signed [12:0] sext_ln58_8967_fu_1415_p1;
wire  signed [12:0] sext_ln58_8966_fu_1412_p1;
wire   [11:0] add_ln58_7667_fu_1388_p2;
wire  signed [12:0] sext_ln58_9088_fu_1427_p1;
wire  signed [12:0] sext_ln58_9087_fu_1424_p1;
wire  signed [12:0] sext_ln58_8968_fu_1437_p1;
wire   [12:0] sub_ln58_3094_fu_1431_p2;
wire   [12:0] sub_ln58_1767_fu_1418_p2;
wire  signed [12:0] sext_ln73_6_fu_733_p1;
wire   [12:0] add_ln58_7675_fu_1446_p2;
wire  signed [13:0] sext_ln58_376_fu_1408_p1;
wire  signed [13:0] sext_ln73_7_fu_765_p1;
wire  signed [12:0] sext_ln58_9089_fu_1462_p1;
wire   [12:0] sub_ln58_3095_fu_1465_p2;
wire  signed [13:0] sext_ln58_8970_fu_1471_p1;
wire   [13:0] add_ln58_7676_fu_1456_p2;
wire  signed [10:0] sub_ln73_1827_fu_940_p2;
wire   [8:0] shl_ln73_5_fu_1068_p3;
wire  signed [8:0] sext_ln70_1580_fu_798_p1;
wire  signed [8:0] sext_ln70_1583_fu_872_p1;
wire   [8:0] add_ln58_7679_fu_1489_p2;
wire   [10:0] tmp_947_fu_1503_p3;
wire  signed [12:0] sext_ln58_9090_fu_1511_p1;
wire   [12:0] p_shl61_fu_1495_p3;
wire   [11:0] sub_ln73_1822_fu_842_p2;
wire  signed [11:0] sext_ln73_11_fu_936_p1;
wire   [11:0] add_ln58_7681_fu_1521_p2;
wire   [10:0] sub_ln73_1830_fu_1002_p2;
wire  signed [10:0] sext_ln73_1122_fu_962_p1;
wire   [10:0] sub_ln58_3097_fu_1531_p2;
wire  signed [12:0] sext_ln58_8976_fu_1537_p1;
wire  signed [12:0] sext_ln58_8975_fu_1527_p1;
wire   [9:0] tmp_931_fu_1044_p3;
wire   [10:0] shl_ln73_4_fu_1024_p3;
wire  signed [11:0] sext_ln58_9092_fu_1551_p1;
wire  signed [11:0] sext_ln58_9091_fu_1547_p1;
wire   [11:0] sub_ln58_3098_fu_1555_p2;
wire  signed [10:0] sext_ln73_10_fu_910_p1;
wire   [10:0] sub_ln58_3099_fu_1565_p2;
wire  signed [12:0] sext_ln58_8979_fu_1571_p1;
wire  signed [12:0] sext_ln58_8978_fu_1561_p1;
wire  signed [9:0] sext_ln58_8973_fu_1485_p1;
wire  signed [9:0] sext_ln73_1125_fu_1064_p1;
wire   [9:0] sub_ln58_3100_fu_1581_p2;
wire  signed [8:0] sext_ln73_16_fu_1106_p1;
wire  signed [8:0] sext_ln70_1598_fu_1144_p1;
wire   [8:0] add_ln58_7685_fu_1591_p2;
wire  signed [10:0] sext_ln58_8981_fu_1597_p1;
wire  signed [10:0] sext_ln58_8980_fu_1587_p1;
wire   [10:0] add_ln58_7686_fu_1601_p2;
wire  signed [12:0] sext_ln58_8982_fu_1607_p1;
wire   [12:0] add_ln58_7684_fu_1575_p2;
wire   [11:0] sub_ln73_1842_fu_1362_p2;
wire   [11:0] sub_ln73_1834_fu_1138_p2;
wire   [11:0] sub_ln73_1840_fu_1312_p2;
wire  signed [11:0] sext_ln73_20_fu_1262_p1;
wire  signed [9:0] sext_ln73_19_fu_1234_p1;
wire  signed [9:0] sext_ln73_1132_fu_1200_p1;
wire   [9:0] sub_ln58_3101_fu_1629_p2;
wire  signed [11:0] sext_ln58_8985_fu_1635_p1;
wire   [11:0] add_ln58_7692_fu_1623_p2;
wire  signed [8:0] sext_ln70_1582_fu_814_p1;
wire  signed [8:0] sext_ln70_1588_fu_950_p1;
wire  signed [8:0] add_ln58_7698_fu_1645_p2;
wire   [10:0] tmp_948_fu_1655_p3;
wire  signed [11:0] sext_ln58_9094_fu_1663_p1;
wire  signed [11:0] sext_ln58_9093_fu_1651_p1;
wire  signed [9:0] sext_ln73_12_fu_1016_p1;
wire  signed [9:0] sext_ln70_1579_fu_794_p1;
wire   [9:0] add_ln58_7700_fu_1673_p2;
wire  signed [10:0] sext_ln58_8988_fu_1679_p1;
wire   [10:0] add_ln58_7701_fu_1683_p2;
wire  signed [11:0] sext_ln58_8989_fu_1689_p1;
wire   [11:0] add_ln58_7699_fu_1667_p2;
wire  signed [8:0] sext_ln70_1597_fu_1110_p1;
wire   [10:0] add_ln73_2_fu_1334_p2;
wire   [10:0] sub_ln73_1833_fu_1092_p2;
wire   [10:0] add_ln58_7708_fu_1705_p2;
wire   [8:0] tmp_930_fu_1032_p3;
wire  signed [10:0] sext_ln58_9097_fu_1715_p1;
wire   [10:0] sub_ln58_3102_fu_1719_p2;
wire  signed [11:0] sext_ln58_8993_fu_1725_p1;
wire  signed [11:0] sext_ln58_8992_fu_1711_p1;
wire   [9:0] shl_ln73_9_fu_1368_p3;
wire  signed [10:0] sext_ln58_8995_fu_1735_p1;
wire  signed [10:0] sext_ln70_1592_fu_1040_p1;
wire  signed [9:0] sext_ln58_8996_fu_1745_p1;
wire  signed [9:0] sext_ln70_1593_fu_1052_p1;
wire   [9:0] sub_ln58_1769_fu_1748_p2;
wire  signed [10:0] sext_ln58_8997_fu_1754_p1;
wire   [10:0] sub_ln58_1768_fu_1739_p2;
wire   [10:0] add_ln58_7711_fu_1758_p2;
wire  signed [7:0] sext_ln58_8999_fu_1768_p0;
wire   [8:0] sub_ln73_481_fu_1238_p2;
wire  signed [9:0] sext_ln58_9000_fu_1772_p1;
wire  signed [9:0] sext_ln58_8999_fu_1768_p1;
wire  signed [8:0] sext_ln70_1599_fu_1148_p1;
wire  signed [8:0] sext_ln73_21_fu_1266_p1;
wire   [8:0] add_ln58_7712_fu_1782_p2;
wire  signed [9:0] sext_ln58_9001_fu_1788_p1;
wire   [9:0] sub_ln58_1770_fu_1776_p2;
wire   [9:0] add_ln58_7713_fu_1792_p2;
wire  signed [11:0] sext_ln58_9002_fu_1798_p1;
wire  signed [11:0] sext_ln58_8998_fu_1764_p1;
wire  signed [13:0] sext_ln58_378_fu_1452_p1;
wire  signed [13:0] sext_ln73_9_fu_791_p1;
wire   [11:0] sub_ln73_1824_fu_866_p2;
wire  signed [11:0] sext_ln58_8971_fu_1481_p1;
wire  signed [9:0] sext_ln70_1584_fu_884_p1;
wire  signed [9:0] sext_ln70_1585_fu_888_p1;
wire   [8:0] tmp_922_fu_802_p3;
wire   [9:0] add_ln58_7719_fu_1825_p2;
wire  signed [10:0] sext_ln58_9099_fu_1835_p1;
wire  signed [10:0] sext_ln58_9098_fu_1831_p1;
wire   [10:0] sub_ln58_3104_fu_1839_p2;
wire  signed [11:0] sext_ln58_9006_fu_1845_p1;
wire   [11:0] add_ln58_7718_fu_1819_p2;
wire  signed [8:0] sext_ln70_1589_fu_982_p1;
wire   [11:0] sub_ln73_1829_fu_976_p2;
wire   [11:0] sub_ln58_3107_fu_1861_p2;
wire   [11:0] sub_ln73_1843_fu_1376_p2;
wire   [11:0] sub_ln58_3108_fu_1871_p2;
wire  signed [12:0] sext_ln58_9010_fu_1877_p1;
wire  signed [12:0] sext_ln58_9009_fu_1867_p1;
wire   [10:0] sub_ln73_1837_fu_1216_p2;
wire  signed [11:0] sext_ln58_9102_fu_1887_p1;
wire   [8:0] tmp_935_fu_1098_p3;
wire   [9:0] sub_ln73_1839_fu_1282_p2;
wire  signed [10:0] sext_ln58_9104_fu_1901_p1;
wire  signed [10:0] sext_ln58_9103_fu_1897_p1;
wire   [10:0] sub_ln58_3110_fu_1905_p2;
wire  signed [11:0] sext_ln58_9012_fu_1911_p1;
wire   [11:0] sub_ln58_3109_fu_1891_p2;
wire  signed [9:0] sext_ln70_1591_fu_1020_p1;
wire   [9:0] sub_ln58_1771_fu_1921_p2;
wire  signed [9:0] sext_ln70_1600_fu_1188_p1;
wire   [9:0] add_ln58_7727_fu_1931_p2;
wire  signed [10:0] sext_ln58_9015_fu_1937_p1;
wire  signed [10:0] sext_ln58_9014_fu_1927_p1;
wire   [10:0] tmp_933_fu_1953_p3;
wire  signed [12:0] sext_ln73_1126_fu_1960_p1;
wire   [12:0] sub_ln73_1831_fu_1964_p2;
wire  signed [12:0] sext_ln70_1595_fu_1950_p1;
wire  signed [14:0] sext_ln58_8974_fu_1985_p1;
wire  signed [14:0] sext_ln58_379_fu_1982_p1;
wire  signed [14:0] sext_ln58_8977_fu_1994_p1;
wire   [14:0] add_ln58_7680_fu_1988_p2;
wire  signed [14:0] sext_ln58_8983_fu_2003_p1;
wire   [14:0] add_ln58_7683_fu_1997_p2;
wire   [14:0] add_ln58_7688_fu_2006_p2;
wire  signed [15:0] sext_ln58_383_fu_2012_p1;
wire  signed [15:0] sext_ln42_fu_1976_p1;
wire  signed [13:0] sext_ln58_377_fu_1979_p1;
wire  signed [13:0] sext_ln73_8_fu_1947_p1;
wire  signed [13:0] sext_ln58_8987_fu_2028_p1;
wire   [13:0] add_ln58_7695_fu_2022_p2;
wire  signed [13:0] sext_ln58_8990_fu_2037_p1;
wire   [13:0] add_ln58_7697_fu_2031_p2;
wire   [10:0] tmp_949_fu_2049_p3;
wire  signed [11:0] sext_ln58_9096_fu_2056_p1;
wire  signed [11:0] sext_ln58_9095_fu_2046_p1;
wire  signed [13:0] sext_ln58_9004_fu_2066_p1;
wire  signed [13:0] sext_ln58_9007_fu_2074_p1;
wire   [13:0] add_ln58_7717_fu_2069_p2;
wire   [13:0] add_ln58_7721_fu_2077_p2;
wire   [11:0] tmp_950_fu_2090_p3;
wire  signed [12:0] sext_ln58_9101_fu_2097_p1;
wire   [12:0] sub_ln58_3105_fu_2101_p2;
wire  signed [12:0] sext_ln58_9100_fu_2087_p1;
wire   [12:0] sub_ln58_3106_fu_2107_p2;
wire  signed [14:0] sext_ln58_9008_fu_2113_p1;
wire  signed [14:0] sext_ln58_387_fu_2083_p1;
wire  signed [12:0] sext_ln58_9016_fu_2126_p1;
wire  signed [12:0] sext_ln58_9013_fu_2123_p1;
wire    ap_CS_fsm_state4;
wire  signed [15:0] sext_ln58_8984_fu_2138_p1;
wire  signed [15:0] sext_ln58_8986_fu_2146_p1;
wire   [15:0] add_ln58_7691_fu_2141_p2;
wire   [15:0] add_ln58_7694_fu_2149_p2;
wire  signed [14:0] sext_ln58_385_fu_2159_p1;
wire  signed [14:0] sext_ln73_15_fu_2135_p1;
wire  signed [14:0] sext_ln58_8991_fu_2168_p1;
wire   [14:0] add_ln58_7704_fu_2162_p2;
wire  signed [14:0] sext_ln58_8994_fu_2177_p1;
wire   [14:0] add_ln58_7707_fu_2171_p2;
wire  signed [14:0] sext_ln58_9003_fu_2186_p1;
wire   [14:0] add_ln58_7710_fu_2180_p2;
wire   [14:0] add_ln58_7715_fu_2189_p2;
wire  signed [14:0] sext_ln58_9011_fu_2199_p1;
wire  signed [14:0] sext_ln58_9017_fu_2207_p1;
wire   [14:0] add_ln58_7725_fu_2202_p2;
wire   [14:0] add_ln58_7730_fu_2210_p2;
wire  signed [21:0] sext_ln58_384_fu_2155_p1;
wire  signed [21:0] sext_ln58_386_fu_2195_p1;
wire  signed [21:0] sext_ln68_fu_2216_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln58_7666_reg_2288 <= add_ln58_7666_fu_654_p2;
        add_ln58_7669_reg_2293 <= add_ln58_7669_fu_666_p2;
        add_ln58_7671_reg_2298 <= add_ln58_7671_fu_694_p2;
        add_ln58_7673_reg_2303 <= add_ln58_7673_fu_700_p2;
        add_ln58_7677_reg_2308 <= add_ln58_7677_fu_706_p2;
        add_ln58_7696_reg_2313 <= add_ln58_7696_fu_712_p2;
        add_ln58_reg_2283[11 : 1] <= add_ln58_fu_628_p2[11 : 1];
        add_ln73_1_reg_2273 <= add_ln73_1_fu_612_p2;
        data_1_val_read_reg_2248 <= data_1_val;
        data_4_val_read_reg_2243 <= data_4_val;
        data_5_val_read_reg_2238 <= data_5_val;
        sext_ln73_1104_reg_2258[11 : 3] <= sext_ln73_1104_fu_412_p1[11 : 3];
        sext_ln73_1112_reg_2268[11 : 3] <= sext_ln73_1112_fu_536_p1[11 : 3];
        sub_ln73_1809_reg_2253[12 : 2] <= sub_ln73_1809_fu_398_p2[12 : 2];
        sub_ln73_480_reg_2278 <= sub_ln73_480_fu_622_p2;
        tmp_912_reg_2263[10 : 3] <= tmp_912_fu_456_p3[10 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln58_7674_reg_2334 <= add_ln58_7674_fu_1440_p2;
        add_ln58_7678_reg_2339 <= add_ln58_7678_fu_1475_p2;
        add_ln58_7682_reg_2349 <= add_ln58_7682_fu_1541_p2;
        add_ln58_7687_reg_2354 <= add_ln58_7687_fu_1611_p2;
        add_ln58_7690_reg_2359 <= add_ln58_7690_fu_1617_p2;
        add_ln58_7693_reg_2364[11 : 1] <= add_ln58_7693_fu_1639_p2[11 : 1];
        add_ln58_7702_reg_2369 <= add_ln58_7702_fu_1693_p2;
        add_ln58_7705_reg_2374 <= add_ln58_7705_fu_1699_p2;
        add_ln58_7709_reg_2380 <= add_ln58_7709_fu_1729_p2;
        add_ln58_7714_reg_2385 <= add_ln58_7714_fu_1802_p2;
        add_ln58_7716_reg_2390 <= add_ln58_7716_fu_1808_p2;
        add_ln58_7720_reg_2400 <= add_ln58_7720_fu_1849_p2;
        add_ln58_7722_reg_2405 <= add_ln58_7722_fu_1855_p2;
        add_ln58_7724_reg_2411 <= add_ln58_7724_fu_1881_p2;
        add_ln58_7726_reg_2416[11 : 1] <= add_ln58_7726_fu_1915_p2[11 : 1];
        add_ln58_7728_reg_2421 <= add_ln58_7728_fu_1941_p2;
        data_20_val_read_reg_2318 <= ap_port_reg_data_20_val;
        sub_ln58_3096_reg_2344[12 : 2] <= sub_ln58_3096_fu_1515_p2[12 : 2];
        sub_ln58_3103_reg_2395 <= sub_ln58_3103_fu_1814_p2;
        sub_ln73_1817_reg_2324[11 : 1] <= sub_ln73_1817_fu_785_p2[11 : 1];
        sub_ln73_1836_reg_2329[12 : 1] <= sub_ln73_1836_fu_1182_p2[12 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln58_7689_reg_2431 <= add_ln58_7689_fu_2016_p2;
        add_ln58_7703_reg_2436 <= add_ln58_7703_fu_2040_p2;
        add_ln58_7706_reg_2441 <= add_ln58_7706_fu_2060_p2;
        add_ln58_7723_reg_2446 <= add_ln58_7723_fu_2117_p2;
        add_ln58_7729_reg_2451 <= add_ln58_7729_fu_2129_p2;
        sub_ln73_1832_reg_2426 <= sub_ln73_1832_fu_1970_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_port_reg_data_10_val <= data_10_val;
        ap_port_reg_data_11_val <= data_11_val;
        ap_port_reg_data_12_val <= data_12_val;
        ap_port_reg_data_13_val <= data_13_val;
        ap_port_reg_data_14_val <= data_14_val;
        ap_port_reg_data_15_val <= data_15_val;
        ap_port_reg_data_16_val <= data_16_val;
        ap_port_reg_data_17_val <= data_17_val;
        ap_port_reg_data_18_val <= data_18_val;
        ap_port_reg_data_20_val <= data_20_val;
        ap_port_reg_data_21_val <= data_21_val;
        ap_port_reg_data_22_val <= data_22_val;
        ap_port_reg_data_23_val <= data_23_val;
        ap_port_reg_data_24_val <= data_24_val;
        ap_port_reg_data_26_val <= data_26_val;
        ap_port_reg_data_27_val <= data_27_val;
        ap_port_reg_data_28_val <= data_28_val;
        ap_port_reg_data_29_val <= data_29_val;
        ap_port_reg_data_30_val <= data_30_val;
        ap_port_reg_data_31_val <= data_31_val;
        ap_port_reg_data_6_val <= data_6_val;
        ap_port_reg_data_9_val <= data_9_val;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_7664_fu_634_p2 = ($signed(add_ln73_fu_362_p2) + $signed(11'd1888));

assign add_ln58_7665_fu_640_p2 = (sub_ln73_1808_fu_368_p2 + 10'd96);

assign add_ln58_7666_fu_654_p2 = ($signed(add_ln58_7664_fu_634_p2) + $signed(sext_ln58_fu_650_p1));

assign add_ln58_7667_fu_1388_p2 = ($signed(sext_ln58_8960_fu_1385_p1) + $signed(sub_ln73_1810_fu_721_p2));

assign add_ln58_7668_fu_660_p2 = ($signed(sub_ln73_1811_fu_428_p2) + $signed(sext_ln58_370_fu_646_p1));

assign add_ln58_7669_fu_666_p2 = (add_ln58_7668_fu_660_p2 + sub_ln73_1812_fu_480_p2);

assign add_ln58_7670_fu_1394_p2 = ($signed(sub_ln73_1809_reg_2253) + $signed(sext_ln58_368_fu_1382_p1));

assign add_ln58_7671_fu_694_p2 = ($signed(sext_ln58_8964_fu_690_p1) + $signed(sext_ln73_3_fu_452_p1));

assign add_ln58_7672_fu_1402_p2 = ($signed(sext_ln58_8965_fu_1399_p1) + $signed(add_ln58_7670_fu_1394_p2));

assign add_ln58_7673_fu_700_p2 = ($signed(sub_ln73_1814_fu_518_p2) + $signed(sext_ln58_8961_fu_672_p1));

assign add_ln58_7674_fu_1440_p2 = ($signed(sext_ln58_8968_fu_1437_p1) + $signed(sub_ln58_3094_fu_1431_p2));

assign add_ln58_7675_fu_1446_p2 = ($signed(sub_ln58_1767_fu_1418_p2) + $signed(sext_ln73_6_fu_733_p1));

assign add_ln58_7676_fu_1456_p2 = ($signed(sext_ln58_376_fu_1408_p1) + $signed(sext_ln73_7_fu_765_p1));

assign add_ln58_7677_fu_706_p2 = (sub_ln73_1818_fu_552_p2 + sub_ln73_1820_fu_584_p2);

assign add_ln58_7678_fu_1475_p2 = ($signed(sext_ln58_8970_fu_1471_p1) + $signed(add_ln58_7676_fu_1456_p2));

assign add_ln58_7679_fu_1489_p2 = ($signed(sext_ln70_1580_fu_798_p1) + $signed(sext_ln70_1583_fu_872_p1));

assign add_ln58_7680_fu_1988_p2 = ($signed(sext_ln58_8974_fu_1985_p1) + $signed(sext_ln58_379_fu_1982_p1));

assign add_ln58_7681_fu_1521_p2 = ($signed(sub_ln73_1822_fu_842_p2) + $signed(sext_ln73_11_fu_936_p1));

assign add_ln58_7682_fu_1541_p2 = ($signed(sext_ln58_8976_fu_1537_p1) + $signed(sext_ln58_8975_fu_1527_p1));

assign add_ln58_7683_fu_1997_p2 = ($signed(sext_ln58_8977_fu_1994_p1) + $signed(add_ln58_7680_fu_1988_p2));

assign add_ln58_7684_fu_1575_p2 = ($signed(sext_ln58_8979_fu_1571_p1) + $signed(sext_ln58_8978_fu_1561_p1));

assign add_ln58_7685_fu_1591_p2 = ($signed(sext_ln73_16_fu_1106_p1) + $signed(sext_ln70_1598_fu_1144_p1));

assign add_ln58_7686_fu_1601_p2 = ($signed(sext_ln58_8981_fu_1597_p1) + $signed(sext_ln58_8980_fu_1587_p1));

assign add_ln58_7687_fu_1611_p2 = ($signed(sext_ln58_8982_fu_1607_p1) + $signed(add_ln58_7684_fu_1575_p2));

assign add_ln58_7688_fu_2006_p2 = ($signed(sext_ln58_8983_fu_2003_p1) + $signed(add_ln58_7683_fu_1997_p2));

assign add_ln58_7689_fu_2016_p2 = ($signed(sext_ln58_383_fu_2012_p1) + $signed(sext_ln42_fu_1976_p1));

assign add_ln58_7690_fu_1617_p2 = (sub_ln73_1842_fu_1362_p2 + sub_ln73_1834_fu_1138_p2);

assign add_ln58_7691_fu_2141_p2 = ($signed(sext_ln58_8984_fu_2138_p1) + $signed(add_ln58_7689_reg_2431));

assign add_ln58_7692_fu_1623_p2 = ($signed(sub_ln73_1840_fu_1312_p2) + $signed(sext_ln73_20_fu_1262_p1));

assign add_ln58_7693_fu_1639_p2 = ($signed(sext_ln58_8985_fu_1635_p1) + $signed(add_ln58_7692_fu_1623_p2));

assign add_ln58_7694_fu_2149_p2 = ($signed(sext_ln58_8986_fu_2146_p1) + $signed(add_ln58_7691_fu_2141_p2));

assign add_ln58_7695_fu_2022_p2 = ($signed(sext_ln58_377_fu_1979_p1) + $signed(sext_ln73_8_fu_1947_p1));

assign add_ln58_7696_fu_712_p2 = (sub_ln73_1819_fu_558_p2 + sub_ln73_1821_fu_602_p2);

assign add_ln58_7697_fu_2031_p2 = ($signed(sext_ln58_8987_fu_2028_p1) + $signed(add_ln58_7695_fu_2022_p2));

assign add_ln58_7698_fu_1645_p2 = ($signed(sext_ln70_1582_fu_814_p1) + $signed(sext_ln70_1588_fu_950_p1));

assign add_ln58_7699_fu_1667_p2 = ($signed(sext_ln58_9094_fu_1663_p1) + $signed(sext_ln58_9093_fu_1651_p1));

assign add_ln58_7700_fu_1673_p2 = ($signed(sext_ln73_12_fu_1016_p1) + $signed(sext_ln70_1579_fu_794_p1));

assign add_ln58_7701_fu_1683_p2 = ($signed(sext_ln58_8988_fu_1679_p1) + $signed(sub_ln73_1827_fu_940_p2));

assign add_ln58_7702_fu_1693_p2 = ($signed(sext_ln58_8989_fu_1689_p1) + $signed(add_ln58_7699_fu_1667_p2));

assign add_ln58_7703_fu_2040_p2 = ($signed(sext_ln58_8990_fu_2037_p1) + $signed(add_ln58_7697_fu_2031_p2));

assign add_ln58_7704_fu_2162_p2 = ($signed(sext_ln58_385_fu_2159_p1) + $signed(sext_ln73_15_fu_2135_p1));

assign add_ln58_7705_fu_1699_p2 = ($signed(sext_ln70_1597_fu_1110_p1) + $signed(sext_ln70_1598_fu_1144_p1));

assign add_ln58_7706_fu_2060_p2 = ($signed(sext_ln58_9096_fu_2056_p1) + $signed(sext_ln58_9095_fu_2046_p1));

assign add_ln58_7707_fu_2171_p2 = ($signed(sext_ln58_8991_fu_2168_p1) + $signed(add_ln58_7704_fu_2162_p2));

assign add_ln58_7708_fu_1705_p2 = (add_ln73_2_fu_1334_p2 + sub_ln73_1833_fu_1092_p2);

assign add_ln58_7709_fu_1729_p2 = ($signed(sext_ln58_8993_fu_1725_p1) + $signed(sext_ln58_8992_fu_1711_p1));

assign add_ln58_7710_fu_2180_p2 = ($signed(sext_ln58_8994_fu_2177_p1) + $signed(add_ln58_7707_fu_2171_p2));

assign add_ln58_7711_fu_1758_p2 = ($signed(sext_ln58_8997_fu_1754_p1) + $signed(sub_ln58_1768_fu_1739_p2));

assign add_ln58_7712_fu_1782_p2 = ($signed(sext_ln70_1599_fu_1148_p1) + $signed(sext_ln73_21_fu_1266_p1));

assign add_ln58_7713_fu_1792_p2 = ($signed(sext_ln58_9001_fu_1788_p1) + $signed(sub_ln58_1770_fu_1776_p2));

assign add_ln58_7714_fu_1802_p2 = ($signed(sext_ln58_9002_fu_1798_p1) + $signed(sext_ln58_8998_fu_1764_p1));

assign add_ln58_7715_fu_2189_p2 = ($signed(sext_ln58_9003_fu_2186_p1) + $signed(add_ln58_7710_fu_2180_p2));

assign add_ln58_7716_fu_1808_p2 = ($signed(sext_ln58_378_fu_1452_p1) + $signed(sext_ln73_9_fu_791_p1));

assign add_ln58_7717_fu_2069_p2 = ($signed(sext_ln58_9004_fu_2066_p1) + $signed(add_ln58_7716_reg_2390));

assign add_ln58_7718_fu_1819_p2 = ($signed(sext_ln73_1110_fu_769_p1) + $signed(sext_ln58_8971_fu_1481_p1));

assign add_ln58_7719_fu_1825_p2 = ($signed(sext_ln70_1584_fu_884_p1) + $signed(sext_ln70_1585_fu_888_p1));

assign add_ln58_7720_fu_1849_p2 = ($signed(sext_ln58_9006_fu_1845_p1) + $signed(add_ln58_7718_fu_1819_p2));

assign add_ln58_7721_fu_2077_p2 = ($signed(sext_ln58_9007_fu_2074_p1) + $signed(add_ln58_7717_fu_2069_p2));

assign add_ln58_7722_fu_1855_p2 = ($signed(sext_ln70_1589_fu_982_p1) + $signed(sext_ln70_1598_fu_1144_p1));

assign add_ln58_7723_fu_2117_p2 = ($signed(sext_ln58_9008_fu_2113_p1) + $signed(sext_ln58_387_fu_2083_p1));

assign add_ln58_7724_fu_1881_p2 = ($signed(sext_ln58_9010_fu_1877_p1) + $signed(sext_ln58_9009_fu_1867_p1));

assign add_ln58_7725_fu_2202_p2 = ($signed(sext_ln58_9011_fu_2199_p1) + $signed(add_ln58_7723_reg_2446));

assign add_ln58_7726_fu_1915_p2 = ($signed(sext_ln58_9012_fu_1911_p1) + $signed(sub_ln58_3109_fu_1891_p2));

assign add_ln58_7727_fu_1931_p2 = ($signed(sext_ln70_1600_fu_1188_p1) + $signed(sext_ln70_1593_fu_1052_p1));

assign add_ln58_7728_fu_1941_p2 = ($signed(sext_ln58_9015_fu_1937_p1) + $signed(sext_ln58_9014_fu_1927_p1));

assign add_ln58_7729_fu_2129_p2 = ($signed(sext_ln58_9016_fu_2126_p1) + $signed(sext_ln58_9013_fu_2123_p1));

assign add_ln58_7730_fu_2210_p2 = ($signed(sext_ln58_9017_fu_2207_p1) + $signed(add_ln58_7725_fu_2202_p2));

assign add_ln58_fu_628_p2 = ($signed(sub_ln73_1807_fu_344_p2) + $signed(12'd4064));

assign add_ln73_1_fu_612_p2 = ($signed(sext_ln73_1116_fu_608_p1) + $signed(sext_ln70_1577_fu_564_p1));

assign add_ln73_2_fu_1334_p2 = ($signed(sext_ln73_1138_fu_1330_p1) + $signed(sext_ln73_22_fu_1318_p1));

assign add_ln73_fu_362_p2 = ($signed(sext_ln73_1101_fu_358_p1) + $signed(sext_ln73_1_fu_310_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_return_0 = sext_ln58_384_fu_2155_p1;

assign ap_return_1 = sext_ln58_386_fu_2195_p1;

assign ap_return_2 = sext_ln68_fu_2216_p1;

assign p_shl61_fu_1495_p3 = {{add_ln58_7679_fu_1489_p2}, {4'd0}};

assign sext_ln42_fu_1976_p1 = $signed(sub_ln73_1836_reg_2329);

assign sext_ln58_368_fu_1382_p1 = $signed(add_ln58_reg_2283);

assign sext_ln58_370_fu_646_p1 = $signed(add_ln58_7665_fu_640_p2);

assign sext_ln58_376_fu_1408_p1 = $signed(add_ln58_7672_fu_1402_p2);

assign sext_ln58_377_fu_1979_p1 = $signed(add_ln58_7674_reg_2334);

assign sext_ln58_378_fu_1452_p1 = $signed(add_ln58_7675_fu_1446_p2);

assign sext_ln58_379_fu_1982_p1 = $signed(add_ln58_7678_reg_2339);

assign sext_ln58_383_fu_2012_p1 = $signed(add_ln58_7688_fu_2006_p2);

assign sext_ln58_384_fu_2155_p1 = $signed(add_ln58_7694_fu_2149_p2);

assign sext_ln58_385_fu_2159_p1 = $signed(add_ln58_7703_reg_2436);

assign sext_ln58_386_fu_2195_p1 = $signed(add_ln58_7715_fu_2189_p2);

assign sext_ln58_387_fu_2083_p1 = $signed(add_ln58_7721_fu_2077_p2);

assign sext_ln58_8960_fu_1385_p1 = $signed(add_ln58_7666_reg_2288);

assign sext_ln58_8961_fu_672_p1 = sub_ln73_479_fu_490_p2;

assign sext_ln58_8962_fu_676_p0 = data_2_val;

assign sext_ln58_8962_fu_676_p1 = sext_ln58_8962_fu_676_p0;

assign sext_ln58_8963_fu_680_p1 = sub_ln73_479_fu_490_p2;

assign sext_ln58_8964_fu_690_p1 = $signed(sub_ln58_fu_684_p2);

assign sext_ln58_8965_fu_1399_p1 = $signed(add_ln58_7671_reg_2298);

assign sext_ln58_8966_fu_1412_p1 = data_4_val_read_reg_2243;

assign sext_ln58_8967_fu_1415_p1 = $signed(add_ln58_7669_reg_2293);

assign sext_ln58_8968_fu_1437_p1 = $signed(add_ln58_7673_reg_2303);

assign sext_ln58_8970_fu_1471_p1 = $signed(sub_ln58_3095_fu_1465_p2);

assign sext_ln58_8971_fu_1481_p1 = sub_ln73_1827_fu_940_p2;

assign sext_ln58_8973_fu_1485_p1 = $signed(shl_ln73_5_fu_1068_p3);

assign sext_ln58_8974_fu_1985_p1 = $signed(sub_ln58_3096_reg_2344);

assign sext_ln58_8975_fu_1527_p1 = $signed(add_ln58_7681_fu_1521_p2);

assign sext_ln58_8976_fu_1537_p1 = $signed(sub_ln58_3097_fu_1531_p2);

assign sext_ln58_8977_fu_1994_p1 = $signed(add_ln58_7682_reg_2349);

assign sext_ln58_8978_fu_1561_p1 = $signed(sub_ln58_3098_fu_1555_p2);

assign sext_ln58_8979_fu_1571_p1 = $signed(sub_ln58_3099_fu_1565_p2);

assign sext_ln58_8980_fu_1587_p1 = $signed(sub_ln58_3100_fu_1581_p2);

assign sext_ln58_8981_fu_1597_p1 = $signed(add_ln58_7685_fu_1591_p2);

assign sext_ln58_8982_fu_1607_p1 = $signed(add_ln58_7686_fu_1601_p2);

assign sext_ln58_8983_fu_2003_p1 = $signed(add_ln58_7687_reg_2354);

assign sext_ln58_8984_fu_2138_p1 = $signed(add_ln58_7690_reg_2359);

assign sext_ln58_8985_fu_1635_p1 = $signed(sub_ln58_3101_fu_1629_p2);

assign sext_ln58_8986_fu_2146_p1 = $signed(add_ln58_7693_reg_2364);

assign sext_ln58_8987_fu_2028_p1 = $signed(add_ln58_7696_reg_2313);

assign sext_ln58_8988_fu_1679_p1 = $signed(add_ln58_7700_fu_1673_p2);

assign sext_ln58_8989_fu_1689_p1 = $signed(add_ln58_7701_fu_1683_p2);

assign sext_ln58_8990_fu_2037_p1 = $signed(add_ln58_7702_reg_2369);

assign sext_ln58_8991_fu_2168_p1 = $signed(add_ln58_7706_reg_2441);

assign sext_ln58_8992_fu_1711_p1 = $signed(add_ln58_7708_fu_1705_p2);

assign sext_ln58_8993_fu_1725_p1 = $signed(sub_ln58_3102_fu_1719_p2);

assign sext_ln58_8994_fu_2177_p1 = $signed(add_ln58_7709_reg_2380);

assign sext_ln58_8995_fu_1735_p1 = $signed(shl_ln73_9_fu_1368_p3);

assign sext_ln58_8996_fu_1745_p1 = $signed(sub_ln73_480_reg_2278);

assign sext_ln58_8997_fu_1754_p1 = $signed(sub_ln58_1769_fu_1748_p2);

assign sext_ln58_8998_fu_1764_p1 = $signed(add_ln58_7711_fu_1758_p2);

assign sext_ln58_8999_fu_1768_p0 = ap_port_reg_data_22_val;

assign sext_ln58_8999_fu_1768_p1 = sext_ln58_8999_fu_1768_p0;

assign sext_ln58_9000_fu_1772_p1 = $signed(sub_ln73_481_fu_1238_p2);

assign sext_ln58_9001_fu_1788_p1 = $signed(add_ln58_7712_fu_1782_p2);

assign sext_ln58_9002_fu_1798_p1 = $signed(add_ln58_7713_fu_1792_p2);

assign sext_ln58_9003_fu_2186_p1 = $signed(add_ln58_7714_reg_2385);

assign sext_ln58_9004_fu_2066_p1 = $signed(sub_ln58_3103_reg_2395);

assign sext_ln58_9006_fu_1845_p1 = $signed(sub_ln58_3104_fu_1839_p2);

assign sext_ln58_9007_fu_2074_p1 = $signed(add_ln58_7720_reg_2400);

assign sext_ln58_9008_fu_2113_p1 = $signed(sub_ln58_3106_fu_2107_p2);

assign sext_ln58_9009_fu_1867_p1 = $signed(sub_ln58_3107_fu_1861_p2);

assign sext_ln58_9010_fu_1877_p1 = $signed(sub_ln58_3108_fu_1871_p2);

assign sext_ln58_9011_fu_2199_p1 = $signed(add_ln58_7724_reg_2411);

assign sext_ln58_9012_fu_1911_p1 = $signed(sub_ln58_3110_fu_1905_p2);

assign sext_ln58_9013_fu_2123_p1 = $signed(add_ln58_7726_reg_2416);

assign sext_ln58_9014_fu_1927_p1 = $signed(sub_ln58_1771_fu_1921_p2);

assign sext_ln58_9015_fu_1937_p1 = $signed(add_ln58_7727_fu_1931_p2);

assign sext_ln58_9016_fu_2126_p1 = $signed(add_ln58_7728_reg_2421);

assign sext_ln58_9017_fu_2207_p1 = $signed(add_ln58_7729_reg_2451);

assign sext_ln58_9087_fu_1424_p1 = tmp_912_reg_2263;

assign sext_ln58_9088_fu_1427_p1 = $signed(add_ln58_7667_fu_1388_p2);

assign sext_ln58_9089_fu_1462_p1 = $signed(add_ln58_7677_reg_2308);

assign sext_ln58_9090_fu_1511_p1 = $signed(tmp_947_fu_1503_p3);

assign sext_ln58_9091_fu_1547_p1 = $signed(tmp_931_fu_1044_p3);

assign sext_ln58_9092_fu_1551_p1 = $signed(shl_ln73_4_fu_1024_p3);

assign sext_ln58_9093_fu_1651_p1 = add_ln58_7698_fu_1645_p2;

assign sext_ln58_9094_fu_1663_p1 = $signed(tmp_948_fu_1655_p3);

assign sext_ln58_9095_fu_2046_p1 = add_ln58_7705_reg_2374;

assign sext_ln58_9096_fu_2056_p1 = $signed(tmp_949_fu_2049_p3);

assign sext_ln58_9097_fu_1715_p1 = $signed(tmp_930_fu_1032_p3);

assign sext_ln58_9098_fu_1831_p1 = $signed(tmp_922_fu_802_p3);

assign sext_ln58_9099_fu_1835_p1 = $signed(add_ln58_7719_fu_1825_p2);

assign sext_ln58_9100_fu_2087_p1 = add_ln58_7722_reg_2405;

assign sext_ln58_9101_fu_2097_p1 = $signed(tmp_950_fu_2090_p3);

assign sext_ln58_9102_fu_1887_p1 = $signed(sub_ln73_1837_fu_1216_p2);

assign sext_ln58_9103_fu_1897_p1 = $signed(tmp_935_fu_1098_p3);

assign sext_ln58_9104_fu_1901_p1 = $signed(sub_ln73_1839_fu_1282_p2);

assign sext_ln58_fu_650_p1 = $signed(sub_ln73_fu_438_p2);

assign sext_ln68_fu_2216_p1 = $signed(add_ln58_7730_fu_2210_p2);

assign sext_ln70_1572_fu_434_p0 = data_2_val;

assign sext_ln70_1572_fu_434_p1 = sext_ln70_1572_fu_434_p0;

assign sext_ln70_1573_fu_486_p0 = data_4_val;

assign sext_ln70_1573_fu_486_p1 = sext_ln70_1573_fu_486_p0;

assign sext_ln70_1574_fu_496_p0 = data_5_val;

assign sext_ln70_1574_fu_496_p1 = sext_ln70_1574_fu_496_p0;

assign sext_ln70_1575_fu_737_p0 = ap_port_reg_data_6_val;

assign sext_ln70_1575_fu_737_p1 = sext_ln70_1575_fu_737_p0;

assign sext_ln70_1576_fu_524_p0 = data_7_val;

assign sext_ln70_1576_fu_524_p1 = sext_ln70_1576_fu_524_p0;

assign sext_ln70_1577_fu_564_p0 = data_8_val;

assign sext_ln70_1577_fu_564_p1 = sext_ln70_1577_fu_564_p0;

assign sext_ln70_1578_fu_568_p0 = data_8_val;

assign sext_ln70_1578_fu_568_p1 = sext_ln70_1578_fu_568_p0;

assign sext_ln70_1579_fu_794_p0 = ap_port_reg_data_9_val;

assign sext_ln70_1579_fu_794_p1 = sext_ln70_1579_fu_794_p0;

assign sext_ln70_1580_fu_798_p0 = ap_port_reg_data_9_val;

assign sext_ln70_1580_fu_798_p1 = sext_ln70_1580_fu_798_p0;

assign sext_ln70_1581_fu_810_p0 = ap_port_reg_data_10_val;

assign sext_ln70_1581_fu_810_p1 = sext_ln70_1581_fu_810_p0;

assign sext_ln70_1582_fu_814_p0 = ap_port_reg_data_10_val;

assign sext_ln70_1582_fu_814_p1 = sext_ln70_1582_fu_814_p0;

assign sext_ln70_1583_fu_872_p0 = ap_port_reg_data_11_val;

assign sext_ln70_1583_fu_872_p1 = sext_ln70_1583_fu_872_p0;

assign sext_ln70_1584_fu_884_p1 = $signed(shl_ln73_2_fu_876_p3);

assign sext_ln70_1585_fu_888_p0 = ap_port_reg_data_12_val;

assign sext_ln70_1585_fu_888_p1 = sext_ln70_1585_fu_888_p0;

assign sext_ln70_1586_fu_914_p0 = ap_port_reg_data_13_val;

assign sext_ln70_1586_fu_914_p1 = sext_ln70_1586_fu_914_p0;

assign sext_ln70_1587_fu_946_p0 = ap_port_reg_data_14_val;

assign sext_ln70_1587_fu_946_p1 = sext_ln70_1587_fu_946_p0;

assign sext_ln70_1588_fu_950_p0 = ap_port_reg_data_14_val;

assign sext_ln70_1588_fu_950_p1 = sext_ln70_1588_fu_950_p0;

assign sext_ln70_1589_fu_982_p0 = ap_port_reg_data_15_val;

assign sext_ln70_1589_fu_982_p1 = sext_ln70_1589_fu_982_p0;

assign sext_ln70_1590_fu_986_p0 = ap_port_reg_data_15_val;

assign sext_ln70_1590_fu_986_p1 = sext_ln70_1590_fu_986_p0;

assign sext_ln70_1591_fu_1020_p0 = ap_port_reg_data_16_val;

assign sext_ln70_1591_fu_1020_p1 = sext_ln70_1591_fu_1020_p0;

assign sext_ln70_1592_fu_1040_p0 = ap_port_reg_data_17_val;

assign sext_ln70_1592_fu_1040_p1 = sext_ln70_1592_fu_1040_p0;

assign sext_ln70_1593_fu_1052_p0 = ap_port_reg_data_18_val;

assign sext_ln70_1593_fu_1052_p1 = sext_ln70_1593_fu_1052_p0;

assign sext_ln70_1594_fu_618_p1 = $signed(data_19_val);

assign sext_ln70_1595_fu_1950_p1 = data_20_val_read_reg_2318;

assign sext_ln70_1596_fu_1076_p0 = ap_port_reg_data_21_val;

assign sext_ln70_1596_fu_1076_p1 = sext_ln70_1596_fu_1076_p0;

assign sext_ln70_1597_fu_1110_p0 = ap_port_reg_data_23_val;

assign sext_ln70_1597_fu_1110_p1 = sext_ln70_1597_fu_1110_p0;

assign sext_ln70_1598_fu_1144_p1 = $signed(ap_port_reg_data_24_val);

assign sext_ln70_1599_fu_1148_p0 = ap_port_reg_data_26_val;

assign sext_ln70_1599_fu_1148_p1 = sext_ln70_1599_fu_1148_p0;

assign sext_ln70_1600_fu_1188_p1 = tmp_939_fu_1170_p3;

assign sext_ln70_1601_fu_1222_p0 = ap_port_reg_data_28_val;

assign sext_ln70_1601_fu_1222_p1 = sext_ln70_1601_fu_1222_p0;

assign sext_ln70_1602_fu_1340_p0 = ap_port_reg_data_31_val;

assign sext_ln70_1602_fu_1340_p1 = sext_ln70_1602_fu_1340_p0;

assign sext_ln70_fu_718_p1 = data_1_val_read_reg_2248;

assign sext_ln73_1099_fu_322_p1 = $signed(tmp_fu_314_p3);

assign sext_ln73_10_fu_910_p1 = $signed(sub_ln73_1825_fu_904_p2);

assign sext_ln73_1100_fu_340_p1 = $signed(tmp_906_fu_332_p3);

assign sext_ln73_1101_fu_358_p1 = tmp_907_fu_350_p3;

assign sext_ln73_1102_fu_382_p1 = $signed(tmp_908_fu_374_p3);

assign sext_ln73_1103_fu_394_p1 = $signed(tmp_909_fu_386_p3);

assign sext_ln73_1104_fu_412_p1 = $signed(tmp_910_fu_404_p3);

assign sext_ln73_1105_fu_424_p1 = $signed(tmp_911_fu_416_p3);

assign sext_ln73_1106_fu_464_p1 = tmp_912_fu_456_p3;

assign sext_ln73_1107_fu_476_p1 = $signed(tmp_913_fu_468_p3);

assign sext_ln73_1108_fu_508_p1 = $signed(tmp_915_fu_500_p3);

assign sext_ln73_1109_fu_749_p1 = tmp_916_fu_741_p3;

assign sext_ln73_1110_fu_769_p1 = tmp_916_fu_741_p3;

assign sext_ln73_1111_fu_781_p1 = $signed(tmp_917_fu_773_p3);

assign sext_ln73_1112_fu_536_p1 = $signed(tmp_918_fu_528_p3);

assign sext_ln73_1113_fu_548_p1 = $signed(tmp_919_fu_540_p3);

assign sext_ln73_1114_fu_580_p1 = tmp_920_fu_572_p3;

assign sext_ln73_1115_fu_598_p1 = $signed(tmp_921_fu_590_p3);

assign sext_ln73_1116_fu_608_p1 = tmp_920_fu_572_p3;

assign sext_ln73_1117_fu_826_p1 = $signed(tmp_923_fu_818_p3);

assign sext_ln73_1118_fu_838_p1 = $signed(tmp_924_fu_830_p3);

assign sext_ln73_1119_fu_856_p1 = $signed(tmp_925_fu_848_p3);

assign sext_ln73_1120_fu_900_p1 = $signed(tmp_926_fu_892_p3);

assign sext_ln73_1121_fu_926_p1 = $signed(tmp_927_fu_918_p3);

assign sext_ln73_1122_fu_962_p1 = tmp_928_fu_954_p3;

assign sext_ln73_1123_fu_966_p1 = tmp_928_fu_954_p3;

assign sext_ln73_1124_fu_998_p1 = $signed(tmp_929_fu_990_p3);

assign sext_ln73_1125_fu_1064_p1 = $signed(tmp_932_fu_1056_p3);

assign sext_ln73_1126_fu_1960_p1 = $signed(tmp_933_fu_1953_p3);

assign sext_ln73_1127_fu_1088_p1 = $signed(tmp_934_fu_1080_p3);

assign sext_ln73_1128_fu_1122_p1 = $signed(tmp_936_fu_1114_p3);

assign sext_ln73_1129_fu_1134_p1 = $signed(tmp_937_fu_1126_p3);

assign sext_ln73_1130_fu_1160_p1 = $signed(tmp_938_fu_1152_p3);

assign sext_ln73_1131_fu_1178_p1 = tmp_939_fu_1170_p3;

assign sext_ln73_1132_fu_1200_p1 = $signed(tmp_940_fu_1192_p3);

assign sext_ln73_1133_fu_1212_p1 = $signed(shl_ln73_7_fu_1204_p3);

assign sext_ln73_1134_fu_1252_p1 = $signed(tmp_941_fu_1244_p3);

assign sext_ln73_1135_fu_1278_p1 = $signed(tmp_942_fu_1270_p3);

assign sext_ln73_1136_fu_1296_p1 = $signed(tmp_943_fu_1288_p3);

assign sext_ln73_1137_fu_1308_p1 = $signed(tmp_944_fu_1300_p3);

assign sext_ln73_1138_fu_1330_p1 = $signed(tmp_945_fu_1322_p3);

assign sext_ln73_1139_fu_1352_p1 = $signed(tmp_946_fu_1344_p3);

assign sext_ln73_11_fu_936_p1 = $signed(sub_ln73_1826_fu_930_p2);

assign sext_ln73_12_fu_1016_p1 = $signed(shl_ln73_3_fu_1008_p3);

assign sext_ln73_15_fu_2135_p1 = $signed(sub_ln73_1832_reg_2426);

assign sext_ln73_16_fu_1106_p0 = ap_port_reg_data_22_val;

assign sext_ln73_16_fu_1106_p1 = sext_ln73_16_fu_1106_p0;

assign sext_ln73_19_fu_1234_p1 = $signed(shl_ln73_8_fu_1226_p3);

assign sext_ln73_1_fu_310_p0 = data_0_val;

assign sext_ln73_1_fu_310_p1 = sext_ln73_1_fu_310_p0;

assign sext_ln73_20_fu_1262_p1 = $signed(sub_ln73_1838_fu_1256_p2);

assign sext_ln73_21_fu_1266_p0 = ap_port_reg_data_29_val;

assign sext_ln73_21_fu_1266_p1 = sext_ln73_21_fu_1266_p0;

assign sext_ln73_22_fu_1318_p0 = ap_port_reg_data_30_val;

assign sext_ln73_22_fu_1318_p1 = sext_ln73_22_fu_1318_p0;

assign sext_ln73_3_fu_452_p1 = $signed(shl_ln_fu_444_p3);

assign sext_ln73_6_fu_733_p1 = $signed(tmp_914_fu_726_p3);

assign sext_ln73_7_fu_765_p1 = $signed(sub_ln73_1816_fu_759_p2);

assign sext_ln73_8_fu_1947_p1 = $signed(sub_ln73_1817_reg_2324);

assign sext_ln73_9_fu_791_p1 = $signed(add_ln73_1_reg_2273);

assign sext_ln73_fu_306_p0 = data_0_val;

assign sext_ln73_fu_306_p1 = sext_ln73_fu_306_p0;

assign shl_ln73_2_fu_876_p1 = ap_port_reg_data_11_val;

assign shl_ln73_2_fu_876_p3 = {{shl_ln73_2_fu_876_p1}, {1'd0}};

assign shl_ln73_3_fu_1008_p1 = ap_port_reg_data_15_val;

assign shl_ln73_3_fu_1008_p3 = {{shl_ln73_3_fu_1008_p1}, {1'd0}};

assign shl_ln73_4_fu_1024_p1 = ap_port_reg_data_16_val;

assign shl_ln73_4_fu_1024_p3 = {{shl_ln73_4_fu_1024_p1}, {3'd0}};

assign shl_ln73_5_fu_1068_p1 = ap_port_reg_data_20_val;

assign shl_ln73_5_fu_1068_p3 = {{shl_ln73_5_fu_1068_p1}, {1'd0}};

assign shl_ln73_7_fu_1204_p3 = {{ap_port_reg_data_27_val}, {2'd0}};

assign shl_ln73_8_fu_1226_p1 = ap_port_reg_data_28_val;

assign shl_ln73_8_fu_1226_p3 = {{shl_ln73_8_fu_1226_p1}, {1'd0}};

assign shl_ln73_9_fu_1368_p1 = ap_port_reg_data_31_val;

assign shl_ln73_9_fu_1368_p3 = {{shl_ln73_9_fu_1368_p1}, {2'd0}};

assign shl_ln_fu_444_p3 = {{data_3_val}, {2'd0}};

assign sub_ln58_1767_fu_1418_p2 = ($signed(sext_ln58_8967_fu_1415_p1) - $signed(sext_ln58_8966_fu_1412_p1));

assign sub_ln58_1768_fu_1739_p2 = ($signed(sext_ln58_8995_fu_1735_p1) - $signed(sext_ln70_1592_fu_1040_p1));

assign sub_ln58_1769_fu_1748_p2 = ($signed(sext_ln58_8996_fu_1745_p1) - $signed(sext_ln70_1593_fu_1052_p1));

assign sub_ln58_1770_fu_1776_p2 = ($signed(sext_ln58_9000_fu_1772_p1) - $signed(sext_ln58_8999_fu_1768_p1));

assign sub_ln58_1771_fu_1921_p2 = ($signed(sext_ln58_8973_fu_1485_p1) - $signed(sext_ln70_1591_fu_1020_p1));

assign sub_ln58_3094_fu_1431_p2 = ($signed(sext_ln58_9088_fu_1427_p1) - $signed(sext_ln58_9087_fu_1424_p1));

assign sub_ln58_3095_fu_1465_p2 = ($signed(sext_ln58_9089_fu_1462_p1) - $signed(sext_ln73_6_fu_733_p1));

assign sub_ln58_3096_fu_1515_p2 = ($signed(sext_ln58_9090_fu_1511_p1) - $signed(p_shl61_fu_1495_p3));

assign sub_ln58_3097_fu_1531_p2 = ($signed(sub_ln73_1830_fu_1002_p2) - $signed(sext_ln73_1122_fu_962_p1));

assign sub_ln58_3098_fu_1555_p2 = ($signed(sext_ln58_9092_fu_1551_p1) - $signed(sext_ln58_9091_fu_1547_p1));

assign sub_ln58_3099_fu_1565_p2 = ($signed(sext_ln73_10_fu_910_p1) - $signed(sext_ln73_1127_fu_1088_p1));

assign sub_ln58_3100_fu_1581_p2 = ($signed(sext_ln58_8973_fu_1485_p1) - $signed(sext_ln73_1125_fu_1064_p1));

assign sub_ln58_3101_fu_1629_p2 = ($signed(sext_ln73_19_fu_1234_p1) - $signed(sext_ln73_1132_fu_1200_p1));

assign sub_ln58_3102_fu_1719_p2 = ($signed(sext_ln73_1133_fu_1212_p1) - $signed(sext_ln58_9097_fu_1715_p1));

assign sub_ln58_3103_fu_1814_p2 = ($signed(sub_ln73_1824_fu_866_p2) - $signed(sext_ln73_1112_reg_2268));

assign sub_ln58_3104_fu_1839_p2 = ($signed(sext_ln58_9099_fu_1835_p1) - $signed(sext_ln58_9098_fu_1831_p1));

assign sub_ln58_3105_fu_2101_p2 = ($signed(13'd0) - $signed(sext_ln58_9101_fu_2097_p1));

assign sub_ln58_3106_fu_2107_p2 = ($signed(sub_ln58_3105_fu_2101_p2) - $signed(sext_ln58_9100_fu_2087_p1));

assign sub_ln58_3107_fu_1861_p2 = ($signed(sub_ln73_1829_fu_976_p2) - $signed(sext_ln73_1128_fu_1122_p1));

assign sub_ln58_3108_fu_1871_p2 = ($signed(sub_ln73_1843_fu_1376_p2) - $signed(sext_ln73_1136_fu_1296_p1));

assign sub_ln58_3109_fu_1891_p2 = ($signed(sext_ln58_9102_fu_1887_p1) - $signed(sext_ln58_9091_fu_1547_p1));

assign sub_ln58_3110_fu_1905_p2 = ($signed(sext_ln58_9104_fu_1901_p1) - $signed(sext_ln58_9103_fu_1897_p1));

assign sub_ln58_fu_684_p2 = ($signed(sext_ln58_8963_fu_680_p1) - $signed(sext_ln58_8962_fu_676_p1));

assign sub_ln73_1806_fu_326_p2 = ($signed(12'd0) - $signed(sext_ln73_1099_fu_322_p1));

assign sub_ln73_1807_fu_344_p2 = ($signed(sub_ln73_1806_fu_326_p2) - $signed(sext_ln73_1100_fu_340_p1));

assign sub_ln73_1808_fu_368_p2 = ($signed(sext_ln73_fu_306_p1) - $signed(tmp_907_fu_350_p3));

assign sub_ln73_1809_fu_398_p2 = ($signed(sext_ln73_1103_fu_394_p1) - $signed(sext_ln73_1102_fu_382_p1));

assign sub_ln73_1810_fu_721_p2 = ($signed(sext_ln73_1104_reg_2258) - $signed(sext_ln70_fu_718_p1));

assign sub_ln73_1811_fu_428_p2 = ($signed(sext_ln73_1104_fu_412_p1) - $signed(sext_ln73_1105_fu_424_p1));

assign sub_ln73_1812_fu_480_p2 = ($signed(sext_ln73_1106_fu_464_p1) - $signed(sext_ln73_1107_fu_476_p1));

assign sub_ln73_1813_fu_512_p2 = ($signed(11'd0) - $signed(sext_ln73_1108_fu_508_p1));

assign sub_ln73_1814_fu_518_p2 = ($signed(sub_ln73_1813_fu_512_p2) - $signed(sext_ln70_1574_fu_496_p1));

assign sub_ln73_1815_fu_753_p2 = ($signed(13'd0) - $signed(sext_ln73_1109_fu_749_p1));

assign sub_ln73_1816_fu_759_p2 = ($signed(sub_ln73_1815_fu_753_p2) - $signed(sext_ln70_1575_fu_737_p1));

assign sub_ln73_1817_fu_785_p2 = ($signed(sext_ln73_1111_fu_781_p1) - $signed(sext_ln73_1110_fu_769_p1));

assign sub_ln73_1818_fu_552_p2 = ($signed(sext_ln73_1112_fu_536_p1) - $signed(sext_ln73_1113_fu_548_p1));

assign sub_ln73_1819_fu_558_p2 = ($signed(sext_ln70_1576_fu_524_p1) - $signed(sext_ln73_1112_fu_536_p1));

assign sub_ln73_1820_fu_584_p2 = ($signed(sext_ln70_1578_fu_568_p1) - $signed(sext_ln73_1114_fu_580_p1));

assign sub_ln73_1821_fu_602_p2 = ($signed(sext_ln73_1115_fu_598_p1) - $signed(sext_ln73_1114_fu_580_p1));

assign sub_ln73_1822_fu_842_p2 = ($signed(sext_ln73_1117_fu_826_p1) - $signed(sext_ln73_1118_fu_838_p1));

assign sub_ln73_1823_fu_860_p2 = ($signed(12'd0) - $signed(sext_ln73_1119_fu_856_p1));

assign sub_ln73_1824_fu_866_p2 = ($signed(sub_ln73_1823_fu_860_p2) - $signed(sext_ln70_1581_fu_810_p1));

assign sub_ln73_1825_fu_904_p2 = ($signed(10'd0) - $signed(sext_ln73_1120_fu_900_p1));

assign sub_ln73_1826_fu_930_p2 = ($signed(11'd0) - $signed(sext_ln73_1121_fu_926_p1));

assign sub_ln73_1827_fu_940_p2 = ($signed(sext_ln70_1586_fu_914_p1) - $signed(sext_ln73_1121_fu_926_p1));

assign sub_ln73_1828_fu_970_p2 = ($signed(12'd0) - $signed(sext_ln73_1123_fu_966_p1));

assign sub_ln73_1829_fu_976_p2 = ($signed(sub_ln73_1828_fu_970_p2) - $signed(sext_ln70_1587_fu_946_p1));

assign sub_ln73_1830_fu_1002_p2 = ($signed(sext_ln73_1124_fu_998_p1) - $signed(sext_ln70_1590_fu_986_p1));

assign sub_ln73_1831_fu_1964_p2 = ($signed(13'd0) - $signed(sext_ln73_1126_fu_1960_p1));

assign sub_ln73_1832_fu_1970_p2 = ($signed(sub_ln73_1831_fu_1964_p2) - $signed(sext_ln70_1595_fu_1950_p1));

assign sub_ln73_1833_fu_1092_p2 = ($signed(sext_ln73_1127_fu_1088_p1) - $signed(sext_ln70_1596_fu_1076_p1));

assign sub_ln73_1834_fu_1138_p2 = ($signed(sext_ln73_1128_fu_1122_p1) - $signed(sext_ln73_1129_fu_1134_p1));

assign sub_ln73_1835_fu_1164_p2 = ($signed(13'd0) - $signed(sext_ln73_1130_fu_1160_p1));

assign sub_ln73_1836_fu_1182_p2 = ($signed(sub_ln73_1835_fu_1164_p2) - $signed(sext_ln73_1131_fu_1178_p1));

assign sub_ln73_1837_fu_1216_p2 = ($signed(11'd0) - $signed(sext_ln73_1133_fu_1212_p1));

assign sub_ln73_1838_fu_1256_p2 = ($signed(11'd0) - $signed(sext_ln73_1134_fu_1252_p1));

assign sub_ln73_1839_fu_1282_p2 = ($signed(10'd0) - $signed(sext_ln73_1135_fu_1278_p1));

assign sub_ln73_1840_fu_1312_p2 = ($signed(sext_ln73_1136_fu_1296_p1) - $signed(sext_ln73_1137_fu_1308_p1));

assign sub_ln73_1841_fu_1356_p2 = ($signed(12'd0) - $signed(sext_ln73_1139_fu_1352_p1));

assign sub_ln73_1842_fu_1362_p2 = ($signed(sub_ln73_1841_fu_1356_p2) - $signed(sext_ln70_1602_fu_1340_p1));

assign sub_ln73_1843_fu_1376_p2 = ($signed(sext_ln70_1602_fu_1340_p1) - $signed(sext_ln73_1139_fu_1352_p1));

assign sub_ln73_479_fu_490_p2 = ($signed(9'd0) - $signed(sext_ln70_1573_fu_486_p1));

assign sub_ln73_480_fu_622_p2 = ($signed(9'd0) - $signed(sext_ln70_1594_fu_618_p1));

assign sub_ln73_481_fu_1238_p2 = ($signed(9'd0) - $signed(sext_ln70_1601_fu_1222_p1));

assign sub_ln73_fu_438_p2 = ($signed(9'd0) - $signed(sext_ln70_1572_fu_434_p1));

assign tmp_906_fu_332_p1 = data_0_val;

assign tmp_906_fu_332_p3 = {{tmp_906_fu_332_p1}, {1'd0}};

assign tmp_907_fu_350_p1 = data_0_val;

assign tmp_907_fu_350_p3 = {{tmp_907_fu_350_p1}, {2'd0}};

assign tmp_908_fu_374_p1 = data_1_val;

assign tmp_908_fu_374_p3 = {{tmp_908_fu_374_p1}, {4'd0}};

assign tmp_909_fu_386_p1 = data_1_val;

assign tmp_909_fu_386_p3 = {{tmp_909_fu_386_p1}, {2'd0}};

assign tmp_910_fu_404_p1 = data_1_val;

assign tmp_910_fu_404_p3 = {{tmp_910_fu_404_p1}, {3'd0}};

assign tmp_911_fu_416_p1 = data_1_val;

assign tmp_911_fu_416_p3 = {{tmp_911_fu_416_p1}, {1'd0}};

assign tmp_912_fu_456_p3 = {{data_3_val}, {3'd0}};

assign tmp_913_fu_468_p3 = {{data_3_val}, {1'd0}};

assign tmp_914_fu_726_p3 = {{data_5_val_read_reg_2238}, {3'd0}};

assign tmp_915_fu_500_p1 = data_5_val;

assign tmp_915_fu_500_p3 = {{tmp_915_fu_500_p1}, {2'd0}};

assign tmp_916_fu_741_p1 = ap_port_reg_data_6_val;

assign tmp_916_fu_741_p3 = {{tmp_916_fu_741_p1}, {3'd0}};

assign tmp_917_fu_773_p1 = ap_port_reg_data_6_val;

assign tmp_917_fu_773_p3 = {{tmp_917_fu_773_p1}, {1'd0}};

assign tmp_918_fu_528_p1 = data_7_val;

assign tmp_918_fu_528_p3 = {{tmp_918_fu_528_p1}, {3'd0}};

assign tmp_919_fu_540_p1 = data_7_val;

assign tmp_919_fu_540_p3 = {{tmp_919_fu_540_p1}, {1'd0}};

assign tmp_920_fu_572_p1 = data_8_val;

assign tmp_920_fu_572_p3 = {{tmp_920_fu_572_p1}, {3'd0}};

assign tmp_921_fu_590_p1 = data_8_val;

assign tmp_921_fu_590_p3 = {{tmp_921_fu_590_p1}, {1'd0}};

assign tmp_922_fu_802_p1 = ap_port_reg_data_9_val;

assign tmp_922_fu_802_p3 = {{tmp_922_fu_802_p1}, {1'd0}};

assign tmp_923_fu_818_p1 = ap_port_reg_data_10_val;

assign tmp_923_fu_818_p3 = {{tmp_923_fu_818_p1}, {3'd0}};

assign tmp_924_fu_830_p1 = ap_port_reg_data_10_val;

assign tmp_924_fu_830_p3 = {{tmp_924_fu_830_p1}, {1'd0}};

assign tmp_925_fu_848_p1 = ap_port_reg_data_10_val;

assign tmp_925_fu_848_p3 = {{tmp_925_fu_848_p1}, {2'd0}};

assign tmp_926_fu_892_p1 = ap_port_reg_data_12_val;

assign tmp_926_fu_892_p3 = {{tmp_926_fu_892_p1}, {1'd0}};

assign tmp_927_fu_918_p1 = ap_port_reg_data_13_val;

assign tmp_927_fu_918_p3 = {{tmp_927_fu_918_p1}, {2'd0}};

assign tmp_928_fu_954_p1 = ap_port_reg_data_14_val;

assign tmp_928_fu_954_p3 = {{tmp_928_fu_954_p1}, {2'd0}};

assign tmp_929_fu_990_p1 = ap_port_reg_data_15_val;

assign tmp_929_fu_990_p3 = {{tmp_929_fu_990_p1}, {2'd0}};

assign tmp_930_fu_1032_p1 = ap_port_reg_data_16_val;

assign tmp_930_fu_1032_p3 = {{tmp_930_fu_1032_p1}, {1'd0}};

assign tmp_931_fu_1044_p1 = ap_port_reg_data_17_val;

assign tmp_931_fu_1044_p3 = {{tmp_931_fu_1044_p1}, {2'd0}};

assign tmp_932_fu_1056_p1 = ap_port_reg_data_18_val;

assign tmp_932_fu_1056_p3 = {{tmp_932_fu_1056_p1}, {1'd0}};

assign tmp_933_fu_1953_p3 = {{data_20_val_read_reg_2318}, {3'd0}};

assign tmp_934_fu_1080_p1 = ap_port_reg_data_21_val;

assign tmp_934_fu_1080_p3 = {{tmp_934_fu_1080_p1}, {2'd0}};

assign tmp_935_fu_1098_p1 = ap_port_reg_data_21_val;

assign tmp_935_fu_1098_p3 = {{tmp_935_fu_1098_p1}, {1'd0}};

assign tmp_936_fu_1114_p1 = ap_port_reg_data_23_val;

assign tmp_936_fu_1114_p3 = {{tmp_936_fu_1114_p1}, {3'd0}};

assign tmp_937_fu_1126_p1 = ap_port_reg_data_23_val;

assign tmp_937_fu_1126_p3 = {{tmp_937_fu_1126_p1}, {1'd0}};

assign tmp_938_fu_1152_p1 = ap_port_reg_data_26_val;

assign tmp_938_fu_1152_p3 = {{tmp_938_fu_1152_p1}, {3'd0}};

assign tmp_939_fu_1170_p1 = ap_port_reg_data_26_val;

assign tmp_939_fu_1170_p3 = {{tmp_939_fu_1170_p1}, {1'd0}};

assign tmp_940_fu_1192_p3 = {{ap_port_reg_data_27_val}, {1'd0}};

assign tmp_941_fu_1244_p1 = ap_port_reg_data_29_val;

assign tmp_941_fu_1244_p3 = {{tmp_941_fu_1244_p1}, {2'd0}};

assign tmp_942_fu_1270_p1 = ap_port_reg_data_29_val;

assign tmp_942_fu_1270_p3 = {{tmp_942_fu_1270_p1}, {1'd0}};

assign tmp_943_fu_1288_p1 = ap_port_reg_data_30_val;

assign tmp_943_fu_1288_p3 = {{tmp_943_fu_1288_p1}, {3'd0}};

assign tmp_944_fu_1300_p1 = ap_port_reg_data_30_val;

assign tmp_944_fu_1300_p3 = {{tmp_944_fu_1300_p1}, {1'd0}};

assign tmp_945_fu_1322_p1 = ap_port_reg_data_30_val;

assign tmp_945_fu_1322_p3 = {{tmp_945_fu_1322_p1}, {2'd0}};

assign tmp_946_fu_1344_p1 = ap_port_reg_data_31_val;

assign tmp_946_fu_1344_p3 = {{tmp_946_fu_1344_p1}, {3'd0}};

assign tmp_947_fu_1503_p3 = {{add_ln58_7679_fu_1489_p2}, {2'd0}};

assign tmp_948_fu_1655_p3 = {{add_ln58_7698_fu_1645_p2}, {2'd0}};

assign tmp_949_fu_2049_p3 = {{add_ln58_7705_reg_2374}, {2'd0}};

assign tmp_950_fu_2090_p3 = {{add_ln58_7722_reg_2405}, {3'd0}};

assign tmp_fu_314_p1 = data_0_val;

assign tmp_fu_314_p3 = {{tmp_fu_314_p1}, {3'd0}};

always @ (posedge ap_clk) begin
    sub_ln73_1809_reg_2253[1:0] <= 2'b00;
    sext_ln73_1104_reg_2258[2:0] <= 3'b000;
    tmp_912_reg_2263[2:0] <= 3'b000;
    sext_ln73_1112_reg_2268[2:0] <= 3'b000;
    add_ln58_reg_2283[0] <= 1'b0;
    sub_ln73_1817_reg_2324[0] <= 1'b0;
    sub_ln73_1836_reg_2329[0] <= 1'b0;
    sub_ln58_3096_reg_2344[1:0] <= 2'b00;
    add_ln58_7693_reg_2364[0] <= 1'b0;
    add_ln58_7726_reg_2416[0] <= 1'b0;
end

endmodule //myproject_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_22_12_5_3_0_config13_s
