// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_myproject,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12t-cpg238-1I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.638750,HLS_SYN_LAT=3287,HLS_SYN_TPT=3276,HLS_SYN_MEM=69,HLS_SYN_DSP=0,HLS_SYN_FF=78441,HLS_SYN_LUT=268646,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject (
        x_TDATA,
        layer13_out_TDATA,
        ap_clk,
        ap_rst_n,
        x_TVALID,
        x_TREADY,
        ap_start,
        layer13_out_TVALID,
        layer13_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [487:0] x_TDATA;
output  [95:0] layer13_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   x_TVALID;
output   x_TREADY;
input   ap_start;
output   layer13_out_TVALID;
input   layer13_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_start;
wire    transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_done;
wire    transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_continue;
wire    transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_idle;
wire    transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_ready;
wire    transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_start_out;
wire    transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_start_write;
wire    transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_x_TREADY;
wire   [7:0] transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_din;
wire    transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_write;
wire   [31:0] transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_num_data_valid;
wire   [31:0] transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_fifo_cap;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_start;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_done;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_continue;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_idle;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_ready;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_start_out;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_start_write;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer14_out_read;
wire   [7:0] zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_din;
wire    zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_write;
wire   [31:0] zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_num_data_valid;
wire   [31:0] zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_fifo_cap;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_layer16_out_read;
wire   [167:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_layer2_out_din;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_layer2_out_write;
wire    relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_start;
wire    relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_done;
wire    relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_continue;
wire    relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_idle;
wire    relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_ready;
wire    relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer2_out_read;
wire   [63:0] relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_din;
wire    relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_write;
wire   [31:0] relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_num_data_valid;
wire   [31:0] relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_fifo_cap;
wire    relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_start_out;
wire    relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_start_write;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_start;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_done;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_continue;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_idle;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_ready;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_start_out;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_start_write;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_layer4_out_read;
wire   [63:0] pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_layer5_out_din;
wire    pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_layer5_out_write;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_start;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_done;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_continue;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_idle;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_ready;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_start_out;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_start_write;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer5_out_read;
wire   [63:0] zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_din;
wire    zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_write;
wire   [31:0] zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_num_data_valid;
wire   [31:0] zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_fifo_cap;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_layer17_out_read;
wire   [383:0] conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_layer6_out_din;
wire    conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_layer6_out_write;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_start;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_done;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_continue;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_idle;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_ready;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer6_out_read;
wire   [127:0] relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_din;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_write;
wire   [31:0] relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_num_data_valid;
wire   [31:0] relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_fifo_cap;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_start_out;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_start_write;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_start;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_done;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_continue;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_idle;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_ready;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_start_out;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_start_write;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_layer8_out_read;
wire   [127:0] pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_layer9_out_din;
wire    pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_layer9_out_write;
wire    transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_start;
wire    transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_done;
wire    transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_continue;
wire    transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_idle;
wire    transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_ready;
wire    transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_start_out;
wire    transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_start_write;
wire    transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer9_out_read;
wire   [119:0] transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_din;
wire    transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_write;
wire   [31:0] transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_num_data_valid;
wire   [31:0] transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_fifo_cap;
wire    dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_start;
wire    dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_done;
wire    dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_continue;
wire    dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_idle;
wire    dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_ready;
wire    dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_start_out;
wire    dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_start_write;
wire    dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_layer15_out_read;
wire   [831:0] dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_layer11_out_din;
wire    dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_layer11_out_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_start;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_done;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_continue;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_idle;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_ready;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_start_out;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_start_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_layer11_out_read;
wire   [255:0] relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_layer12_out_din;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_layer12_out_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_start;
wire    dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_done;
wire    dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_continue;
wire    dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_idle;
wire    dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_ready;
wire    dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_layer12_out_read;
wire   [95:0] dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_layer13_out_TDATA;
wire    dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_layer13_out_TVALID;
wire    layer14_out_full_n;
wire   [7:0] layer14_out_dout;
wire    layer14_out_empty_n;
wire   [10:0] layer14_out_num_data_valid;
wire   [10:0] layer14_out_fifo_cap;
wire    layer16_out_full_n;
wire   [7:0] layer16_out_dout;
wire    layer16_out_empty_n;
wire   [10:0] layer16_out_num_data_valid;
wire   [10:0] layer16_out_fifo_cap;
wire    layer2_out_full_n;
wire   [167:0] layer2_out_dout;
wire    layer2_out_empty_n;
wire   [10:0] layer2_out_num_data_valid;
wire   [10:0] layer2_out_fifo_cap;
wire    layer4_out_full_n;
wire   [63:0] layer4_out_dout;
wire    layer4_out_empty_n;
wire   [10:0] layer4_out_num_data_valid;
wire   [10:0] layer4_out_fifo_cap;
wire    layer5_out_full_n;
wire   [63:0] layer5_out_dout;
wire    layer5_out_empty_n;
wire   [8:0] layer5_out_num_data_valid;
wire   [8:0] layer5_out_fifo_cap;
wire    layer17_out_full_n;
wire   [63:0] layer17_out_dout;
wire    layer17_out_empty_n;
wire   [8:0] layer17_out_num_data_valid;
wire   [8:0] layer17_out_fifo_cap;
wire    layer6_out_full_n;
wire   [383:0] layer6_out_dout;
wire    layer6_out_empty_n;
wire   [8:0] layer6_out_num_data_valid;
wire   [8:0] layer6_out_fifo_cap;
wire    layer8_out_full_n;
wire   [127:0] layer8_out_dout;
wire    layer8_out_empty_n;
wire   [8:0] layer8_out_num_data_valid;
wire   [8:0] layer8_out_fifo_cap;
wire    layer9_out_full_n;
wire   [127:0] layer9_out_dout;
wire    layer9_out_empty_n;
wire   [5:0] layer9_out_num_data_valid;
wire   [5:0] layer9_out_fifo_cap;
wire    layer15_out_full_n;
wire   [119:0] layer15_out_dout;
wire    layer15_out_empty_n;
wire   [5:0] layer15_out_num_data_valid;
wire   [5:0] layer15_out_fifo_cap;
wire    layer11_out_full_n;
wire   [831:0] layer11_out_dout;
wire    layer11_out_empty_n;
wire   [1:0] layer11_out_num_data_valid;
wire   [1:0] layer11_out_fifo_cap;
wire    layer12_out_full_n;
wire   [255:0] layer12_out_dout;
wire    layer12_out_empty_n;
wire   [1:0] layer12_out_num_data_valid;
wire   [1:0] layer12_out_fifo_cap;
wire   [0:0] start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_din;
wire    start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_dout;
wire    start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_din;
wire    start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_dout;
wire    start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_din;
wire    start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_dout;
wire    start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_din;
wire    start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_dout;
wire    start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_din;
wire    start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_dout;
wire    start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_din;
wire    start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_dout;
wire    start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_din;
wire    start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_dout;
wire    start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_din;
wire    start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_dout;
wire    start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_empty_n;
wire   [0:0] start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_din;
wire    start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_full_n;
wire   [0:0] start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_dout;
wire    start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_din;
wire    start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_dout;
wire    start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_din;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_dout;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_din;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_dout;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_empty_n;

myproject_transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_s transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_full_n),
    .ap_done(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_done),
    .ap_continue(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_continue),
    .ap_idle(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_idle),
    .ap_ready(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_ready),
    .start_out(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_start_out),
    .start_write(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_start_write),
    .x_TDATA(x_TDATA),
    .x_TVALID(x_TVALID),
    .x_TREADY(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_x_TREADY),
    .layer14_out_din(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_din),
    .layer14_out_full_n(layer14_out_full_n),
    .layer14_out_write(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_write),
    .layer14_out_num_data_valid(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_num_data_valid),
    .layer14_out_fifo_cap(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_fifo_cap)
);

myproject_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_s zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_full_n),
    .ap_done(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_ready),
    .start_out(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_start_out),
    .start_write(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_start_write),
    .layer14_out_dout(layer14_out_dout),
    .layer14_out_empty_n(layer14_out_empty_n),
    .layer14_out_read(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer14_out_read),
    .layer14_out_num_data_valid(layer14_out_num_data_valid),
    .layer14_out_fifo_cap(layer14_out_fifo_cap),
    .layer16_out_din(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_din),
    .layer16_out_full_n(layer16_out_full_n),
    .layer16_out_write(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_write),
    .layer16_out_num_data_valid(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_num_data_valid),
    .layer16_out_fifo_cap(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_fifo_cap)
);

myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_s conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_start_write),
    .layer16_out_dout(layer16_out_dout),
    .layer16_out_empty_n(layer16_out_empty_n),
    .layer16_out_read(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_layer16_out_read),
    .layer16_out_num_data_valid(layer16_out_num_data_valid),
    .layer16_out_fifo_cap(layer16_out_fifo_cap),
    .layer2_out_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_layer2_out_din),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_layer2_out_write),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap)
);

myproject_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_s relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_full_n),
    .ap_done(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_ready),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer2_out_read),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer4_out_din(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_din),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_write),
    .layer4_out_num_data_valid(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_num_data_valid),
    .layer4_out_fifo_cap(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_fifo_cap),
    .start_out(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_start_out),
    .start_write(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_start_write)
);

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_s pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_full_n),
    .ap_done(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_done),
    .ap_continue(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_ready),
    .start_out(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_start_out),
    .start_write(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_start_write),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_layer4_out_read),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer5_out_din(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_layer5_out_din),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_layer5_out_write),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap)
);

myproject_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_s zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_full_n),
    .ap_done(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_ready),
    .start_out(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_start_out),
    .start_write(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_start_write),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer5_out_read),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer17_out_din(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_din),
    .layer17_out_full_n(layer17_out_full_n),
    .layer17_out_write(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_write),
    .layer17_out_num_data_valid(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_num_data_valid),
    .layer17_out_fifo_cap(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_fifo_cap)
);

myproject_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_s conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_start_write),
    .layer17_out_dout(layer17_out_dout),
    .layer17_out_empty_n(layer17_out_empty_n),
    .layer17_out_read(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_layer17_out_read),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .layer6_out_din(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_layer6_out_din),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_layer6_out_write),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap)
);

myproject_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_s relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_full_n),
    .ap_done(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_ready),
    .layer6_out_dout(layer6_out_dout),
    .layer6_out_empty_n(layer6_out_empty_n),
    .layer6_out_read(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer6_out_read),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer8_out_din(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_din),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_write),
    .layer8_out_num_data_valid(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_num_data_valid),
    .layer8_out_fifo_cap(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_fifo_cap),
    .start_out(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_start_out),
    .start_write(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_start_write)
);

myproject_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_s pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_start),
    .start_full_n(start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_full_n),
    .ap_done(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_done),
    .ap_continue(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_ready),
    .start_out(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_start_out),
    .start_write(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_start_write),
    .layer8_out_dout(layer8_out_dout),
    .layer8_out_empty_n(layer8_out_empty_n),
    .layer8_out_read(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_layer8_out_read),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer9_out_din(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_layer9_out_din),
    .layer9_out_full_n(layer9_out_full_n),
    .layer9_out_write(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_layer9_out_write),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap)
);

myproject_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_s transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_full_n),
    .ap_done(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_done),
    .ap_continue(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_continue),
    .ap_idle(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_idle),
    .ap_ready(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_ready),
    .start_out(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_start_out),
    .start_write(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_start_write),
    .layer9_out_dout(layer9_out_dout),
    .layer9_out_empty_n(layer9_out_empty_n),
    .layer9_out_read(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer9_out_read),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer15_out_din(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_din),
    .layer15_out_full_n(layer15_out_full_n),
    .layer15_out_write(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_write),
    .layer15_out_num_data_valid(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_num_data_valid),
    .layer15_out_fifo_cap(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_fifo_cap)
);

myproject_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_s dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_full_n),
    .ap_done(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_ready),
    .start_out(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_start_out),
    .start_write(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_start_write),
    .layer15_out_dout(layer15_out_dout),
    .layer15_out_empty_n(layer15_out_empty_n),
    .layer15_out_read(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_layer15_out_read),
    .layer15_out_num_data_valid(layer15_out_num_data_valid),
    .layer15_out_fifo_cap(layer15_out_fifo_cap),
    .layer11_out_din(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_layer11_out_din),
    .layer11_out_full_n(layer11_out_full_n),
    .layer11_out_write(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_layer11_out_write),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap)
);

myproject_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_s relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_full_n),
    .ap_done(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_ready),
    .start_out(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_start_out),
    .start_write(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_start_write),
    .layer11_out_dout(layer11_out_dout),
    .layer11_out_empty_n(layer11_out_empty_n),
    .layer11_out_read(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_layer11_out_read),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer12_out_din(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_layer12_out_din),
    .layer12_out_full_n(layer12_out_full_n),
    .layer12_out_write(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_layer12_out_write),
    .layer12_out_num_data_valid(layer12_out_num_data_valid),
    .layer12_out_fifo_cap(layer12_out_fifo_cap)
);

myproject_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_s dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_start),
    .ap_done(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_ready),
    .layer12_out_dout(layer12_out_dout),
    .layer12_out_empty_n(layer12_out_empty_n),
    .layer12_out_read(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_layer12_out_read),
    .layer12_out_num_data_valid(layer12_out_num_data_valid),
    .layer12_out_fifo_cap(layer12_out_fifo_cap),
    .layer13_out_TDATA(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_layer13_out_TDATA),
    .layer13_out_TVALID(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_layer13_out_TVALID),
    .layer13_out_TREADY(layer13_out_TREADY)
);

myproject_fifo_w8_d671_A layer14_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_din),
    .if_full_n(layer14_out_full_n),
    .if_write(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_write),
    .if_dout(layer14_out_dout),
    .if_empty_n(layer14_out_empty_n),
    .if_read(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer14_out_read),
    .if_num_data_valid(layer14_out_num_data_valid),
    .if_fifo_cap(layer14_out_fifo_cap)
);

myproject_fifo_w8_d819_A layer16_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_din),
    .if_full_n(layer16_out_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_write),
    .if_dout(layer16_out_dout),
    .if_empty_n(layer16_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_layer16_out_read),
    .if_num_data_valid(layer16_out_num_data_valid),
    .if_fifo_cap(layer16_out_fifo_cap)
);

myproject_fifo_w168_d671_A layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_empty_n(layer2_out_empty_n),
    .if_read(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer2_out_read),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap)
);

myproject_fifo_w64_d671_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_empty_n(layer4_out_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_layer4_out_read),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap)
);

myproject_fifo_w64_d150_A layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_empty_n(layer5_out_empty_n),
    .if_read(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer5_out_read),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap)
);

myproject_fifo_w64_d224_A layer17_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_din),
    .if_full_n(layer17_out_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_write),
    .if_dout(layer17_out_dout),
    .if_empty_n(layer17_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_layer17_out_read),
    .if_num_data_valid(layer17_out_num_data_valid),
    .if_fifo_cap(layer17_out_fifo_cap)
);

myproject_fifo_w384_d150_A layer6_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_layer6_out_din),
    .if_full_n(layer6_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_layer6_out_write),
    .if_dout(layer6_out_dout),
    .if_empty_n(layer6_out_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer6_out_read),
    .if_num_data_valid(layer6_out_num_data_valid),
    .if_fifo_cap(layer6_out_fifo_cap)
);

myproject_fifo_w128_d150_A layer8_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_din),
    .if_full_n(layer8_out_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_write),
    .if_dout(layer8_out_dout),
    .if_empty_n(layer8_out_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_layer8_out_read),
    .if_num_data_valid(layer8_out_num_data_valid),
    .if_fifo_cap(layer8_out_fifo_cap)
);

myproject_fifo_w128_d30_A layer9_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_layer9_out_din),
    .if_full_n(layer9_out_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_layer9_out_write),
    .if_dout(layer9_out_dout),
    .if_empty_n(layer9_out_empty_n),
    .if_read(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer9_out_read),
    .if_num_data_valid(layer9_out_num_data_valid),
    .if_fifo_cap(layer9_out_fifo_cap)
);

myproject_fifo_w120_d32_A layer15_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_din),
    .if_full_n(layer15_out_full_n),
    .if_write(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_write),
    .if_dout(layer15_out_dout),
    .if_empty_n(layer15_out_empty_n),
    .if_read(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_layer15_out_read),
    .if_num_data_valid(layer15_out_num_data_valid),
    .if_fifo_cap(layer15_out_fifo_cap)
);

myproject_fifo_w832_d1_S layer11_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_layer11_out_din),
    .if_full_n(layer11_out_full_n),
    .if_write(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_layer11_out_write),
    .if_dout(layer11_out_dout),
    .if_empty_n(layer11_out_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_layer11_out_read),
    .if_num_data_valid(layer11_out_num_data_valid),
    .if_fifo_cap(layer11_out_fifo_cap)
);

myproject_fifo_w256_d1_S layer12_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_layer12_out_din),
    .if_full_n(layer12_out_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_layer12_out_write),
    .if_dout(layer12_out_dout),
    .if_empty_n(layer12_out_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_layer12_out_read),
    .if_num_data_valid(layer12_out_num_data_valid),
    .if_fifo_cap(layer12_out_fifo_cap)
);

myproject_start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16tde start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16tde_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_din),
    .if_full_n(start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_full_n),
    .if_write(transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_empty_n),
    .if_read(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_ready)
);

myproject_start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0 start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0 start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_empty_n),
    .if_read(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0 start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_full_n),
    .if_write(relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_ready)
);

myproject_start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17udo start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17udo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_din),
    .if_full_n(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_empty_n),
    .if_read(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_ready)
);

myproject_start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6vdy start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6vdy_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_full_n),
    .if_write(zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0 start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_configwdI start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_configwdI_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_ready)
);

myproject_start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0 start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_din),
    .if_full_n(start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_start_write),
    .if_dout(start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_dout),
    .if_empty_n(start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_empty_n),
    .if_read(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_ready)
);

myproject_start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0 start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_full_n),
    .if_write(transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_empty_n),
    .if_read(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0 start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_full_n),
    .if_write(dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_ready)
);

myproject_start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0 start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_ready)
);

assign ap_done = dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_done;

assign ap_idle = (zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_idle & zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_idle & transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_idle & transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_idle & relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_idle & relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_idle & relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_idle & pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_idle & pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_idle & dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_idle & dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_idle & conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_idle & conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_idle);

assign ap_ready = transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_ap_start = start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_empty_n;

assign conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_ap_start = start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_empty_n;

assign dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_ap_start = start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_empty_n;

assign dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_ap_start = start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_empty_n;

assign layer13_out_TDATA = dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_layer13_out_TDATA;

assign layer13_out_TVALID = dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_layer13_out_TVALID;

assign pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_ap_start = start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_empty_n;

assign pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_ap_start = start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_empty_n;

assign relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_ap_start = start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_empty_n;

assign relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_fifo_cap = layer8_out_fifo_cap;

assign relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_layer8_out_num_data_valid = layer8_out_num_data_valid;

assign relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_ap_start = start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_empty_n;

assign relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_ap_start = start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_empty_n;

assign relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_fifo_cap = layer4_out_fifo_cap;

assign relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_layer4_out_num_data_valid = layer4_out_num_data_valid;

assign start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_21_11_5_3_0_8u_config2_U0_din = 1'b1;

assign start_for_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_24_14_5_3_0_16u_config6_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_15u_array_ap_fixed_26_16_5_3_0_32u_config11_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_32u_array_ap_fixed_22_12_5_3_0_3u_config13_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_relu_config4_U0_din = 1'b1;

assign start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_din = 1'b1;

assign start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_din = 1'b1;

assign start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_din = 1'b1;

assign transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_continue = 1'b1;

assign transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_ap_start = start_for_transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_empty_n;

assign transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_fifo_cap = layer15_out_fifo_cap;

assign transpose_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_15u_config15_U0_layer15_out_num_data_valid = layer15_out_num_data_valid;

assign transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_continue = 1'b1;

assign transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_ap_start = ap_start;

assign transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_fifo_cap = layer14_out_fifo_cap;

assign transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_layer14_out_num_data_valid = layer14_out_num_data_valid;

assign x_TREADY = transpose_array_ap_fixed_61u_array_ap_fixed_8_3_5_3_0_1u_config14_U0_x_TREADY;

assign zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_ap_start = start_for_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_empty_n;

assign zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_fifo_cap = layer16_out_fifo_cap;

assign zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_5_3_0_1u_config16_U0_layer16_out_num_data_valid = layer16_out_num_data_valid;

assign zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_ap_start = start_for_zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_empty_n;

assign zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_fifo_cap = layer17_out_fifo_cap;

assign zeropad2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config17_U0_layer17_out_num_data_valid = layer17_out_num_data_valid;

endmodule //myproject
