// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer8_out_dout,
        layer8_out_empty_n,
        layer8_out_read,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer9_out_din,
        layer9_out_full_n,
        layer9_out_write,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] layer8_out_dout;
input   layer8_out_empty_n;
output   layer8_out_read;
input  [8:0] layer8_out_num_data_valid;
input  [8:0] layer8_out_fifo_cap;
output  [127:0] layer9_out_din;
input   layer9_out_full_n;
output   layer9_out_write;
input  [5:0] layer9_out_num_data_valid;
input  [5:0] layer9_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer8_out_read;
reg layer9_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_22;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_16;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_15;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_14;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_13;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_12;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_11;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_10;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_9;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_8;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_21;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_20;
reg   [7:0] void_pooling2d_buffer_cl_stream_stream_array_ap_fixed_16u_0_line_buffer;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_19;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_18;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_17;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_45;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_44;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_43;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_42;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_41;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_40;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_39;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_38;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_37;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_36;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_35;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_34;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_33;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_32;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_31;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_30;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_29;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_28;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_27;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_26;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_25;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_24;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_23;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_22;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_21;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_20;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_19;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_18;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_17;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_16;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_15;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_14;
reg   [31:0] sX_1;
reg   [31:0] pX_1;
reg   [31:0] sY_1;
reg   [31:0] pY_1;
reg    layer8_out_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    layer9_out_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln191_reg_3456;
reg   [0:0] and_ln191_2_reg_3460;
reg   [0:0] icmp_ln24386_reg_427;
reg   [7:0] p_0_0_0_0_09384_reg_438;
reg    ap_block_state1;
wire   [7:0] select_ln241_fu_988_p3;
reg   [7:0] select_ln241_reg_3284;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op478_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln241_7_fu_996_p3;
reg   [7:0] select_ln241_7_reg_3289;
wire   [7:0] select_ln241_8_fu_1004_p3;
reg   [7:0] select_ln241_8_reg_3294;
wire   [7:0] select_ln241_9_fu_1012_p3;
reg   [7:0] select_ln241_9_reg_3299;
wire   [7:0] select_ln241_10_fu_1020_p3;
reg   [7:0] select_ln241_10_reg_3304;
wire   [7:0] select_ln241_11_fu_1028_p3;
reg   [7:0] select_ln241_11_reg_3309;
wire   [7:0] select_ln241_12_fu_1036_p3;
reg   [7:0] select_ln241_12_reg_3314;
wire   [7:0] select_ln241_13_fu_1044_p3;
reg   [7:0] select_ln241_13_reg_3319;
wire   [7:0] select_ln241_14_fu_1052_p3;
reg   [7:0] select_ln241_14_reg_3324;
wire   [7:0] select_ln241_15_fu_1060_p3;
reg   [7:0] select_ln241_15_reg_3329;
wire   [7:0] select_ln241_16_fu_1068_p3;
reg   [7:0] select_ln241_16_reg_3334;
wire   [7:0] select_ln241_17_fu_1076_p3;
reg   [7:0] select_ln241_17_reg_3339;
wire   [7:0] select_ln241_18_fu_1084_p3;
reg   [7:0] select_ln241_18_reg_3344;
wire   [7:0] select_ln241_19_fu_1092_p3;
reg   [7:0] select_ln241_19_reg_3349;
wire   [7:0] select_ln241_20_fu_1100_p3;
reg   [7:0] select_ln241_20_reg_3354;
wire   [7:0] trunc_ln247_fu_1108_p1;
reg   [7:0] trunc_ln247_reg_3359;
wire   [7:0] trunc_ln247_1_fu_1112_p4;
reg   [7:0] trunc_ln247_1_reg_3366;
wire   [7:0] trunc_ln247_2_fu_1122_p4;
reg   [7:0] trunc_ln247_2_reg_3372;
wire   [7:0] trunc_ln247_3_fu_1132_p4;
reg   [7:0] trunc_ln247_3_reg_3378;
wire   [7:0] trunc_ln247_4_fu_1142_p4;
reg   [7:0] trunc_ln247_4_reg_3384;
wire   [7:0] trunc_ln247_5_fu_1152_p4;
reg   [7:0] trunc_ln247_5_reg_3390;
wire   [7:0] trunc_ln247_6_fu_1162_p4;
reg   [7:0] trunc_ln247_6_reg_3396;
wire   [7:0] trunc_ln247_7_fu_1172_p4;
reg   [7:0] trunc_ln247_7_reg_3402;
wire   [7:0] trunc_ln247_8_fu_1182_p4;
reg   [7:0] trunc_ln247_8_reg_3408;
wire   [7:0] trunc_ln247_9_fu_1192_p4;
reg   [7:0] trunc_ln247_9_reg_3414;
wire   [7:0] trunc_ln247_s_fu_1202_p4;
reg   [7:0] trunc_ln247_s_reg_3420;
wire   [7:0] trunc_ln247_10_fu_1212_p4;
reg   [7:0] trunc_ln247_10_reg_3426;
wire   [7:0] trunc_ln247_11_fu_1222_p4;
reg   [7:0] trunc_ln247_11_reg_3432;
wire   [7:0] trunc_ln247_12_fu_1232_p4;
reg   [7:0] trunc_ln247_12_reg_3438;
wire   [7:0] trunc_ln247_13_fu_1242_p4;
reg   [7:0] trunc_ln247_13_reg_3444;
wire   [7:0] trunc_ln247_14_fu_1252_p4;
reg   [7:0] trunc_ln247_14_reg_3450;
wire   [0:0] icmp_ln191_fu_1266_p2;
wire   [0:0] and_ln191_2_fu_1314_p2;
wire   [7:0] select_ln0_fu_1383_p3;
reg   [7:0] select_ln0_reg_3464;
wire   [7:0] select_ln0_16_fu_1411_p3;
reg   [7:0] select_ln0_16_reg_3470;
wire   [7:0] select_ln0_17_fu_1431_p3;
reg   [7:0] select_ln0_17_reg_3476;
wire   [7:0] select_ln0_18_fu_1451_p3;
reg   [7:0] select_ln0_18_reg_3482;
wire   [7:0] select_ln0_19_fu_1471_p3;
reg   [7:0] select_ln0_19_reg_3488;
wire   [7:0] select_ln0_20_fu_1491_p3;
reg   [7:0] select_ln0_20_reg_3494;
wire   [7:0] select_ln0_21_fu_1511_p3;
reg   [7:0] select_ln0_21_reg_3500;
wire   [7:0] select_ln0_22_fu_1531_p3;
reg   [7:0] select_ln0_22_reg_3506;
wire   [7:0] select_ln0_23_fu_1551_p3;
reg   [7:0] select_ln0_23_reg_3512;
wire   [7:0] select_ln0_24_fu_1571_p3;
reg   [7:0] select_ln0_24_reg_3518;
wire   [7:0] select_ln0_25_fu_1591_p3;
reg   [7:0] select_ln0_25_reg_3524;
wire   [7:0] select_ln0_26_fu_1611_p3;
reg   [7:0] select_ln0_26_reg_3530;
wire   [7:0] select_ln0_27_fu_1631_p3;
reg   [7:0] select_ln0_27_reg_3536;
wire   [7:0] select_ln0_28_fu_1651_p3;
reg   [7:0] select_ln0_28_reg_3542;
wire   [7:0] select_ln0_29_fu_1671_p3;
reg   [7:0] select_ln0_29_reg_3548;
wire   [7:0] select_ln0_30_fu_1691_p3;
reg   [7:0] select_ln0_30_reg_3554;
wire   [7:0] select_ln0_31_fu_1711_p3;
reg   [7:0] select_ln0_31_reg_3560;
wire   [7:0] select_ln0_32_fu_1731_p3;
reg   [7:0] select_ln0_32_reg_3566;
wire   [7:0] select_ln0_33_fu_1751_p3;
reg   [7:0] select_ln0_33_reg_3572;
wire   [7:0] select_ln0_34_fu_1771_p3;
reg   [7:0] select_ln0_34_reg_3578;
wire   [7:0] select_ln0_35_fu_1791_p3;
reg   [7:0] select_ln0_35_reg_3584;
wire   [7:0] select_ln0_36_fu_1811_p3;
reg   [7:0] select_ln0_36_reg_3590;
wire   [7:0] select_ln0_37_fu_1831_p3;
reg   [7:0] select_ln0_37_reg_3596;
wire   [7:0] select_ln0_38_fu_1851_p3;
reg   [7:0] select_ln0_38_reg_3602;
wire   [7:0] select_ln0_39_fu_1871_p3;
reg   [7:0] select_ln0_39_reg_3608;
wire   [7:0] select_ln0_40_fu_1891_p3;
reg   [7:0] select_ln0_40_reg_3614;
wire   [7:0] select_ln0_41_fu_1911_p3;
reg   [7:0] select_ln0_41_reg_3620;
wire   [7:0] select_ln0_42_fu_1931_p3;
reg   [7:0] select_ln0_42_reg_3626;
wire   [7:0] select_ln0_43_fu_1951_p3;
reg   [7:0] select_ln0_43_reg_3632;
wire   [7:0] select_ln0_44_fu_1971_p3;
reg   [7:0] select_ln0_44_reg_3638;
wire   [7:0] select_ln0_45_fu_1991_p3;
reg   [7:0] select_ln0_45_reg_3644;
wire   [7:0] select_ln0_46_fu_2011_p3;
reg   [7:0] select_ln0_46_reg_3650;
wire   [0:0] icmp_ln212_fu_2025_p2;
wire   [0:0] icmp_ln216_fu_2079_p2;
wire   [0:0] icmp_ln243_fu_2145_p2;
reg   [0:0] icmp_ln243_reg_3664;
wire   [0:0] icmp_ln241_fu_2151_p2;
reg   [0:0] icmp_ln241_reg_3669;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg   [0:0] ap_phi_mux_icmp_ln24386_phi_fu_431_p4;
reg   [7:0] ap_phi_mux_p_0_0_0_0_09384_phi_fu_441_p4;
reg   [31:0] ap_phi_mux_storemerge_i_i_phi_fu_451_p4;
wire   [31:0] select_ln222_fu_2107_p3;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_i_i_reg_448;
wire    ap_CS_fsm_state4;
wire   [31:0] select_ln227_fu_2043_p3;
wire   [31:0] add_ln212_fu_2019_p2;
wire   [31:0] add_ln216_fu_2073_p2;
reg   [7:0] indvar_flatten3_fu_218;
wire   [7:0] add_ln241_fu_1276_p2;
reg   [7:0] p_0_15_0_0_02336_fu_222;
reg   [7:0] p_0_14_0_0_02298_fu_226;
reg   [7:0] p_0_13_0_0_022510_fu_230;
reg   [7:0] p_0_12_0_0_022112_fu_234;
reg   [7:0] p_0_11_0_0_021714_fu_238;
reg   [7:0] p_0_10_0_0_021316_fu_242;
reg   [7:0] p_0_9_0_0_020918_fu_246;
reg   [7:0] p_0_8_0_0_020520_fu_250;
reg   [7:0] p_0_7_0_0_020122_fu_254;
reg   [7:0] p_0_6_0_0_019724_fu_258;
reg   [7:0] p_0_5_0_0_019326_fu_262;
reg   [7:0] p_0_4_0_0_018928_fu_266;
reg   [7:0] p_0_3_0_0_018530_fu_270;
reg   [7:0] p_0_2_0_0_018132_fu_274;
reg   [7:0] p_0_1_0_0_017734_fu_278;
reg   [7:0] p_0_0_0_0_017336_fu_282;
reg   [7:0] p_0_15_0_0_012317037_fu_286;
reg   [7:0] p_0_14_0_0_012116739_fu_290;
reg   [7:0] p_0_13_0_0_011916441_fu_294;
reg   [7:0] p_0_12_0_0_011716143_fu_298;
reg   [7:0] p_0_11_0_0_011515845_fu_302;
reg   [7:0] p_0_10_0_0_011315547_fu_306;
reg   [7:0] p_0_9_0_0_011115249_fu_310;
reg   [7:0] p_0_8_0_0_010914951_fu_314;
reg   [7:0] p_0_7_0_0_010714653_fu_318;
reg   [7:0] p_0_6_0_0_010514355_fu_322;
reg   [7:0] p_0_5_0_0_010314057_fu_326;
reg   [7:0] p_0_4_0_0_010113759_fu_330;
reg   [7:0] p_0_3_0_0_09913461_fu_334;
reg   [7:0] p_0_2_0_0_09713163_fu_338;
reg   [7:0] p_0_1_0_0_09512865_fu_342;
reg   [7:0] p_0_0_0_0_09312567_fu_346;
reg   [7:0] p_0_15_0_0_012369_fu_350;
reg   [7:0] p_0_14_0_0_012170_fu_354;
reg   [7:0] p_0_13_0_0_011971_fu_358;
reg   [7:0] p_0_12_0_0_011772_fu_362;
reg   [7:0] p_0_11_0_0_011573_fu_366;
reg   [7:0] p_0_10_0_0_011374_fu_370;
reg   [7:0] p_0_9_0_0_011175_fu_374;
reg   [7:0] p_0_8_0_0_010976_fu_378;
reg   [7:0] p_0_7_0_0_010777_fu_382;
reg   [7:0] p_0_6_0_0_010578_fu_386;
reg   [7:0] p_0_5_0_0_010379_fu_390;
reg   [7:0] p_0_4_0_0_010180_fu_394;
reg   [7:0] p_0_3_0_0_09981_fu_398;
reg   [7:0] p_0_2_0_0_09782_fu_402;
reg   [7:0] p_0_1_0_0_09583_fu_406;
reg   [4:0] i_iw_fu_410;
wire   [4:0] i_iw_3_fu_2137_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln191_5_fu_1296_p2;
wire   [0:0] icmp_ln191_6_fu_1302_p2;
wire   [0:0] and_ln191_fu_1308_p2;
wire   [0:0] icmp_ln191_4_fu_1286_p2;
wire   [0:0] icmp_ln66_fu_1371_p2;
wire   [0:0] xor_ln66_fu_1377_p2;
wire   [7:0] select_ln24187_fu_1391_p3;
wire   [0:0] icmp_ln66_24_fu_1399_p2;
wire   [0:0] xor_ln66_24_fu_1405_p2;
wire   [0:0] icmp_ln66_26_fu_1419_p2;
wire   [0:0] xor_ln66_26_fu_1425_p2;
wire   [0:0] icmp_ln66_27_fu_1439_p2;
wire   [0:0] xor_ln66_27_fu_1445_p2;
wire   [0:0] icmp_ln66_29_fu_1459_p2;
wire   [0:0] xor_ln66_29_fu_1465_p2;
wire   [0:0] icmp_ln66_30_fu_1479_p2;
wire   [0:0] xor_ln66_30_fu_1485_p2;
wire   [0:0] icmp_ln66_32_fu_1499_p2;
wire   [0:0] xor_ln66_32_fu_1505_p2;
wire   [0:0] icmp_ln66_33_fu_1519_p2;
wire   [0:0] xor_ln66_33_fu_1525_p2;
wire   [0:0] icmp_ln66_35_fu_1539_p2;
wire   [0:0] xor_ln66_35_fu_1545_p2;
wire   [0:0] icmp_ln66_36_fu_1559_p2;
wire   [0:0] xor_ln66_36_fu_1565_p2;
wire   [0:0] icmp_ln66_38_fu_1579_p2;
wire   [0:0] xor_ln66_38_fu_1585_p2;
wire   [0:0] icmp_ln66_39_fu_1599_p2;
wire   [0:0] xor_ln66_39_fu_1605_p2;
wire   [0:0] icmp_ln66_41_fu_1619_p2;
wire   [0:0] xor_ln66_41_fu_1625_p2;
wire   [0:0] icmp_ln66_42_fu_1639_p2;
wire   [0:0] xor_ln66_42_fu_1645_p2;
wire   [0:0] icmp_ln66_44_fu_1659_p2;
wire   [0:0] xor_ln66_44_fu_1665_p2;
wire   [0:0] icmp_ln66_45_fu_1679_p2;
wire   [0:0] xor_ln66_45_fu_1685_p2;
wire   [0:0] icmp_ln66_47_fu_1699_p2;
wire   [0:0] xor_ln66_47_fu_1705_p2;
wire   [0:0] icmp_ln66_48_fu_1719_p2;
wire   [0:0] xor_ln66_48_fu_1725_p2;
wire   [0:0] icmp_ln66_50_fu_1739_p2;
wire   [0:0] xor_ln66_50_fu_1745_p2;
wire   [0:0] icmp_ln66_51_fu_1759_p2;
wire   [0:0] xor_ln66_51_fu_1765_p2;
wire   [0:0] icmp_ln66_53_fu_1779_p2;
wire   [0:0] xor_ln66_53_fu_1785_p2;
wire   [0:0] icmp_ln66_54_fu_1799_p2;
wire   [0:0] xor_ln66_54_fu_1805_p2;
wire   [0:0] icmp_ln66_56_fu_1819_p2;
wire   [0:0] xor_ln66_56_fu_1825_p2;
wire   [0:0] icmp_ln66_57_fu_1839_p2;
wire   [0:0] xor_ln66_57_fu_1845_p2;
wire   [0:0] icmp_ln66_59_fu_1859_p2;
wire   [0:0] xor_ln66_59_fu_1865_p2;
wire   [0:0] icmp_ln66_60_fu_1879_p2;
wire   [0:0] xor_ln66_60_fu_1885_p2;
wire   [0:0] icmp_ln66_62_fu_1899_p2;
wire   [0:0] xor_ln66_62_fu_1905_p2;
wire   [0:0] icmp_ln66_63_fu_1919_p2;
wire   [0:0] xor_ln66_63_fu_1925_p2;
wire   [0:0] icmp_ln66_65_fu_1939_p2;
wire   [0:0] xor_ln66_65_fu_1945_p2;
wire   [0:0] icmp_ln66_66_fu_1959_p2;
wire   [0:0] xor_ln66_66_fu_1965_p2;
wire   [0:0] icmp_ln66_68_fu_1979_p2;
wire   [0:0] xor_ln66_68_fu_1985_p2;
wire   [0:0] icmp_ln66_69_fu_1999_p2;
wire   [0:0] xor_ln66_69_fu_2005_p2;
wire   [31:0] add_ln227_fu_2037_p2;
wire   [0:0] icmp_ln222_fu_2095_p2;
wire   [31:0] add_ln222_fu_2101_p2;
wire   [4:0] add_ln243_fu_2131_p2;
wire   [0:0] icmp_ln66_25_fu_2402_p2;
wire   [0:0] xor_ln66_25_fu_2406_p2;
wire   [0:0] icmp_ln66_28_fu_2418_p2;
wire   [0:0] xor_ln66_28_fu_2422_p2;
wire   [0:0] icmp_ln66_31_fu_2434_p2;
wire   [0:0] xor_ln66_31_fu_2438_p2;
wire   [0:0] icmp_ln66_34_fu_2450_p2;
wire   [0:0] xor_ln66_34_fu_2454_p2;
wire   [0:0] icmp_ln66_37_fu_2466_p2;
wire   [0:0] xor_ln66_37_fu_2470_p2;
wire   [0:0] icmp_ln66_40_fu_2482_p2;
wire   [0:0] xor_ln66_40_fu_2486_p2;
wire   [0:0] icmp_ln66_43_fu_2498_p2;
wire   [0:0] xor_ln66_43_fu_2502_p2;
wire   [0:0] icmp_ln66_46_fu_2514_p2;
wire   [0:0] xor_ln66_46_fu_2518_p2;
wire   [0:0] icmp_ln66_49_fu_2530_p2;
wire   [0:0] xor_ln66_49_fu_2534_p2;
wire   [0:0] icmp_ln66_52_fu_2546_p2;
wire   [0:0] xor_ln66_52_fu_2550_p2;
wire   [0:0] icmp_ln66_55_fu_2562_p2;
wire   [0:0] xor_ln66_55_fu_2566_p2;
wire   [0:0] icmp_ln66_58_fu_2578_p2;
wire   [0:0] xor_ln66_58_fu_2582_p2;
wire   [0:0] icmp_ln66_61_fu_2594_p2;
wire   [0:0] xor_ln66_61_fu_2598_p2;
wire   [0:0] icmp_ln66_64_fu_2610_p2;
wire   [0:0] xor_ln66_64_fu_2614_p2;
wire   [0:0] icmp_ln66_67_fu_2626_p2;
wire   [0:0] xor_ln66_67_fu_2630_p2;
wire   [0:0] icmp_ln66_70_fu_2642_p2;
wire   [0:0] xor_ln66_70_fu_2646_p2;
wire   [7:0] res_pack_22_fu_2652_p3;
wire   [7:0] res_pack_21_fu_2636_p3;
wire   [7:0] res_pack_20_fu_2620_p3;
wire   [7:0] res_pack_19_fu_2604_p3;
wire   [7:0] res_pack_18_fu_2588_p3;
wire   [7:0] res_pack_17_fu_2572_p3;
wire   [7:0] res_pack_16_fu_2556_p3;
wire   [7:0] res_pack_15_fu_2540_p3;
wire   [7:0] res_pack_14_fu_2524_p3;
wire   [7:0] res_pack_13_fu_2508_p3;
wire   [7:0] res_pack_12_fu_2492_p3;
wire   [7:0] res_pack_11_fu_2476_p3;
wire   [7:0] res_pack_10_fu_2460_p3;
wire   [7:0] res_pack_9_fu_2444_p3;
wire   [7:0] res_pack_8_fu_2428_p3;
wire   [7:0] res_pack_fu_2412_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_163;
reg    ap_condition_429;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_22 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_16 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_15 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_14 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_13 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_12 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_11 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_10 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_9 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_8 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_21 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_20 = 8'd0;
#0 void_pooling2d_buffer_cl_stream_stream_array_ap_fixed_16u_0_line_buffer = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_19 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_18 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_17 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_45 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_44 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_43 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_42 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_41 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_40 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_39 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_38 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_37 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_36 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_35 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_34 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_33 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_32 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_31 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_30 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_29 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_28 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_27 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_26 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_25 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_24 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_23 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_22 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_21 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_20 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_19 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_18 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_17 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_16 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_15 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_14 = 8'd0;
#0 sX_1 = 32'd0;
#0 pX_1 = 32'd0;
#0 sY_1 = 32'd0;
#0 pY_1 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 indvar_flatten3_fu_218 = 8'd0;
#0 p_0_15_0_0_02336_fu_222 = 8'd0;
#0 p_0_14_0_0_02298_fu_226 = 8'd0;
#0 p_0_13_0_0_022510_fu_230 = 8'd0;
#0 p_0_12_0_0_022112_fu_234 = 8'd0;
#0 p_0_11_0_0_021714_fu_238 = 8'd0;
#0 p_0_10_0_0_021316_fu_242 = 8'd0;
#0 p_0_9_0_0_020918_fu_246 = 8'd0;
#0 p_0_8_0_0_020520_fu_250 = 8'd0;
#0 p_0_7_0_0_020122_fu_254 = 8'd0;
#0 p_0_6_0_0_019724_fu_258 = 8'd0;
#0 p_0_5_0_0_019326_fu_262 = 8'd0;
#0 p_0_4_0_0_018928_fu_266 = 8'd0;
#0 p_0_3_0_0_018530_fu_270 = 8'd0;
#0 p_0_2_0_0_018132_fu_274 = 8'd0;
#0 p_0_1_0_0_017734_fu_278 = 8'd0;
#0 p_0_0_0_0_017336_fu_282 = 8'd0;
#0 p_0_15_0_0_012317037_fu_286 = 8'd0;
#0 p_0_14_0_0_012116739_fu_290 = 8'd0;
#0 p_0_13_0_0_011916441_fu_294 = 8'd0;
#0 p_0_12_0_0_011716143_fu_298 = 8'd0;
#0 p_0_11_0_0_011515845_fu_302 = 8'd0;
#0 p_0_10_0_0_011315547_fu_306 = 8'd0;
#0 p_0_9_0_0_011115249_fu_310 = 8'd0;
#0 p_0_8_0_0_010914951_fu_314 = 8'd0;
#0 p_0_7_0_0_010714653_fu_318 = 8'd0;
#0 p_0_6_0_0_010514355_fu_322 = 8'd0;
#0 p_0_5_0_0_010314057_fu_326 = 8'd0;
#0 p_0_4_0_0_010113759_fu_330 = 8'd0;
#0 p_0_3_0_0_09913461_fu_334 = 8'd0;
#0 p_0_2_0_0_09713163_fu_338 = 8'd0;
#0 p_0_1_0_0_09512865_fu_342 = 8'd0;
#0 p_0_0_0_0_09312567_fu_346 = 8'd0;
#0 p_0_15_0_0_012369_fu_350 = 8'd0;
#0 p_0_14_0_0_012170_fu_354 = 8'd0;
#0 p_0_13_0_0_011971_fu_358 = 8'd0;
#0 p_0_12_0_0_011772_fu_362 = 8'd0;
#0 p_0_11_0_0_011573_fu_366 = 8'd0;
#0 p_0_10_0_0_011374_fu_370 = 8'd0;
#0 p_0_9_0_0_011175_fu_374 = 8'd0;
#0 p_0_8_0_0_010976_fu_378 = 8'd0;
#0 p_0_7_0_0_010777_fu_382 = 8'd0;
#0 p_0_6_0_0_010578_fu_386 = 8'd0;
#0 p_0_5_0_0_010379_fu_390 = 8'd0;
#0 p_0_4_0_0_010180_fu_394 = 8'd0;
#0 p_0_3_0_0_09981_fu_398 = 8'd0;
#0 p_0_2_0_0_09782_fu_402 = 8'd0;
#0 p_0_1_0_0_09583_fu_406 = 8'd0;
#0 i_iw_fu_410 = 5'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        i_iw_fu_410 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_iw_fu_410 <= i_iw_3_fu_2137_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln241_reg_3669 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln24386_reg_427 <= icmp_ln243_reg_3664;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        icmp_ln24386_reg_427 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        indvar_flatten3_fu_218 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten3_fu_218 <= add_ln241_fu_1276_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_163)) begin
        if ((icmp_ln212_fu_2025_p2 == 1'd1)) begin
            pX_1 <= 32'd0;
        end else if ((icmp_ln212_fu_2025_p2 == 1'd0)) begin
            pX_1 <= add_ln212_fu_2019_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_429)) begin
        if ((icmp_ln216_fu_2079_p2 == 1'd1)) begin
            pY_1 <= 32'd0;
        end else if ((icmp_ln216_fu_2079_p2 == 1'd0)) begin
            pY_1 <= add_ln216_fu_2073_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_017336_fu_282 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_29;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_0_0_0_017336_fu_282 <= trunc_ln247_fu_1108_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_09312567_fu_346 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_45;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_0_0_0_09312567_fu_346 <= ap_phi_mux_p_0_0_0_0_09384_phi_fu_441_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln241_reg_3669 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_0_0_0_09384_reg_438 <= trunc_ln247_reg_3359;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_09384_reg_438 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_22;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_011315547_fu_306 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_35;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_10_0_0_011315547_fu_306 <= select_ln241_11_fu_1028_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_011374_fu_370 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_21;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_10_0_0_011374_fu_370 <= {{layer8_out_dout[87:80]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_021316_fu_242 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_19;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_10_0_0_021316_fu_242 <= {{layer8_out_dout[87:80]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_011515845_fu_302 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_34;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_11_0_0_011515845_fu_302 <= select_ln241_10_fu_1020_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_011573_fu_366 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_20;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_11_0_0_011573_fu_366 <= {{layer8_out_dout[95:88]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_021714_fu_238 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_18;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_11_0_0_021714_fu_238 <= {{layer8_out_dout[95:88]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_011716143_fu_298 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_33;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_12_0_0_011716143_fu_298 <= select_ln241_9_fu_1012_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_011772_fu_362 <= void_pooling2d_buffer_cl_stream_stream_array_ap_fixed_16u_0_line_buffer;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_12_0_0_011772_fu_362 <= {{layer8_out_dout[103:96]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_022112_fu_234 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_17;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_12_0_0_022112_fu_234 <= {{layer8_out_dout[103:96]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_011916441_fu_294 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_32;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_13_0_0_011916441_fu_294 <= select_ln241_8_fu_1004_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_011971_fu_358 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_19;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_13_0_0_011971_fu_358 <= {{layer8_out_dout[111:104]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_022510_fu_230 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_16;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_13_0_0_022510_fu_230 <= {{layer8_out_dout[111:104]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_14_0_0_012116739_fu_290 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_31;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_14_0_0_012116739_fu_290 <= select_ln241_7_fu_996_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_14_0_0_012170_fu_354 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_18;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_14_0_0_012170_fu_354 <= {{layer8_out_dout[119:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_14_0_0_02298_fu_226 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_15;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_14_0_0_02298_fu_226 <= {{layer8_out_dout[119:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_15_0_0_012317037_fu_286 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_30;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_15_0_0_012317037_fu_286 <= select_ln241_fu_988_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_15_0_0_012369_fu_350 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_17;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_15_0_0_012369_fu_350 <= {{layer8_out_dout[127:120]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_15_0_0_02336_fu_222 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_14;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_15_0_0_02336_fu_222 <= {{layer8_out_dout[127:120]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_017734_fu_278 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_28;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_1_0_0_017734_fu_278 <= {{layer8_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_09512865_fu_342 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_44;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_1_0_0_09512865_fu_342 <= select_ln241_20_fu_1100_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_09583_fu_406 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_16;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_1_0_0_09583_fu_406 <= {{layer8_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_018132_fu_274 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_27;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_2_0_0_018132_fu_274 <= {{layer8_out_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_09713163_fu_338 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_43;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_2_0_0_09713163_fu_338 <= select_ln241_19_fu_1092_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_09782_fu_402 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_15;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_2_0_0_09782_fu_402 <= {{layer8_out_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_018530_fu_270 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_26;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_3_0_0_018530_fu_270 <= {{layer8_out_dout[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_09913461_fu_334 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_42;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_3_0_0_09913461_fu_334 <= select_ln241_18_fu_1084_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_09981_fu_398 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_14;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_3_0_0_09981_fu_398 <= {{layer8_out_dout[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_010113759_fu_330 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_41;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_4_0_0_010113759_fu_330 <= select_ln241_17_fu_1076_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_010180_fu_394 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_13;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_4_0_0_010180_fu_394 <= {{layer8_out_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_018928_fu_266 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_25;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_4_0_0_018928_fu_266 <= {{layer8_out_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_010314057_fu_326 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_40;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_5_0_0_010314057_fu_326 <= select_ln241_16_fu_1068_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_010379_fu_390 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_12;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_5_0_0_010379_fu_390 <= {{layer8_out_dout[47:40]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_019326_fu_262 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_24;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_5_0_0_019326_fu_262 <= {{layer8_out_dout[47:40]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_010514355_fu_322 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_39;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_6_0_0_010514355_fu_322 <= select_ln241_15_fu_1060_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_010578_fu_386 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_11;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_6_0_0_010578_fu_386 <= {{layer8_out_dout[55:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_019724_fu_258 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_23;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_6_0_0_019724_fu_258 <= {{layer8_out_dout[55:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_010714653_fu_318 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_38;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_7_0_0_010714653_fu_318 <= select_ln241_14_fu_1052_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_010777_fu_382 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_10;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_7_0_0_010777_fu_382 <= {{layer8_out_dout[63:56]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_020122_fu_254 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_22;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_7_0_0_020122_fu_254 <= {{layer8_out_dout[63:56]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_010914951_fu_314 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_37;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_8_0_0_010914951_fu_314 <= select_ln241_13_fu_1044_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_010976_fu_378 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_9;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_8_0_0_010976_fu_378 <= {{layer8_out_dout[71:64]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_020520_fu_250 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_21;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_8_0_0_020520_fu_250 <= {{layer8_out_dout[71:64]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_011115249_fu_310 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_36;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_9_0_0_011115249_fu_310 <= select_ln241_12_fu_1036_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_011175_fu_374 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_8;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_9_0_0_011175_fu_374 <= {{layer8_out_dout[79:72]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_020918_fu_246 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_20;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_9_0_0_020918_fu_246 <= {{layer8_out_dout[79:72]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_163)) begin
        if ((icmp_ln212_fu_2025_p2 == 1'd1)) begin
            sX_1 <= 32'd0;
        end else if ((icmp_ln212_fu_2025_p2 == 1'd0)) begin
            sX_1 <= select_ln227_fu_2043_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln191_2_reg_3460 <= and_ln191_2_fu_1314_p2;
        icmp_ln191_reg_3456 <= icmp_ln191_fu_1266_p2;
        icmp_ln241_reg_3669 <= icmp_ln241_fu_2151_p2;
        select_ln0_16_reg_3470 <= select_ln0_16_fu_1411_p3;
        select_ln0_17_reg_3476 <= select_ln0_17_fu_1431_p3;
        select_ln0_18_reg_3482 <= select_ln0_18_fu_1451_p3;
        select_ln0_19_reg_3488 <= select_ln0_19_fu_1471_p3;
        select_ln0_20_reg_3494 <= select_ln0_20_fu_1491_p3;
        select_ln0_21_reg_3500 <= select_ln0_21_fu_1511_p3;
        select_ln0_22_reg_3506 <= select_ln0_22_fu_1531_p3;
        select_ln0_23_reg_3512 <= select_ln0_23_fu_1551_p3;
        select_ln0_24_reg_3518 <= select_ln0_24_fu_1571_p3;
        select_ln0_25_reg_3524 <= select_ln0_25_fu_1591_p3;
        select_ln0_26_reg_3530 <= select_ln0_26_fu_1611_p3;
        select_ln0_27_reg_3536 <= select_ln0_27_fu_1631_p3;
        select_ln0_28_reg_3542 <= select_ln0_28_fu_1651_p3;
        select_ln0_29_reg_3548 <= select_ln0_29_fu_1671_p3;
        select_ln0_30_reg_3554 <= select_ln0_30_fu_1691_p3;
        select_ln0_31_reg_3560 <= select_ln0_31_fu_1711_p3;
        select_ln0_32_reg_3566 <= select_ln0_32_fu_1731_p3;
        select_ln0_33_reg_3572 <= select_ln0_33_fu_1751_p3;
        select_ln0_34_reg_3578 <= select_ln0_34_fu_1771_p3;
        select_ln0_35_reg_3584 <= select_ln0_35_fu_1791_p3;
        select_ln0_36_reg_3590 <= select_ln0_36_fu_1811_p3;
        select_ln0_37_reg_3596 <= select_ln0_37_fu_1831_p3;
        select_ln0_38_reg_3602 <= select_ln0_38_fu_1851_p3;
        select_ln0_39_reg_3608 <= select_ln0_39_fu_1871_p3;
        select_ln0_40_reg_3614 <= select_ln0_40_fu_1891_p3;
        select_ln0_41_reg_3620 <= select_ln0_41_fu_1911_p3;
        select_ln0_42_reg_3626 <= select_ln0_42_fu_1931_p3;
        select_ln0_43_reg_3632 <= select_ln0_43_fu_1951_p3;
        select_ln0_44_reg_3638 <= select_ln0_44_fu_1971_p3;
        select_ln0_45_reg_3644 <= select_ln0_45_fu_1991_p3;
        select_ln0_46_reg_3650 <= select_ln0_46_fu_2011_p3;
        select_ln0_reg_3464 <= select_ln0_fu_1383_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        icmp_ln243_reg_3664 <= icmp_ln243_fu_2145_p2;
        select_ln241_10_reg_3304 <= select_ln241_10_fu_1020_p3;
        select_ln241_11_reg_3309 <= select_ln241_11_fu_1028_p3;
        select_ln241_12_reg_3314 <= select_ln241_12_fu_1036_p3;
        select_ln241_13_reg_3319 <= select_ln241_13_fu_1044_p3;
        select_ln241_14_reg_3324 <= select_ln241_14_fu_1052_p3;
        select_ln241_15_reg_3329 <= select_ln241_15_fu_1060_p3;
        select_ln241_16_reg_3334 <= select_ln241_16_fu_1068_p3;
        select_ln241_17_reg_3339 <= select_ln241_17_fu_1076_p3;
        select_ln241_18_reg_3344 <= select_ln241_18_fu_1084_p3;
        select_ln241_19_reg_3349 <= select_ln241_19_fu_1092_p3;
        select_ln241_20_reg_3354 <= select_ln241_20_fu_1100_p3;
        select_ln241_7_reg_3289 <= select_ln241_7_fu_996_p3;
        select_ln241_8_reg_3294 <= select_ln241_8_fu_1004_p3;
        select_ln241_9_reg_3299 <= select_ln241_9_fu_1012_p3;
        select_ln241_reg_3284 <= select_ln241_fu_988_p3;
        trunc_ln247_10_reg_3426 <= {{layer8_out_dout[95:88]}};
        trunc_ln247_11_reg_3432 <= {{layer8_out_dout[103:96]}};
        trunc_ln247_12_reg_3438 <= {{layer8_out_dout[111:104]}};
        trunc_ln247_13_reg_3444 <= {{layer8_out_dout[119:112]}};
        trunc_ln247_14_reg_3450 <= {{layer8_out_dout[127:120]}};
        trunc_ln247_1_reg_3366 <= {{layer8_out_dout[15:8]}};
        trunc_ln247_2_reg_3372 <= {{layer8_out_dout[23:16]}};
        trunc_ln247_3_reg_3378 <= {{layer8_out_dout[31:24]}};
        trunc_ln247_4_reg_3384 <= {{layer8_out_dout[39:32]}};
        trunc_ln247_5_reg_3390 <= {{layer8_out_dout[47:40]}};
        trunc_ln247_6_reg_3396 <= {{layer8_out_dout[55:48]}};
        trunc_ln247_7_reg_3402 <= {{layer8_out_dout[63:56]}};
        trunc_ln247_8_reg_3408 <= {{layer8_out_dout[71:64]}};
        trunc_ln247_9_reg_3414 <= {{layer8_out_dout[79:72]}};
        trunc_ln247_reg_3359 <= trunc_ln247_fu_1108_p1;
        trunc_ln247_s_reg_3420 <= {{layer8_out_dout[87:80]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_10 <= trunc_ln247_7_reg_3402;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_11 <= trunc_ln247_6_reg_3396;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_12 <= trunc_ln247_5_reg_3390;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_13 <= trunc_ln247_4_reg_3384;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_14 <= trunc_ln247_3_reg_3378;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_15 <= trunc_ln247_2_reg_3372;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_16 <= trunc_ln247_1_reg_3366;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_17 <= trunc_ln247_14_reg_3450;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_18 <= trunc_ln247_13_reg_3444;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_19 <= trunc_ln247_12_reg_3438;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_20 <= trunc_ln247_10_reg_3426;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_21 <= trunc_ln247_s_reg_3420;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_22 <= trunc_ln247_reg_3359;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_8 <= trunc_ln247_9_reg_3414;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_9 <= trunc_ln247_8_reg_3408;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_14 <= trunc_ln247_14_reg_3450;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_15 <= trunc_ln247_13_reg_3444;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_16 <= trunc_ln247_12_reg_3438;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_17 <= trunc_ln247_11_reg_3432;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_18 <= trunc_ln247_10_reg_3426;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_19 <= trunc_ln247_s_reg_3420;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_20 <= trunc_ln247_9_reg_3414;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_21 <= trunc_ln247_8_reg_3408;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_22 <= trunc_ln247_7_reg_3402;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_23 <= trunc_ln247_6_reg_3396;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_24 <= trunc_ln247_5_reg_3390;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_25 <= trunc_ln247_4_reg_3384;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_26 <= trunc_ln247_3_reg_3378;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_27 <= trunc_ln247_2_reg_3372;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_28 <= trunc_ln247_1_reg_3366;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_29 <= trunc_ln247_reg_3359;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_30 <= select_ln241_reg_3284;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_31 <= select_ln241_7_reg_3289;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_32 <= select_ln241_8_reg_3294;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_33 <= select_ln241_9_reg_3299;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_34 <= select_ln241_10_reg_3304;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_35 <= select_ln241_11_reg_3309;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_36 <= select_ln241_12_reg_3314;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_37 <= select_ln241_13_reg_3319;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_38 <= select_ln241_14_reg_3324;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_39 <= select_ln241_15_reg_3329;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_40 <= select_ln241_16_reg_3334;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_41 <= select_ln241_17_reg_3339;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_42 <= select_ln241_18_reg_3344;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_43 <= select_ln241_19_reg_3349;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_44 <= select_ln241_20_reg_3354;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_45 <= p_0_0_0_0_09384_reg_438;
        void_pooling2d_buffer_cl_stream_stream_array_ap_fixed_16u_0_line_buffer <= trunc_ln247_11_reg_3432;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln212_fu_2025_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        sY_1 <= ap_phi_mux_storemerge_i_i_phi_fu_451_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln241_fu_2151_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_3669 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_icmp_ln24386_phi_fu_431_p4 = icmp_ln243_reg_3664;
    end else begin
        ap_phi_mux_icmp_ln24386_phi_fu_431_p4 = icmp_ln24386_reg_427;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_3669 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_0_0_0_0_09384_phi_fu_441_p4 = trunc_ln247_reg_3359;
    end else begin
        ap_phi_mux_p_0_0_0_0_09384_phi_fu_441_p4 = p_0_0_0_0_09384_reg_438;
    end
end

always @ (*) begin
    if ((icmp_ln212_fu_2025_p2 == 1'd1)) begin
        if ((icmp_ln216_fu_2079_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_i_i_phi_fu_451_p4 = 32'd0;
        end else if ((icmp_ln216_fu_2079_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_i_i_phi_fu_451_p4 = select_ln222_fu_2107_p3;
        end else begin
            ap_phi_mux_storemerge_i_i_phi_fu_451_p4 = ap_phi_reg_pp0_iter0_storemerge_i_i_reg_448;
        end
    end else begin
        ap_phi_mux_storemerge_i_i_phi_fu_451_p4 = ap_phi_reg_pp0_iter0_storemerge_i_i_reg_448;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        layer8_out_blk_n = layer8_out_empty_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        layer8_out_read = 1'b1;
    end else begin
        layer8_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln191_2_reg_3460) & (icmp_ln191_reg_3456 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        layer9_out_blk_n = layer9_out_full_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op478_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer9_out_write = 1'b1;
    end else begin
        layer9_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln212_fu_2019_p2 = (pX_1 + 32'd1);

assign add_ln216_fu_2073_p2 = (pY_1 + 32'd1);

assign add_ln222_fu_2101_p2 = (sY_1 + 32'd1);

assign add_ln227_fu_2037_p2 = (sX_1 + 32'd1);

assign add_ln241_fu_1276_p2 = (indvar_flatten3_fu_218 + 8'd1);

assign add_ln243_fu_2131_p2 = (i_iw_fu_410 + 5'd1);

assign and_ln191_2_fu_1314_p2 = (icmp_ln191_4_fu_1286_p2 & and_ln191_fu_1308_p2);

assign and_ln191_fu_1308_p2 = (icmp_ln191_6_fu_1302_p2 & icmp_ln191_5_fu_1296_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == ap_block_state3_pp0_stage0_iter1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state3_pp0_stage0_iter1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state3_pp0_stage0_iter1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (layer8_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((layer9_out_full_n == 1'b0) & (ap_predicate_op478_write_state3 == 1'b1));
end

always @ (*) begin
    ap_condition_163 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_429 = ((icmp_ln212_fu_2025_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_storemerge_i_i_reg_448 = 'bx;

always @ (*) begin
    ap_predicate_op478_write_state3 = ((1'd1 == and_ln191_2_reg_3460) & (icmp_ln191_reg_3456 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign i_iw_3_fu_2137_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? 5'd1 : add_ln243_fu_2131_p2);

assign icmp_ln191_4_fu_1286_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln191_5_fu_1296_p2 = (($signed(pY_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln191_6_fu_1302_p2 = (($signed(pX_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_1266_p2 = ((sX_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln212_fu_2025_p2 = ((add_ln212_fu_2019_p2 == 32'd30) ? 1'b1 : 1'b0);

assign icmp_ln216_fu_2079_p2 = ((add_ln216_fu_2073_p2 == 32'd5) ? 1'b1 : 1'b0);

assign icmp_ln222_fu_2095_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_2151_p2 = ((indvar_flatten3_fu_218 == 8'd149) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_2145_p2 = ((i_iw_3_fu_2137_p3 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln66_24_fu_1399_p2 = (($signed(select_ln24187_fu_1391_p3) < $signed(trunc_ln247_fu_1108_p1)) ? 1'b1 : 1'b0);

assign icmp_ln66_25_fu_2402_p2 = (($signed(select_ln0_reg_3464) < $signed(select_ln0_16_reg_3470)) ? 1'b1 : 1'b0);

assign icmp_ln66_26_fu_1419_p2 = (($signed(p_0_1_0_0_09512865_fu_342) < $signed(select_ln241_20_fu_1100_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_27_fu_1439_p2 = (($signed(p_0_1_0_0_017734_fu_278) < $signed(trunc_ln247_1_fu_1112_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_28_fu_2418_p2 = (($signed(select_ln0_17_reg_3476) < $signed(select_ln0_18_reg_3482)) ? 1'b1 : 1'b0);

assign icmp_ln66_29_fu_1459_p2 = (($signed(p_0_2_0_0_09713163_fu_338) < $signed(select_ln241_19_fu_1092_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_30_fu_1479_p2 = (($signed(p_0_2_0_0_018132_fu_274) < $signed(trunc_ln247_2_fu_1122_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_31_fu_2434_p2 = (($signed(select_ln0_19_reg_3488) < $signed(select_ln0_20_reg_3494)) ? 1'b1 : 1'b0);

assign icmp_ln66_32_fu_1499_p2 = (($signed(p_0_3_0_0_09913461_fu_334) < $signed(select_ln241_18_fu_1084_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_33_fu_1519_p2 = (($signed(p_0_3_0_0_018530_fu_270) < $signed(trunc_ln247_3_fu_1132_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_34_fu_2450_p2 = (($signed(select_ln0_21_reg_3500) < $signed(select_ln0_22_reg_3506)) ? 1'b1 : 1'b0);

assign icmp_ln66_35_fu_1539_p2 = (($signed(p_0_4_0_0_010113759_fu_330) < $signed(select_ln241_17_fu_1076_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_36_fu_1559_p2 = (($signed(p_0_4_0_0_018928_fu_266) < $signed(trunc_ln247_4_fu_1142_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_37_fu_2466_p2 = (($signed(select_ln0_23_reg_3512) < $signed(select_ln0_24_reg_3518)) ? 1'b1 : 1'b0);

assign icmp_ln66_38_fu_1579_p2 = (($signed(p_0_5_0_0_010314057_fu_326) < $signed(select_ln241_16_fu_1068_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_39_fu_1599_p2 = (($signed(p_0_5_0_0_019326_fu_262) < $signed(trunc_ln247_5_fu_1152_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_40_fu_2482_p2 = (($signed(select_ln0_25_reg_3524) < $signed(select_ln0_26_reg_3530)) ? 1'b1 : 1'b0);

assign icmp_ln66_41_fu_1619_p2 = (($signed(p_0_6_0_0_010514355_fu_322) < $signed(select_ln241_15_fu_1060_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_42_fu_1639_p2 = (($signed(p_0_6_0_0_019724_fu_258) < $signed(trunc_ln247_6_fu_1162_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_43_fu_2498_p2 = (($signed(select_ln0_27_reg_3536) < $signed(select_ln0_28_reg_3542)) ? 1'b1 : 1'b0);

assign icmp_ln66_44_fu_1659_p2 = (($signed(p_0_7_0_0_010714653_fu_318) < $signed(select_ln241_14_fu_1052_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_45_fu_1679_p2 = (($signed(p_0_7_0_0_020122_fu_254) < $signed(trunc_ln247_7_fu_1172_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_46_fu_2514_p2 = (($signed(select_ln0_29_reg_3548) < $signed(select_ln0_30_reg_3554)) ? 1'b1 : 1'b0);

assign icmp_ln66_47_fu_1699_p2 = (($signed(p_0_8_0_0_010914951_fu_314) < $signed(select_ln241_13_fu_1044_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_48_fu_1719_p2 = (($signed(p_0_8_0_0_020520_fu_250) < $signed(trunc_ln247_8_fu_1182_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_49_fu_2530_p2 = (($signed(select_ln0_31_reg_3560) < $signed(select_ln0_32_reg_3566)) ? 1'b1 : 1'b0);

assign icmp_ln66_50_fu_1739_p2 = (($signed(p_0_9_0_0_011115249_fu_310) < $signed(select_ln241_12_fu_1036_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_51_fu_1759_p2 = (($signed(p_0_9_0_0_020918_fu_246) < $signed(trunc_ln247_9_fu_1192_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_52_fu_2546_p2 = (($signed(select_ln0_33_reg_3572) < $signed(select_ln0_34_reg_3578)) ? 1'b1 : 1'b0);

assign icmp_ln66_53_fu_1779_p2 = (($signed(p_0_10_0_0_011315547_fu_306) < $signed(select_ln241_11_fu_1028_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_54_fu_1799_p2 = (($signed(p_0_10_0_0_021316_fu_242) < $signed(trunc_ln247_s_fu_1202_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_55_fu_2562_p2 = (($signed(select_ln0_35_reg_3584) < $signed(select_ln0_36_reg_3590)) ? 1'b1 : 1'b0);

assign icmp_ln66_56_fu_1819_p2 = (($signed(p_0_11_0_0_011515845_fu_302) < $signed(select_ln241_10_fu_1020_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_57_fu_1839_p2 = (($signed(p_0_11_0_0_021714_fu_238) < $signed(trunc_ln247_10_fu_1212_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_58_fu_2578_p2 = (($signed(select_ln0_37_reg_3596) < $signed(select_ln0_38_reg_3602)) ? 1'b1 : 1'b0);

assign icmp_ln66_59_fu_1859_p2 = (($signed(p_0_12_0_0_011716143_fu_298) < $signed(select_ln241_9_fu_1012_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_60_fu_1879_p2 = (($signed(p_0_12_0_0_022112_fu_234) < $signed(trunc_ln247_11_fu_1222_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_61_fu_2594_p2 = (($signed(select_ln0_39_reg_3608) < $signed(select_ln0_40_reg_3614)) ? 1'b1 : 1'b0);

assign icmp_ln66_62_fu_1899_p2 = (($signed(p_0_13_0_0_011916441_fu_294) < $signed(select_ln241_8_fu_1004_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_63_fu_1919_p2 = (($signed(p_0_13_0_0_022510_fu_230) < $signed(trunc_ln247_12_fu_1232_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_64_fu_2610_p2 = (($signed(select_ln0_41_reg_3620) < $signed(select_ln0_42_reg_3626)) ? 1'b1 : 1'b0);

assign icmp_ln66_65_fu_1939_p2 = (($signed(p_0_14_0_0_012116739_fu_290) < $signed(select_ln241_7_fu_996_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_66_fu_1959_p2 = (($signed(p_0_14_0_0_02298_fu_226) < $signed(trunc_ln247_13_fu_1242_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_67_fu_2626_p2 = (($signed(select_ln0_43_reg_3632) < $signed(select_ln0_44_reg_3638)) ? 1'b1 : 1'b0);

assign icmp_ln66_68_fu_1979_p2 = (($signed(p_0_15_0_0_012317037_fu_286) < $signed(select_ln241_fu_988_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_69_fu_1999_p2 = (($signed(p_0_15_0_0_02336_fu_222) < $signed(trunc_ln247_14_fu_1252_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_70_fu_2642_p2 = (($signed(select_ln0_45_reg_3644) < $signed(select_ln0_46_reg_3650)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_1371_p2 = (($signed(p_0_0_0_0_09312567_fu_346) < $signed(ap_phi_mux_p_0_0_0_0_09384_phi_fu_441_p4)) ? 1'b1 : 1'b0);

assign layer9_out_din = {{{{{{{{{{{{{{{{res_pack_22_fu_2652_p3}, {res_pack_21_fu_2636_p3}}, {res_pack_20_fu_2620_p3}}, {res_pack_19_fu_2604_p3}}, {res_pack_18_fu_2588_p3}}, {res_pack_17_fu_2572_p3}}, {res_pack_16_fu_2556_p3}}, {res_pack_15_fu_2540_p3}}, {res_pack_14_fu_2524_p3}}, {res_pack_13_fu_2508_p3}}, {res_pack_12_fu_2492_p3}}, {res_pack_11_fu_2476_p3}}, {res_pack_10_fu_2460_p3}}, {res_pack_9_fu_2444_p3}}, {res_pack_8_fu_2428_p3}}, {res_pack_fu_2412_p3}};

assign res_pack_10_fu_2460_p3 = ((xor_ln66_34_fu_2454_p2[0:0] == 1'b1) ? select_ln0_21_reg_3500 : select_ln0_22_reg_3506);

assign res_pack_11_fu_2476_p3 = ((xor_ln66_37_fu_2470_p2[0:0] == 1'b1) ? select_ln0_23_reg_3512 : select_ln0_24_reg_3518);

assign res_pack_12_fu_2492_p3 = ((xor_ln66_40_fu_2486_p2[0:0] == 1'b1) ? select_ln0_25_reg_3524 : select_ln0_26_reg_3530);

assign res_pack_13_fu_2508_p3 = ((xor_ln66_43_fu_2502_p2[0:0] == 1'b1) ? select_ln0_27_reg_3536 : select_ln0_28_reg_3542);

assign res_pack_14_fu_2524_p3 = ((xor_ln66_46_fu_2518_p2[0:0] == 1'b1) ? select_ln0_29_reg_3548 : select_ln0_30_reg_3554);

assign res_pack_15_fu_2540_p3 = ((xor_ln66_49_fu_2534_p2[0:0] == 1'b1) ? select_ln0_31_reg_3560 : select_ln0_32_reg_3566);

assign res_pack_16_fu_2556_p3 = ((xor_ln66_52_fu_2550_p2[0:0] == 1'b1) ? select_ln0_33_reg_3572 : select_ln0_34_reg_3578);

assign res_pack_17_fu_2572_p3 = ((xor_ln66_55_fu_2566_p2[0:0] == 1'b1) ? select_ln0_35_reg_3584 : select_ln0_36_reg_3590);

assign res_pack_18_fu_2588_p3 = ((xor_ln66_58_fu_2582_p2[0:0] == 1'b1) ? select_ln0_37_reg_3596 : select_ln0_38_reg_3602);

assign res_pack_19_fu_2604_p3 = ((xor_ln66_61_fu_2598_p2[0:0] == 1'b1) ? select_ln0_39_reg_3608 : select_ln0_40_reg_3614);

assign res_pack_20_fu_2620_p3 = ((xor_ln66_64_fu_2614_p2[0:0] == 1'b1) ? select_ln0_41_reg_3620 : select_ln0_42_reg_3626);

assign res_pack_21_fu_2636_p3 = ((xor_ln66_67_fu_2630_p2[0:0] == 1'b1) ? select_ln0_43_reg_3632 : select_ln0_44_reg_3638);

assign res_pack_22_fu_2652_p3 = ((xor_ln66_70_fu_2646_p2[0:0] == 1'b1) ? select_ln0_45_reg_3644 : select_ln0_46_reg_3650);

assign res_pack_8_fu_2428_p3 = ((xor_ln66_28_fu_2422_p2[0:0] == 1'b1) ? select_ln0_17_reg_3476 : select_ln0_18_reg_3482);

assign res_pack_9_fu_2444_p3 = ((xor_ln66_31_fu_2438_p2[0:0] == 1'b1) ? select_ln0_19_reg_3488 : select_ln0_20_reg_3494);

assign res_pack_fu_2412_p3 = ((xor_ln66_25_fu_2406_p2[0:0] == 1'b1) ? select_ln0_reg_3464 : select_ln0_16_reg_3470);

assign select_ln0_16_fu_1411_p3 = ((xor_ln66_24_fu_1405_p2[0:0] == 1'b1) ? select_ln24187_fu_1391_p3 : trunc_ln247_fu_1108_p1);

assign select_ln0_17_fu_1431_p3 = ((xor_ln66_26_fu_1425_p2[0:0] == 1'b1) ? p_0_1_0_0_09512865_fu_342 : select_ln241_20_fu_1100_p3);

assign select_ln0_18_fu_1451_p3 = ((xor_ln66_27_fu_1445_p2[0:0] == 1'b1) ? p_0_1_0_0_017734_fu_278 : trunc_ln247_1_fu_1112_p4);

assign select_ln0_19_fu_1471_p3 = ((xor_ln66_29_fu_1465_p2[0:0] == 1'b1) ? p_0_2_0_0_09713163_fu_338 : select_ln241_19_fu_1092_p3);

assign select_ln0_20_fu_1491_p3 = ((xor_ln66_30_fu_1485_p2[0:0] == 1'b1) ? p_0_2_0_0_018132_fu_274 : trunc_ln247_2_fu_1122_p4);

assign select_ln0_21_fu_1511_p3 = ((xor_ln66_32_fu_1505_p2[0:0] == 1'b1) ? p_0_3_0_0_09913461_fu_334 : select_ln241_18_fu_1084_p3);

assign select_ln0_22_fu_1531_p3 = ((xor_ln66_33_fu_1525_p2[0:0] == 1'b1) ? p_0_3_0_0_018530_fu_270 : trunc_ln247_3_fu_1132_p4);

assign select_ln0_23_fu_1551_p3 = ((xor_ln66_35_fu_1545_p2[0:0] == 1'b1) ? p_0_4_0_0_010113759_fu_330 : select_ln241_17_fu_1076_p3);

assign select_ln0_24_fu_1571_p3 = ((xor_ln66_36_fu_1565_p2[0:0] == 1'b1) ? p_0_4_0_0_018928_fu_266 : trunc_ln247_4_fu_1142_p4);

assign select_ln0_25_fu_1591_p3 = ((xor_ln66_38_fu_1585_p2[0:0] == 1'b1) ? p_0_5_0_0_010314057_fu_326 : select_ln241_16_fu_1068_p3);

assign select_ln0_26_fu_1611_p3 = ((xor_ln66_39_fu_1605_p2[0:0] == 1'b1) ? p_0_5_0_0_019326_fu_262 : trunc_ln247_5_fu_1152_p4);

assign select_ln0_27_fu_1631_p3 = ((xor_ln66_41_fu_1625_p2[0:0] == 1'b1) ? p_0_6_0_0_010514355_fu_322 : select_ln241_15_fu_1060_p3);

assign select_ln0_28_fu_1651_p3 = ((xor_ln66_42_fu_1645_p2[0:0] == 1'b1) ? p_0_6_0_0_019724_fu_258 : trunc_ln247_6_fu_1162_p4);

assign select_ln0_29_fu_1671_p3 = ((xor_ln66_44_fu_1665_p2[0:0] == 1'b1) ? p_0_7_0_0_010714653_fu_318 : select_ln241_14_fu_1052_p3);

assign select_ln0_30_fu_1691_p3 = ((xor_ln66_45_fu_1685_p2[0:0] == 1'b1) ? p_0_7_0_0_020122_fu_254 : trunc_ln247_7_fu_1172_p4);

assign select_ln0_31_fu_1711_p3 = ((xor_ln66_47_fu_1705_p2[0:0] == 1'b1) ? p_0_8_0_0_010914951_fu_314 : select_ln241_13_fu_1044_p3);

assign select_ln0_32_fu_1731_p3 = ((xor_ln66_48_fu_1725_p2[0:0] == 1'b1) ? p_0_8_0_0_020520_fu_250 : trunc_ln247_8_fu_1182_p4);

assign select_ln0_33_fu_1751_p3 = ((xor_ln66_50_fu_1745_p2[0:0] == 1'b1) ? p_0_9_0_0_011115249_fu_310 : select_ln241_12_fu_1036_p3);

assign select_ln0_34_fu_1771_p3 = ((xor_ln66_51_fu_1765_p2[0:0] == 1'b1) ? p_0_9_0_0_020918_fu_246 : trunc_ln247_9_fu_1192_p4);

assign select_ln0_35_fu_1791_p3 = ((xor_ln66_53_fu_1785_p2[0:0] == 1'b1) ? p_0_10_0_0_011315547_fu_306 : select_ln241_11_fu_1028_p3);

assign select_ln0_36_fu_1811_p3 = ((xor_ln66_54_fu_1805_p2[0:0] == 1'b1) ? p_0_10_0_0_021316_fu_242 : trunc_ln247_s_fu_1202_p4);

assign select_ln0_37_fu_1831_p3 = ((xor_ln66_56_fu_1825_p2[0:0] == 1'b1) ? p_0_11_0_0_011515845_fu_302 : select_ln241_10_fu_1020_p3);

assign select_ln0_38_fu_1851_p3 = ((xor_ln66_57_fu_1845_p2[0:0] == 1'b1) ? p_0_11_0_0_021714_fu_238 : trunc_ln247_10_fu_1212_p4);

assign select_ln0_39_fu_1871_p3 = ((xor_ln66_59_fu_1865_p2[0:0] == 1'b1) ? p_0_12_0_0_011716143_fu_298 : select_ln241_9_fu_1012_p3);

assign select_ln0_40_fu_1891_p3 = ((xor_ln66_60_fu_1885_p2[0:0] == 1'b1) ? p_0_12_0_0_022112_fu_234 : trunc_ln247_11_fu_1222_p4);

assign select_ln0_41_fu_1911_p3 = ((xor_ln66_62_fu_1905_p2[0:0] == 1'b1) ? p_0_13_0_0_011916441_fu_294 : select_ln241_8_fu_1004_p3);

assign select_ln0_42_fu_1931_p3 = ((xor_ln66_63_fu_1925_p2[0:0] == 1'b1) ? p_0_13_0_0_022510_fu_230 : trunc_ln247_12_fu_1232_p4);

assign select_ln0_43_fu_1951_p3 = ((xor_ln66_65_fu_1945_p2[0:0] == 1'b1) ? p_0_14_0_0_012116739_fu_290 : select_ln241_7_fu_996_p3);

assign select_ln0_44_fu_1971_p3 = ((xor_ln66_66_fu_1965_p2[0:0] == 1'b1) ? p_0_14_0_0_02298_fu_226 : trunc_ln247_13_fu_1242_p4);

assign select_ln0_45_fu_1991_p3 = ((xor_ln66_68_fu_1985_p2[0:0] == 1'b1) ? p_0_15_0_0_012317037_fu_286 : select_ln241_fu_988_p3);

assign select_ln0_46_fu_2011_p3 = ((xor_ln66_69_fu_2005_p2[0:0] == 1'b1) ? p_0_15_0_0_02336_fu_222 : trunc_ln247_14_fu_1252_p4);

assign select_ln0_fu_1383_p3 = ((xor_ln66_fu_1377_p2[0:0] == 1'b1) ? p_0_0_0_0_09312567_fu_346 : ap_phi_mux_p_0_0_0_0_09384_phi_fu_441_p4);

assign select_ln222_fu_2107_p3 = ((icmp_ln222_fu_2095_p2[0:0] == 1'b1) ? 32'd0 : add_ln222_fu_2101_p2);

assign select_ln227_fu_2043_p3 = ((icmp_ln191_fu_1266_p2[0:0] == 1'b1) ? 32'd0 : add_ln227_fu_2037_p2);

assign select_ln24187_fu_1391_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0_0_09384_phi_fu_441_p4 : p_0_0_0_0_017336_fu_282);

assign select_ln241_10_fu_1020_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_11_0_0_021714_fu_238 : p_0_11_0_0_011573_fu_366);

assign select_ln241_11_fu_1028_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_10_0_0_021316_fu_242 : p_0_10_0_0_011374_fu_370);

assign select_ln241_12_fu_1036_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_9_0_0_020918_fu_246 : p_0_9_0_0_011175_fu_374);

assign select_ln241_13_fu_1044_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_8_0_0_020520_fu_250 : p_0_8_0_0_010976_fu_378);

assign select_ln241_14_fu_1052_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_7_0_0_020122_fu_254 : p_0_7_0_0_010777_fu_382);

assign select_ln241_15_fu_1060_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_6_0_0_019724_fu_258 : p_0_6_0_0_010578_fu_386);

assign select_ln241_16_fu_1068_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_5_0_0_019326_fu_262 : p_0_5_0_0_010379_fu_390);

assign select_ln241_17_fu_1076_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_4_0_0_018928_fu_266 : p_0_4_0_0_010180_fu_394);

assign select_ln241_18_fu_1084_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_3_0_0_018530_fu_270 : p_0_3_0_0_09981_fu_398);

assign select_ln241_19_fu_1092_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_2_0_0_018132_fu_274 : p_0_2_0_0_09782_fu_402);

assign select_ln241_20_fu_1100_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_1_0_0_017734_fu_278 : p_0_1_0_0_09583_fu_406);

assign select_ln241_7_fu_996_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_14_0_0_02298_fu_226 : p_0_14_0_0_012170_fu_354);

assign select_ln241_8_fu_1004_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_13_0_0_022510_fu_230 : p_0_13_0_0_011971_fu_358);

assign select_ln241_9_fu_1012_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_12_0_0_022112_fu_234 : p_0_12_0_0_011772_fu_362);

assign select_ln241_fu_988_p3 = ((ap_phi_mux_icmp_ln24386_phi_fu_431_p4[0:0] == 1'b1) ? p_0_15_0_0_02336_fu_222 : p_0_15_0_0_012369_fu_350);

assign start_out = real_start;

assign trunc_ln247_10_fu_1212_p4 = {{layer8_out_dout[95:88]}};

assign trunc_ln247_11_fu_1222_p4 = {{layer8_out_dout[103:96]}};

assign trunc_ln247_12_fu_1232_p4 = {{layer8_out_dout[111:104]}};

assign trunc_ln247_13_fu_1242_p4 = {{layer8_out_dout[119:112]}};

assign trunc_ln247_14_fu_1252_p4 = {{layer8_out_dout[127:120]}};

assign trunc_ln247_1_fu_1112_p4 = {{layer8_out_dout[15:8]}};

assign trunc_ln247_2_fu_1122_p4 = {{layer8_out_dout[23:16]}};

assign trunc_ln247_3_fu_1132_p4 = {{layer8_out_dout[31:24]}};

assign trunc_ln247_4_fu_1142_p4 = {{layer8_out_dout[39:32]}};

assign trunc_ln247_5_fu_1152_p4 = {{layer8_out_dout[47:40]}};

assign trunc_ln247_6_fu_1162_p4 = {{layer8_out_dout[55:48]}};

assign trunc_ln247_7_fu_1172_p4 = {{layer8_out_dout[63:56]}};

assign trunc_ln247_8_fu_1182_p4 = {{layer8_out_dout[71:64]}};

assign trunc_ln247_9_fu_1192_p4 = {{layer8_out_dout[79:72]}};

assign trunc_ln247_fu_1108_p1 = layer8_out_dout[7:0];

assign trunc_ln247_s_fu_1202_p4 = {{layer8_out_dout[87:80]}};

assign xor_ln66_24_fu_1405_p2 = (icmp_ln66_24_fu_1399_p2 ^ 1'd1);

assign xor_ln66_25_fu_2406_p2 = (icmp_ln66_25_fu_2402_p2 ^ 1'd1);

assign xor_ln66_26_fu_1425_p2 = (icmp_ln66_26_fu_1419_p2 ^ 1'd1);

assign xor_ln66_27_fu_1445_p2 = (icmp_ln66_27_fu_1439_p2 ^ 1'd1);

assign xor_ln66_28_fu_2422_p2 = (icmp_ln66_28_fu_2418_p2 ^ 1'd1);

assign xor_ln66_29_fu_1465_p2 = (icmp_ln66_29_fu_1459_p2 ^ 1'd1);

assign xor_ln66_30_fu_1485_p2 = (icmp_ln66_30_fu_1479_p2 ^ 1'd1);

assign xor_ln66_31_fu_2438_p2 = (icmp_ln66_31_fu_2434_p2 ^ 1'd1);

assign xor_ln66_32_fu_1505_p2 = (icmp_ln66_32_fu_1499_p2 ^ 1'd1);

assign xor_ln66_33_fu_1525_p2 = (icmp_ln66_33_fu_1519_p2 ^ 1'd1);

assign xor_ln66_34_fu_2454_p2 = (icmp_ln66_34_fu_2450_p2 ^ 1'd1);

assign xor_ln66_35_fu_1545_p2 = (icmp_ln66_35_fu_1539_p2 ^ 1'd1);

assign xor_ln66_36_fu_1565_p2 = (icmp_ln66_36_fu_1559_p2 ^ 1'd1);

assign xor_ln66_37_fu_2470_p2 = (icmp_ln66_37_fu_2466_p2 ^ 1'd1);

assign xor_ln66_38_fu_1585_p2 = (icmp_ln66_38_fu_1579_p2 ^ 1'd1);

assign xor_ln66_39_fu_1605_p2 = (icmp_ln66_39_fu_1599_p2 ^ 1'd1);

assign xor_ln66_40_fu_2486_p2 = (icmp_ln66_40_fu_2482_p2 ^ 1'd1);

assign xor_ln66_41_fu_1625_p2 = (icmp_ln66_41_fu_1619_p2 ^ 1'd1);

assign xor_ln66_42_fu_1645_p2 = (icmp_ln66_42_fu_1639_p2 ^ 1'd1);

assign xor_ln66_43_fu_2502_p2 = (icmp_ln66_43_fu_2498_p2 ^ 1'd1);

assign xor_ln66_44_fu_1665_p2 = (icmp_ln66_44_fu_1659_p2 ^ 1'd1);

assign xor_ln66_45_fu_1685_p2 = (icmp_ln66_45_fu_1679_p2 ^ 1'd1);

assign xor_ln66_46_fu_2518_p2 = (icmp_ln66_46_fu_2514_p2 ^ 1'd1);

assign xor_ln66_47_fu_1705_p2 = (icmp_ln66_47_fu_1699_p2 ^ 1'd1);

assign xor_ln66_48_fu_1725_p2 = (icmp_ln66_48_fu_1719_p2 ^ 1'd1);

assign xor_ln66_49_fu_2534_p2 = (icmp_ln66_49_fu_2530_p2 ^ 1'd1);

assign xor_ln66_50_fu_1745_p2 = (icmp_ln66_50_fu_1739_p2 ^ 1'd1);

assign xor_ln66_51_fu_1765_p2 = (icmp_ln66_51_fu_1759_p2 ^ 1'd1);

assign xor_ln66_52_fu_2550_p2 = (icmp_ln66_52_fu_2546_p2 ^ 1'd1);

assign xor_ln66_53_fu_1785_p2 = (icmp_ln66_53_fu_1779_p2 ^ 1'd1);

assign xor_ln66_54_fu_1805_p2 = (icmp_ln66_54_fu_1799_p2 ^ 1'd1);

assign xor_ln66_55_fu_2566_p2 = (icmp_ln66_55_fu_2562_p2 ^ 1'd1);

assign xor_ln66_56_fu_1825_p2 = (icmp_ln66_56_fu_1819_p2 ^ 1'd1);

assign xor_ln66_57_fu_1845_p2 = (icmp_ln66_57_fu_1839_p2 ^ 1'd1);

assign xor_ln66_58_fu_2582_p2 = (icmp_ln66_58_fu_2578_p2 ^ 1'd1);

assign xor_ln66_59_fu_1865_p2 = (icmp_ln66_59_fu_1859_p2 ^ 1'd1);

assign xor_ln66_60_fu_1885_p2 = (icmp_ln66_60_fu_1879_p2 ^ 1'd1);

assign xor_ln66_61_fu_2598_p2 = (icmp_ln66_61_fu_2594_p2 ^ 1'd1);

assign xor_ln66_62_fu_1905_p2 = (icmp_ln66_62_fu_1899_p2 ^ 1'd1);

assign xor_ln66_63_fu_1925_p2 = (icmp_ln66_63_fu_1919_p2 ^ 1'd1);

assign xor_ln66_64_fu_2614_p2 = (icmp_ln66_64_fu_2610_p2 ^ 1'd1);

assign xor_ln66_65_fu_1945_p2 = (icmp_ln66_65_fu_1939_p2 ^ 1'd1);

assign xor_ln66_66_fu_1965_p2 = (icmp_ln66_66_fu_1959_p2 ^ 1'd1);

assign xor_ln66_67_fu_2630_p2 = (icmp_ln66_67_fu_2626_p2 ^ 1'd1);

assign xor_ln66_68_fu_1985_p2 = (icmp_ln66_68_fu_1979_p2 ^ 1'd1);

assign xor_ln66_69_fu_2005_p2 = (icmp_ln66_69_fu_1999_p2 ^ 1'd1);

assign xor_ln66_70_fu_2646_p2 = (icmp_ln66_70_fu_2642_p2 ^ 1'd1);

assign xor_ln66_fu_1377_p2 = (icmp_ln66_fu_1371_p2 ^ 1'd1);

endmodule //myproject_pooling2d_cl_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_config9_s
