// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer11_out_dout,
        layer11_out_empty_n,
        layer11_out_read,
        layer11_out_num_data_valid,
        layer11_out_fifo_cap,
        layer12_out_din,
        layer12_out_full_n,
        layer12_out_write,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [831:0] layer11_out_dout;
input   layer11_out_empty_n;
output   layer11_out_read;
input  [1:0] layer11_out_num_data_valid;
input  [1:0] layer11_out_fifo_cap;
output  [255:0] layer12_out_din;
input   layer12_out_full_n;
output   layer12_out_write;
input  [1:0] layer12_out_num_data_valid;
input  [1:0] layer12_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer11_out_read;
reg layer12_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer11_out_blk_n;
reg    layer12_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [7:0] select_ln51_fu_623_p3;
reg   [7:0] select_ln51_reg_1412;
reg    ap_block_state1;
wire   [7:0] select_ln51_1_fu_647_p3;
reg   [7:0] select_ln51_1_reg_1417;
wire   [7:0] select_ln51_2_fu_671_p3;
reg   [7:0] select_ln51_2_reg_1422;
wire   [7:0] select_ln51_3_fu_695_p3;
reg   [7:0] select_ln51_3_reg_1427;
wire   [7:0] select_ln51_4_fu_719_p3;
reg   [7:0] select_ln51_4_reg_1432;
wire   [7:0] select_ln51_5_fu_743_p3;
reg   [7:0] select_ln51_5_reg_1437;
wire   [7:0] select_ln51_6_fu_767_p3;
reg   [7:0] select_ln51_6_reg_1442;
wire   [7:0] select_ln51_7_fu_791_p3;
reg   [7:0] select_ln51_7_reg_1447;
wire   [7:0] select_ln51_8_fu_815_p3;
reg   [7:0] select_ln51_8_reg_1452;
wire   [7:0] select_ln51_9_fu_839_p3;
reg   [7:0] select_ln51_9_reg_1457;
wire   [7:0] select_ln51_10_fu_863_p3;
reg   [7:0] select_ln51_10_reg_1462;
wire   [7:0] select_ln51_11_fu_887_p3;
reg   [7:0] select_ln51_11_reg_1467;
wire   [7:0] select_ln51_12_fu_911_p3;
reg   [7:0] select_ln51_12_reg_1472;
wire   [7:0] select_ln51_13_fu_935_p3;
reg   [7:0] select_ln51_13_reg_1477;
wire   [7:0] select_ln51_14_fu_959_p3;
reg   [7:0] select_ln51_14_reg_1482;
wire   [7:0] select_ln51_15_fu_983_p3;
reg   [7:0] select_ln51_15_reg_1487;
wire   [7:0] select_ln51_16_fu_1007_p3;
reg   [7:0] select_ln51_16_reg_1492;
wire   [7:0] select_ln51_17_fu_1031_p3;
reg   [7:0] select_ln51_17_reg_1497;
wire   [7:0] select_ln51_18_fu_1055_p3;
reg   [7:0] select_ln51_18_reg_1502;
wire   [7:0] select_ln51_19_fu_1079_p3;
reg   [7:0] select_ln51_19_reg_1507;
wire   [7:0] select_ln51_20_fu_1103_p3;
reg   [7:0] select_ln51_20_reg_1512;
wire   [7:0] select_ln51_21_fu_1127_p3;
reg   [7:0] select_ln51_21_reg_1517;
wire   [7:0] select_ln51_22_fu_1151_p3;
reg   [7:0] select_ln51_22_reg_1522;
wire   [7:0] select_ln51_23_fu_1175_p3;
reg   [7:0] select_ln51_23_reg_1527;
wire   [7:0] select_ln51_24_fu_1199_p3;
reg   [7:0] select_ln51_24_reg_1532;
wire   [7:0] select_ln51_25_fu_1223_p3;
reg   [7:0] select_ln51_25_reg_1537;
wire   [7:0] select_ln51_26_fu_1247_p3;
reg   [7:0] select_ln51_26_reg_1542;
wire   [7:0] select_ln51_27_fu_1271_p3;
reg   [7:0] select_ln51_27_reg_1547;
wire   [7:0] select_ln51_28_fu_1295_p3;
reg   [7:0] select_ln51_28_reg_1552;
wire   [7:0] select_ln51_29_fu_1319_p3;
reg   [7:0] select_ln51_29_reg_1557;
wire   [7:0] select_ln51_30_fu_1343_p3;
reg   [7:0] select_ln51_30_reg_1562;
wire   [7:0] select_ln51_31_fu_1367_p3;
reg   [7:0] select_ln51_31_reg_1567;
wire   [25:0] trunc_ln44_fu_293_p1;
wire   [0:0] icmp_ln51_fu_607_p2;
wire   [7:0] trunc_ln2_fu_613_p4;
wire   [25:0] trunc_ln44_1_fu_297_p4;
wire   [0:0] icmp_ln51_1_fu_631_p2;
wire   [7:0] trunc_ln52_1_fu_637_p4;
wire   [25:0] trunc_ln44_2_fu_307_p4;
wire   [0:0] icmp_ln51_2_fu_655_p2;
wire   [7:0] trunc_ln52_2_fu_661_p4;
wire   [25:0] trunc_ln44_3_fu_317_p4;
wire   [0:0] icmp_ln51_3_fu_679_p2;
wire   [7:0] trunc_ln52_3_fu_685_p4;
wire   [25:0] trunc_ln44_4_fu_327_p4;
wire   [0:0] icmp_ln51_4_fu_703_p2;
wire   [7:0] trunc_ln52_4_fu_709_p4;
wire   [25:0] trunc_ln44_5_fu_337_p4;
wire   [0:0] icmp_ln51_5_fu_727_p2;
wire   [7:0] trunc_ln52_5_fu_733_p4;
wire   [25:0] trunc_ln44_6_fu_347_p4;
wire   [0:0] icmp_ln51_6_fu_751_p2;
wire   [7:0] trunc_ln52_6_fu_757_p4;
wire   [25:0] trunc_ln44_7_fu_357_p4;
wire   [0:0] icmp_ln51_7_fu_775_p2;
wire   [7:0] trunc_ln52_7_fu_781_p4;
wire   [25:0] trunc_ln44_8_fu_367_p4;
wire   [0:0] icmp_ln51_8_fu_799_p2;
wire   [7:0] trunc_ln52_8_fu_805_p4;
wire   [25:0] trunc_ln44_9_fu_377_p4;
wire   [0:0] icmp_ln51_9_fu_823_p2;
wire   [7:0] trunc_ln52_9_fu_829_p4;
wire   [25:0] trunc_ln44_s_fu_387_p4;
wire   [0:0] icmp_ln51_10_fu_847_p2;
wire   [7:0] trunc_ln52_s_fu_853_p4;
wire   [25:0] trunc_ln44_10_fu_397_p4;
wire   [0:0] icmp_ln51_11_fu_871_p2;
wire   [7:0] trunc_ln52_10_fu_877_p4;
wire   [25:0] trunc_ln44_11_fu_407_p4;
wire   [0:0] icmp_ln51_12_fu_895_p2;
wire   [7:0] trunc_ln52_11_fu_901_p4;
wire   [25:0] trunc_ln44_12_fu_417_p4;
wire   [0:0] icmp_ln51_13_fu_919_p2;
wire   [7:0] trunc_ln52_12_fu_925_p4;
wire   [25:0] trunc_ln44_13_fu_427_p4;
wire   [0:0] icmp_ln51_14_fu_943_p2;
wire   [7:0] trunc_ln52_13_fu_949_p4;
wire   [25:0] trunc_ln44_14_fu_437_p4;
wire   [0:0] icmp_ln51_15_fu_967_p2;
wire   [7:0] trunc_ln52_14_fu_973_p4;
wire   [25:0] trunc_ln44_15_fu_447_p4;
wire   [0:0] icmp_ln51_16_fu_991_p2;
wire   [7:0] trunc_ln52_15_fu_997_p4;
wire   [25:0] trunc_ln44_16_fu_457_p4;
wire   [0:0] icmp_ln51_17_fu_1015_p2;
wire   [7:0] trunc_ln52_16_fu_1021_p4;
wire   [25:0] trunc_ln44_17_fu_467_p4;
wire   [0:0] icmp_ln51_18_fu_1039_p2;
wire   [7:0] trunc_ln52_17_fu_1045_p4;
wire   [25:0] trunc_ln44_18_fu_477_p4;
wire   [0:0] icmp_ln51_19_fu_1063_p2;
wire   [7:0] trunc_ln52_18_fu_1069_p4;
wire   [25:0] trunc_ln44_19_fu_487_p4;
wire   [0:0] icmp_ln51_20_fu_1087_p2;
wire   [7:0] trunc_ln52_19_fu_1093_p4;
wire   [25:0] trunc_ln44_20_fu_497_p4;
wire   [0:0] icmp_ln51_21_fu_1111_p2;
wire   [7:0] trunc_ln52_20_fu_1117_p4;
wire   [25:0] trunc_ln44_21_fu_507_p4;
wire   [0:0] icmp_ln51_22_fu_1135_p2;
wire   [7:0] trunc_ln52_21_fu_1141_p4;
wire   [25:0] trunc_ln44_22_fu_517_p4;
wire   [0:0] icmp_ln51_23_fu_1159_p2;
wire   [7:0] trunc_ln52_22_fu_1165_p4;
wire   [25:0] trunc_ln44_23_fu_527_p4;
wire   [0:0] icmp_ln51_24_fu_1183_p2;
wire   [7:0] trunc_ln52_23_fu_1189_p4;
wire   [25:0] trunc_ln44_24_fu_537_p4;
wire   [0:0] icmp_ln51_25_fu_1207_p2;
wire   [7:0] trunc_ln52_24_fu_1213_p4;
wire   [25:0] trunc_ln44_25_fu_547_p4;
wire   [0:0] icmp_ln51_26_fu_1231_p2;
wire   [7:0] trunc_ln52_25_fu_1237_p4;
wire   [25:0] trunc_ln44_26_fu_557_p4;
wire   [0:0] icmp_ln51_27_fu_1255_p2;
wire   [7:0] trunc_ln52_26_fu_1261_p4;
wire   [25:0] trunc_ln44_27_fu_567_p4;
wire   [0:0] icmp_ln51_28_fu_1279_p2;
wire   [7:0] trunc_ln52_27_fu_1285_p4;
wire   [25:0] trunc_ln44_28_fu_577_p4;
wire   [0:0] icmp_ln51_29_fu_1303_p2;
wire   [7:0] trunc_ln52_28_fu_1309_p4;
wire   [25:0] trunc_ln44_29_fu_587_p4;
wire   [0:0] icmp_ln51_30_fu_1327_p2;
wire   [7:0] trunc_ln52_29_fu_1333_p4;
wire   [25:0] trunc_ln44_30_fu_597_p4;
wire   [0:0] icmp_ln51_31_fu_1351_p2;
wire   [7:0] trunc_ln52_30_fu_1357_p4;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer12_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        select_ln51_10_reg_1462 <= select_ln51_10_fu_863_p3;
        select_ln51_11_reg_1467 <= select_ln51_11_fu_887_p3;
        select_ln51_12_reg_1472 <= select_ln51_12_fu_911_p3;
        select_ln51_13_reg_1477 <= select_ln51_13_fu_935_p3;
        select_ln51_14_reg_1482 <= select_ln51_14_fu_959_p3;
        select_ln51_15_reg_1487 <= select_ln51_15_fu_983_p3;
        select_ln51_16_reg_1492 <= select_ln51_16_fu_1007_p3;
        select_ln51_17_reg_1497 <= select_ln51_17_fu_1031_p3;
        select_ln51_18_reg_1502 <= select_ln51_18_fu_1055_p3;
        select_ln51_19_reg_1507 <= select_ln51_19_fu_1079_p3;
        select_ln51_1_reg_1417 <= select_ln51_1_fu_647_p3;
        select_ln51_20_reg_1512 <= select_ln51_20_fu_1103_p3;
        select_ln51_21_reg_1517 <= select_ln51_21_fu_1127_p3;
        select_ln51_22_reg_1522 <= select_ln51_22_fu_1151_p3;
        select_ln51_23_reg_1527 <= select_ln51_23_fu_1175_p3;
        select_ln51_24_reg_1532 <= select_ln51_24_fu_1199_p3;
        select_ln51_25_reg_1537 <= select_ln51_25_fu_1223_p3;
        select_ln51_26_reg_1542 <= select_ln51_26_fu_1247_p3;
        select_ln51_27_reg_1547 <= select_ln51_27_fu_1271_p3;
        select_ln51_28_reg_1552 <= select_ln51_28_fu_1295_p3;
        select_ln51_29_reg_1557 <= select_ln51_29_fu_1319_p3;
        select_ln51_2_reg_1422 <= select_ln51_2_fu_671_p3;
        select_ln51_30_reg_1562 <= select_ln51_30_fu_1343_p3;
        select_ln51_31_reg_1567 <= select_ln51_31_fu_1367_p3;
        select_ln51_3_reg_1427 <= select_ln51_3_fu_695_p3;
        select_ln51_4_reg_1432 <= select_ln51_4_fu_719_p3;
        select_ln51_5_reg_1437 <= select_ln51_5_fu_743_p3;
        select_ln51_6_reg_1442 <= select_ln51_6_fu_767_p3;
        select_ln51_7_reg_1447 <= select_ln51_7_fu_791_p3;
        select_ln51_8_reg_1452 <= select_ln51_8_fu_815_p3;
        select_ln51_9_reg_1457 <= select_ln51_9_fu_839_p3;
        select_ln51_reg_1412 <= select_ln51_fu_623_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer12_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer12_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer12_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_blk_n = layer11_out_empty_n;
    end else begin
        layer11_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_read = 1'b1;
    end else begin
        layer11_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer12_out_blk_n = layer12_out_full_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer12_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer12_out_write = 1'b1;
    end else begin
        layer12_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer12_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer11_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_10_fu_847_p2 = (($signed(trunc_ln44_s_fu_387_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_871_p2 = (($signed(trunc_ln44_10_fu_397_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_895_p2 = (($signed(trunc_ln44_11_fu_407_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_919_p2 = (($signed(trunc_ln44_12_fu_417_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_943_p2 = (($signed(trunc_ln44_13_fu_427_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_967_p2 = (($signed(trunc_ln44_14_fu_437_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_991_p2 = (($signed(trunc_ln44_15_fu_447_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_1015_p2 = (($signed(trunc_ln44_16_fu_457_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_1039_p2 = (($signed(trunc_ln44_17_fu_467_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_1063_p2 = (($signed(trunc_ln44_18_fu_477_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_631_p2 = (($signed(trunc_ln44_1_fu_297_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_1087_p2 = (($signed(trunc_ln44_19_fu_487_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_1111_p2 = (($signed(trunc_ln44_20_fu_497_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_1135_p2 = (($signed(trunc_ln44_21_fu_507_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_1159_p2 = (($signed(trunc_ln44_22_fu_517_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_1183_p2 = (($signed(trunc_ln44_23_fu_527_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_1207_p2 = (($signed(trunc_ln44_24_fu_537_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_1231_p2 = (($signed(trunc_ln44_25_fu_547_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_1255_p2 = (($signed(trunc_ln44_26_fu_557_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_1279_p2 = (($signed(trunc_ln44_27_fu_567_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_1303_p2 = (($signed(trunc_ln44_28_fu_577_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_655_p2 = (($signed(trunc_ln44_2_fu_307_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_1327_p2 = (($signed(trunc_ln44_29_fu_587_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_1351_p2 = (($signed(trunc_ln44_30_fu_597_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_679_p2 = (($signed(trunc_ln44_3_fu_317_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_703_p2 = (($signed(trunc_ln44_4_fu_327_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_727_p2 = (($signed(trunc_ln44_5_fu_337_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_751_p2 = (($signed(trunc_ln44_6_fu_347_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_775_p2 = (($signed(trunc_ln44_7_fu_357_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_799_p2 = (($signed(trunc_ln44_8_fu_367_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_823_p2 = (($signed(trunc_ln44_9_fu_377_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_607_p2 = (($signed(trunc_ln44_fu_293_p1) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign layer12_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_31_reg_1567}, {select_ln51_30_reg_1562}}, {select_ln51_29_reg_1557}}, {select_ln51_28_reg_1552}}, {select_ln51_27_reg_1547}}, {select_ln51_26_reg_1542}}, {select_ln51_25_reg_1537}}, {select_ln51_24_reg_1532}}, {select_ln51_23_reg_1527}}, {select_ln51_22_reg_1522}}, {select_ln51_21_reg_1517}}, {select_ln51_20_reg_1512}}, {select_ln51_19_reg_1507}}, {select_ln51_18_reg_1502}}, {select_ln51_17_reg_1497}}, {select_ln51_16_reg_1492}}, {select_ln51_15_reg_1487}}, {select_ln51_14_reg_1482}}, {select_ln51_13_reg_1477}}, {select_ln51_12_reg_1472}}, {select_ln51_11_reg_1467}}, {select_ln51_10_reg_1462}}, {select_ln51_9_reg_1457}}, {select_ln51_8_reg_1452}}, {select_ln51_7_reg_1447}}, {select_ln51_6_reg_1442}}, {select_ln51_5_reg_1437}}, {select_ln51_4_reg_1432}}, {select_ln51_3_reg_1427}}, {select_ln51_2_reg_1422}}, {select_ln51_1_reg_1417}}, {select_ln51_reg_1412}};

assign select_ln51_10_fu_863_p3 = ((icmp_ln51_10_fu_847_p2[0:0] == 1'b1) ? trunc_ln52_s_fu_853_p4 : 8'd0);

assign select_ln51_11_fu_887_p3 = ((icmp_ln51_11_fu_871_p2[0:0] == 1'b1) ? trunc_ln52_10_fu_877_p4 : 8'd0);

assign select_ln51_12_fu_911_p3 = ((icmp_ln51_12_fu_895_p2[0:0] == 1'b1) ? trunc_ln52_11_fu_901_p4 : 8'd0);

assign select_ln51_13_fu_935_p3 = ((icmp_ln51_13_fu_919_p2[0:0] == 1'b1) ? trunc_ln52_12_fu_925_p4 : 8'd0);

assign select_ln51_14_fu_959_p3 = ((icmp_ln51_14_fu_943_p2[0:0] == 1'b1) ? trunc_ln52_13_fu_949_p4 : 8'd0);

assign select_ln51_15_fu_983_p3 = ((icmp_ln51_15_fu_967_p2[0:0] == 1'b1) ? trunc_ln52_14_fu_973_p4 : 8'd0);

assign select_ln51_16_fu_1007_p3 = ((icmp_ln51_16_fu_991_p2[0:0] == 1'b1) ? trunc_ln52_15_fu_997_p4 : 8'd0);

assign select_ln51_17_fu_1031_p3 = ((icmp_ln51_17_fu_1015_p2[0:0] == 1'b1) ? trunc_ln52_16_fu_1021_p4 : 8'd0);

assign select_ln51_18_fu_1055_p3 = ((icmp_ln51_18_fu_1039_p2[0:0] == 1'b1) ? trunc_ln52_17_fu_1045_p4 : 8'd0);

assign select_ln51_19_fu_1079_p3 = ((icmp_ln51_19_fu_1063_p2[0:0] == 1'b1) ? trunc_ln52_18_fu_1069_p4 : 8'd0);

assign select_ln51_1_fu_647_p3 = ((icmp_ln51_1_fu_631_p2[0:0] == 1'b1) ? trunc_ln52_1_fu_637_p4 : 8'd0);

assign select_ln51_20_fu_1103_p3 = ((icmp_ln51_20_fu_1087_p2[0:0] == 1'b1) ? trunc_ln52_19_fu_1093_p4 : 8'd0);

assign select_ln51_21_fu_1127_p3 = ((icmp_ln51_21_fu_1111_p2[0:0] == 1'b1) ? trunc_ln52_20_fu_1117_p4 : 8'd0);

assign select_ln51_22_fu_1151_p3 = ((icmp_ln51_22_fu_1135_p2[0:0] == 1'b1) ? trunc_ln52_21_fu_1141_p4 : 8'd0);

assign select_ln51_23_fu_1175_p3 = ((icmp_ln51_23_fu_1159_p2[0:0] == 1'b1) ? trunc_ln52_22_fu_1165_p4 : 8'd0);

assign select_ln51_24_fu_1199_p3 = ((icmp_ln51_24_fu_1183_p2[0:0] == 1'b1) ? trunc_ln52_23_fu_1189_p4 : 8'd0);

assign select_ln51_25_fu_1223_p3 = ((icmp_ln51_25_fu_1207_p2[0:0] == 1'b1) ? trunc_ln52_24_fu_1213_p4 : 8'd0);

assign select_ln51_26_fu_1247_p3 = ((icmp_ln51_26_fu_1231_p2[0:0] == 1'b1) ? trunc_ln52_25_fu_1237_p4 : 8'd0);

assign select_ln51_27_fu_1271_p3 = ((icmp_ln51_27_fu_1255_p2[0:0] == 1'b1) ? trunc_ln52_26_fu_1261_p4 : 8'd0);

assign select_ln51_28_fu_1295_p3 = ((icmp_ln51_28_fu_1279_p2[0:0] == 1'b1) ? trunc_ln52_27_fu_1285_p4 : 8'd0);

assign select_ln51_29_fu_1319_p3 = ((icmp_ln51_29_fu_1303_p2[0:0] == 1'b1) ? trunc_ln52_28_fu_1309_p4 : 8'd0);

assign select_ln51_2_fu_671_p3 = ((icmp_ln51_2_fu_655_p2[0:0] == 1'b1) ? trunc_ln52_2_fu_661_p4 : 8'd0);

assign select_ln51_30_fu_1343_p3 = ((icmp_ln51_30_fu_1327_p2[0:0] == 1'b1) ? trunc_ln52_29_fu_1333_p4 : 8'd0);

assign select_ln51_31_fu_1367_p3 = ((icmp_ln51_31_fu_1351_p2[0:0] == 1'b1) ? trunc_ln52_30_fu_1357_p4 : 8'd0);

assign select_ln51_3_fu_695_p3 = ((icmp_ln51_3_fu_679_p2[0:0] == 1'b1) ? trunc_ln52_3_fu_685_p4 : 8'd0);

assign select_ln51_4_fu_719_p3 = ((icmp_ln51_4_fu_703_p2[0:0] == 1'b1) ? trunc_ln52_4_fu_709_p4 : 8'd0);

assign select_ln51_5_fu_743_p3 = ((icmp_ln51_5_fu_727_p2[0:0] == 1'b1) ? trunc_ln52_5_fu_733_p4 : 8'd0);

assign select_ln51_6_fu_767_p3 = ((icmp_ln51_6_fu_751_p2[0:0] == 1'b1) ? trunc_ln52_6_fu_757_p4 : 8'd0);

assign select_ln51_7_fu_791_p3 = ((icmp_ln51_7_fu_775_p2[0:0] == 1'b1) ? trunc_ln52_7_fu_781_p4 : 8'd0);

assign select_ln51_8_fu_815_p3 = ((icmp_ln51_8_fu_799_p2[0:0] == 1'b1) ? trunc_ln52_8_fu_805_p4 : 8'd0);

assign select_ln51_9_fu_839_p3 = ((icmp_ln51_9_fu_823_p2[0:0] == 1'b1) ? trunc_ln52_9_fu_829_p4 : 8'd0);

assign select_ln51_fu_623_p3 = ((icmp_ln51_fu_607_p2[0:0] == 1'b1) ? trunc_ln2_fu_613_p4 : 8'd0);

assign start_out = real_start;

assign trunc_ln2_fu_613_p4 = {{layer11_out_dout[12:5]}};

assign trunc_ln44_10_fu_397_p4 = {{layer11_out_dout[311:286]}};

assign trunc_ln44_11_fu_407_p4 = {{layer11_out_dout[337:312]}};

assign trunc_ln44_12_fu_417_p4 = {{layer11_out_dout[363:338]}};

assign trunc_ln44_13_fu_427_p4 = {{layer11_out_dout[389:364]}};

assign trunc_ln44_14_fu_437_p4 = {{layer11_out_dout[415:390]}};

assign trunc_ln44_15_fu_447_p4 = {{layer11_out_dout[441:416]}};

assign trunc_ln44_16_fu_457_p4 = {{layer11_out_dout[467:442]}};

assign trunc_ln44_17_fu_467_p4 = {{layer11_out_dout[493:468]}};

assign trunc_ln44_18_fu_477_p4 = {{layer11_out_dout[519:494]}};

assign trunc_ln44_19_fu_487_p4 = {{layer11_out_dout[545:520]}};

assign trunc_ln44_1_fu_297_p4 = {{layer11_out_dout[51:26]}};

assign trunc_ln44_20_fu_497_p4 = {{layer11_out_dout[571:546]}};

assign trunc_ln44_21_fu_507_p4 = {{layer11_out_dout[597:572]}};

assign trunc_ln44_22_fu_517_p4 = {{layer11_out_dout[623:598]}};

assign trunc_ln44_23_fu_527_p4 = {{layer11_out_dout[649:624]}};

assign trunc_ln44_24_fu_537_p4 = {{layer11_out_dout[675:650]}};

assign trunc_ln44_25_fu_547_p4 = {{layer11_out_dout[701:676]}};

assign trunc_ln44_26_fu_557_p4 = {{layer11_out_dout[727:702]}};

assign trunc_ln44_27_fu_567_p4 = {{layer11_out_dout[753:728]}};

assign trunc_ln44_28_fu_577_p4 = {{layer11_out_dout[779:754]}};

assign trunc_ln44_29_fu_587_p4 = {{layer11_out_dout[805:780]}};

assign trunc_ln44_2_fu_307_p4 = {{layer11_out_dout[77:52]}};

assign trunc_ln44_30_fu_597_p4 = {{layer11_out_dout[831:806]}};

assign trunc_ln44_3_fu_317_p4 = {{layer11_out_dout[103:78]}};

assign trunc_ln44_4_fu_327_p4 = {{layer11_out_dout[129:104]}};

assign trunc_ln44_5_fu_337_p4 = {{layer11_out_dout[155:130]}};

assign trunc_ln44_6_fu_347_p4 = {{layer11_out_dout[181:156]}};

assign trunc_ln44_7_fu_357_p4 = {{layer11_out_dout[207:182]}};

assign trunc_ln44_8_fu_367_p4 = {{layer11_out_dout[233:208]}};

assign trunc_ln44_9_fu_377_p4 = {{layer11_out_dout[259:234]}};

assign trunc_ln44_fu_293_p1 = layer11_out_dout[25:0];

assign trunc_ln44_s_fu_387_p4 = {{layer11_out_dout[285:260]}};

assign trunc_ln52_10_fu_877_p4 = {{layer11_out_dout[298:291]}};

assign trunc_ln52_11_fu_901_p4 = {{layer11_out_dout[324:317]}};

assign trunc_ln52_12_fu_925_p4 = {{layer11_out_dout[350:343]}};

assign trunc_ln52_13_fu_949_p4 = {{layer11_out_dout[376:369]}};

assign trunc_ln52_14_fu_973_p4 = {{layer11_out_dout[402:395]}};

assign trunc_ln52_15_fu_997_p4 = {{layer11_out_dout[428:421]}};

assign trunc_ln52_16_fu_1021_p4 = {{layer11_out_dout[454:447]}};

assign trunc_ln52_17_fu_1045_p4 = {{layer11_out_dout[480:473]}};

assign trunc_ln52_18_fu_1069_p4 = {{layer11_out_dout[506:499]}};

assign trunc_ln52_19_fu_1093_p4 = {{layer11_out_dout[532:525]}};

assign trunc_ln52_1_fu_637_p4 = {{layer11_out_dout[38:31]}};

assign trunc_ln52_20_fu_1117_p4 = {{layer11_out_dout[558:551]}};

assign trunc_ln52_21_fu_1141_p4 = {{layer11_out_dout[584:577]}};

assign trunc_ln52_22_fu_1165_p4 = {{layer11_out_dout[610:603]}};

assign trunc_ln52_23_fu_1189_p4 = {{layer11_out_dout[636:629]}};

assign trunc_ln52_24_fu_1213_p4 = {{layer11_out_dout[662:655]}};

assign trunc_ln52_25_fu_1237_p4 = {{layer11_out_dout[688:681]}};

assign trunc_ln52_26_fu_1261_p4 = {{layer11_out_dout[714:707]}};

assign trunc_ln52_27_fu_1285_p4 = {{layer11_out_dout[740:733]}};

assign trunc_ln52_28_fu_1309_p4 = {{layer11_out_dout[766:759]}};

assign trunc_ln52_29_fu_1333_p4 = {{layer11_out_dout[792:785]}};

assign trunc_ln52_2_fu_661_p4 = {{layer11_out_dout[64:57]}};

assign trunc_ln52_30_fu_1357_p4 = {{layer11_out_dout[818:811]}};

assign trunc_ln52_3_fu_685_p4 = {{layer11_out_dout[90:83]}};

assign trunc_ln52_4_fu_709_p4 = {{layer11_out_dout[116:109]}};

assign trunc_ln52_5_fu_733_p4 = {{layer11_out_dout[142:135]}};

assign trunc_ln52_6_fu_757_p4 = {{layer11_out_dout[168:161]}};

assign trunc_ln52_7_fu_781_p4 = {{layer11_out_dout[194:187]}};

assign trunc_ln52_8_fu_805_p4 = {{layer11_out_dout[220:213]}};

assign trunc_ln52_9_fu_829_p4 = {{layer11_out_dout[246:239]}};

assign trunc_ln52_s_fu_853_p4 = {{layer11_out_dout[272:265]}};

endmodule //myproject_relu_array_ap_fixed_32u_array_ap_fixed_8_3_5_3_0_32u_relu_config12_s
