// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;
input  [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;
output  [20:0] ap_return_0;
output  [20:0] ap_return_1;
output  [20:0] ap_return_2;
output  [20:0] ap_return_3;
output  [20:0] ap_return_4;
output  [20:0] ap_return_5;
output  [20:0] ap_return_6;
output  [20:0] ap_return_7;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [12:0] mul_ln73_1_fu_99_p2;
reg   [12:0] mul_ln73_1_reg_873;
wire   [13:0] mul_ln73_2_fu_108_p2;
reg   [13:0] mul_ln73_2_reg_877;
wire   [12:0] mul_ln73_3_fu_105_p2;
reg   [12:0] mul_ln73_3_reg_881;
wire   [12:0] mul_ln73_4_fu_100_p2;
reg   [12:0] mul_ln73_4_reg_885;
wire   [12:0] mul_ln73_5_fu_109_p2;
reg   [12:0] mul_ln73_5_reg_889;
wire   [12:0] mul_ln73_6_fu_94_p2;
reg   [12:0] mul_ln73_6_reg_893;
wire   [12:0] mul_ln73_7_fu_97_p2;
reg   [12:0] mul_ln73_7_reg_897;
wire  signed [13:0] mul_ln73_8_fu_104_p2;
reg  signed [13:0] mul_ln73_8_reg_901;
wire   [13:0] mul_ln73_9_fu_92_p2;
reg   [13:0] mul_ln73_9_reg_905;
reg  signed [7:0] a_reg_2461;
reg  signed [7:0] a_125_reg_2466;
wire  signed [8:0] tmp_952_fu_975_p3;
reg  signed [8:0] tmp_952_reg_2472;
reg  signed [7:0] a_126_reg_2477;
wire  signed [11:0] sub_ln73_1850_fu_1018_p2;
reg  signed [11:0] sub_ln73_1850_reg_2482;
reg  signed [7:0] a_127_reg_2488;
reg  signed [7:0] a_128_reg_2497;
reg  signed [7:0] a_129_reg_2506;
wire  signed [12:0] sext_ln70_1614_fu_1080_p1;
reg  signed [12:0] sext_ln70_1614_reg_2513;
wire  signed [9:0] tmp_964_fu_1085_p3;
reg  signed [9:0] tmp_964_reg_2518;
reg  signed [7:0] a_130_reg_2524;
reg  signed [7:0] a_131_reg_2533;
wire  signed [9:0] tmp_971_fu_1145_p3;
reg  signed [9:0] tmp_971_reg_2541;
wire   [10:0] sub_ln73_1873_fu_1157_p2;
reg   [10:0] sub_ln73_1873_reg_2546;
reg  signed [7:0] a_132_reg_2551;
wire   [11:0] add_ln58_7731_fu_1172_p2;
reg   [11:0] add_ln58_7731_reg_2561;
wire   [11:0] add_ln58_7732_fu_1178_p2;
reg   [11:0] add_ln58_7732_reg_2567;
wire   [11:0] sub_ln58_3111_fu_1184_p2;
reg   [11:0] sub_ln58_3111_reg_2572;
wire   [11:0] add_ln58_7734_fu_1200_p2;
reg   [11:0] add_ln58_7734_reg_2577;
wire   [10:0] add_ln58_7735_fu_1216_p2;
reg   [10:0] add_ln58_7735_reg_2582;
wire   [11:0] add_ln58_7738_fu_1232_p2;
reg   [11:0] add_ln58_7738_reg_2587;
wire   [10:0] add_ln58_7745_fu_1238_p2;
reg   [10:0] add_ln58_7745_reg_2592;
wire   [10:0] add_ln58_7764_fu_1244_p2;
reg   [10:0] add_ln58_7764_reg_2597;
wire  signed [11:0] tmp_960_fu_1448_p3;
reg  signed [11:0] tmp_960_reg_2602;
wire    ap_CS_fsm_state2;
wire   [13:0] add_ln73_8_fu_1511_p2;
reg   [13:0] add_ln73_8_reg_2607;
wire   [12:0] add_ln73_9_fu_1525_p2;
reg   [12:0] add_ln73_9_reg_2612;
wire   [12:0] sub_ln73_1860_fu_1535_p2;
reg   [12:0] sub_ln73_1860_reg_2617;
wire   [12:0] sub_ln73_1874_fu_1716_p2;
reg   [12:0] sub_ln73_1874_reg_2622;
wire  signed [12:0] add_ln73_10_fu_1736_p2;
reg  signed [12:0] add_ln73_10_reg_2627;
wire   [12:0] add_ln58_7743_fu_1884_p2;
reg   [12:0] add_ln58_7743_reg_2632;
wire   [12:0] add_ln58_7749_fu_1925_p2;
reg   [12:0] add_ln58_7749_reg_2637;
wire   [12:0] add_ln58_7752_fu_1946_p2;
reg   [12:0] add_ln58_7752_reg_2642;
wire   [12:0] add_ln58_7753_fu_1952_p2;
reg   [12:0] add_ln58_7753_reg_2647;
wire   [13:0] add_ln58_7757_fu_1974_p2;
reg   [13:0] add_ln58_7757_reg_2652;
wire   [13:0] add_ln58_7758_fu_1980_p2;
reg   [13:0] add_ln58_7758_reg_2657;
wire   [13:0] add_ln58_7762_fu_2002_p2;
reg   [13:0] add_ln58_7762_reg_2662;
wire   [12:0] add_ln58_7766_fu_2027_p2;
reg   [12:0] add_ln58_7766_reg_2667;
wire   [12:0] add_ln58_7768_fu_2033_p2;
reg   [12:0] add_ln58_7768_reg_2672;
wire   [11:0] trunc_ln58_fu_2039_p1;
reg   [11:0] trunc_ln58_reg_2677;
wire   [11:0] add_ln58_7773_fu_2049_p2;
reg   [11:0] add_ln58_7773_reg_2682;
wire   [11:0] add_ln58_7776_fu_2073_p2;
reg   [11:0] add_ln58_7776_reg_2687;
wire   [12:0] add_ln58_7781_fu_2089_p2;
reg   [12:0] add_ln58_7781_reg_2692;
wire   [13:0] sub_ln58_3115_fu_2105_p2;
reg   [13:0] sub_ln58_3115_reg_2697;
wire   [10:0] add_ln58_7788_fu_2111_p2;
reg   [10:0] add_ln58_7788_reg_2702;
wire   [12:0] add_ln58_7791_fu_2117_p2;
reg   [12:0] add_ln58_7791_reg_2707;
wire   [5:0] mul_ln73_9_fu_92_p1;
wire  signed [4:0] mul_ln73_6_fu_94_p1;
wire  signed [7:0] mul_ln73_fu_95_p0;
wire  signed [11:0] sext_ln70_1603_fu_914_p1;
wire  signed [4:0] mul_ln73_fu_95_p1;
wire  signed [4:0] mul_ln73_7_fu_97_p1;
wire  signed [4:0] mul_ln73_1_fu_99_p1;
wire  signed [7:0] mul_ln73_4_fu_100_p0;
wire  signed [12:0] sext_ln70_1612_fu_1070_p1;
wire  signed [4:0] mul_ln73_4_fu_100_p1;
wire   [5:0] mul_ln73_8_fu_104_p1;
wire   [4:0] mul_ln73_3_fu_105_p1;
wire   [5:0] mul_ln73_2_fu_108_p1;
wire  signed [7:0] mul_ln73_5_fu_109_p0;
wire  signed [4:0] mul_ln73_5_fu_109_p1;
wire  signed [7:0] sext_ln70_1603_fu_914_p0;
wire  signed [7:0] tmp_fu_919_p1;
wire  signed [10:0] tmp_fu_919_p3;
wire  signed [11:0] sext_ln73_fu_927_p1;
wire  signed [7:0] tmp_951_fu_937_p1;
wire   [8:0] tmp_951_fu_937_p3;
wire  signed [10:0] sext_ln73_1140_fu_945_p1;
wire   [11:0] sub_ln73_1846_fu_955_p2;
wire  signed [7:0] sext_ln70_1604_fu_971_p0;
wire  signed [7:0] tmp_952_fu_975_p1;
wire  signed [7:0] sext_ln70_1605_fu_991_p0;
wire  signed [7:0] sext_ln70_1606_fu_996_p0;
wire  signed [7:0] tmp_954_fu_1000_p1;
wire  signed [9:0] tmp_954_fu_1000_p3;
wire  signed [11:0] sext_ln73_1145_fu_1008_p1;
wire   [11:0] sub_ln73_1849_fu_1012_p2;
wire  signed [11:0] sext_ln70_1606_fu_996_p1;
wire  signed [7:0] sext_ln73_26_fu_1024_p0;
wire  signed [10:0] sext_ln73_1146_fu_1028_p1;
wire  signed [10:0] sext_ln73_26_fu_1024_p1;
wire  signed [7:0] sext_ln70_1607_fu_1042_p0;
wire  signed [7:0] sext_ln70_1608_fu_1047_p0;
wire  signed [7:0] sext_ln70_1610_fu_1052_p0;
wire  signed [8:0] sext_ln70_1610_fu_1052_p1;
wire   [8:0] sub_ln73_fu_1056_p2;
wire  signed [7:0] sext_ln70_1612_fu_1070_p0;
wire  signed [7:0] sext_ln70_1614_fu_1080_p0;
wire  signed [7:0] tmp_964_fu_1085_p1;
wire  signed [7:0] sext_ln73_36_fu_1093_p0;
wire  signed [10:0] sext_ln73_1165_fu_1097_p1;
wire   [10:0] sub_ln73_1861_fu_1101_p2;
wire  signed [10:0] sext_ln73_36_fu_1093_p1;
wire  signed [7:0] sext_ln70_1615_fu_1117_p0;
wire  signed [8:0] sext_ln70_1615_fu_1117_p1;
wire   [8:0] sub_ln73_482_fu_1121_p2;
wire  signed [7:0] sext_ln70_1617_fu_1135_p0;
wire  signed [7:0] sext_ln70_1618_fu_1140_p0;
wire  signed [7:0] tmp_971_fu_1145_p1;
wire  signed [10:0] sext_ln73_1176_fu_1153_p1;
wire  signed [7:0] sext_ln70_1620_fu_1167_p0;
wire   [11:0] sub_ln73_1844_fu_931_p2;
wire  signed [8:0] sext_ln70_1604_fu_971_p1;
wire   [8:0] sub_ln58_1772_fu_1190_p2;
wire  signed [11:0] sext_ln58_fu_1196_p1;
wire   [11:0] mul_ln73_fu_95_p2;
wire   [8:0] sub_ln58_1773_fu_1206_p2;
wire  signed [10:0] sext_ln58_9018_fu_1212_p1;
wire   [10:0] sub_ln73_1845_fu_949_p2;
wire  signed [9:0] sext_ln73_1144_fu_983_p1;
wire   [9:0] sub_ln58_3112_fu_1222_p2;
wire  signed [11:0] sext_ln58_9019_fu_1228_p1;
wire   [11:0] sub_ln73_1847_fu_961_p2;
wire   [10:0] add_ln73_4_fu_1032_p2;
wire  signed [10:0] sext_ln73_31_fu_1062_p1;
wire   [10:0] sub_ln73_1862_fu_1107_p2;
wire  signed [10:0] sext_ln73_41_fu_1127_p1;
wire  signed [10:0] shl_ln_fu_1253_p3;
wire  signed [12:0] sext_ln73_1141_fu_1264_p1;
wire  signed [12:0] sext_ln73_1142_fu_1268_p1;
wire   [11:0] tmp_953_fu_1277_p3;
wire  signed [12:0] sext_ln73_1143_fu_1284_p1;
wire   [11:0] shl_ln73_s_fu_1300_p3;
wire   [10:0] tmp_955_fu_1317_p3;
wire   [8:0] tmp_956_fu_1328_p3;
wire  signed [11:0] sext_ln73_1147_fu_1324_p1;
wire  signed [11:0] sext_ln73_1148_fu_1335_p1;
wire  signed [9:0] tmp_957_fu_1345_p3;
wire  signed [10:0] sext_ln70_1609_fu_1311_p1;
wire  signed [10:0] sext_ln73_1149_fu_1352_p1;
wire   [10:0] sub_ln73_1852_fu_1356_p2;
wire  signed [11:0] sext_ln73_1150_fu_1366_p1;
wire   [11:0] sub_ln73_1853_fu_1370_p2;
wire  signed [11:0] sext_ln70_1611_fu_1314_p1;
wire   [11:0] sub_ln73_1854_fu_1376_p2;
wire   [11:0] add_ln73_5_fu_1386_p2;
wire  signed [10:0] shl_ln73_1_fu_1400_p3;
wire  signed [12:0] sext_ln73_1152_fu_1411_p1;
wire  signed [8:0] tmp_959_fu_1421_p3;
wire   [12:0] sub_ln73_1855_fu_1415_p2;
wire  signed [12:0] sext_ln73_1153_fu_1428_p1;
wire  signed [11:0] sext_ln73_32_fu_1407_p1;
wire  signed [11:0] sext_ln73_1154_fu_1438_p1;
wire  signed [12:0] sext_ln73_1155_fu_1455_p1;
wire   [12:0] sub_ln73_1858_fu_1459_p2;
wire  signed [10:0] tmp_961_fu_1469_p3;
wire  signed [8:0] tmp_962_fu_1480_p3;
wire  signed [11:0] sext_ln73_1158_fu_1476_p1;
wire  signed [11:0] sext_ln73_1159_fu_1487_p1;
wire  signed [11:0] tmp_963_fu_1497_p3;
wire  signed [13:0] sext_ln73_1160_fu_1504_p1;
wire  signed [13:0] sext_ln73_1161_fu_1508_p1;
wire  signed [12:0] sext_ln73_1162_fu_1517_p1;
wire  signed [12:0] sext_ln73_1163_fu_1521_p1;
wire  signed [12:0] sext_ln73_1164_fu_1531_p1;
wire  signed [12:0] sext_ln73_1166_fu_1544_p1;
wire  signed [9:0] tmp_965_fu_1556_p3;
wire  signed [10:0] sext_ln73_1167_fu_1563_p1;
wire   [10:0] sub_ln73_1864_fu_1567_p2;
wire  signed [10:0] tmp_967_fu_1584_p3;
wire  signed [12:0] sext_ln73_1168_fu_1591_p1;
wire  signed [8:0] tmp_966_fu_1577_p3;
wire   [12:0] sub_ln73_1865_fu_1595_p2;
wire  signed [12:0] sext_ln73_1169_fu_1601_p1;
wire  signed [11:0] sext_ln73_1170_fu_1611_p1;
wire  signed [11:0] sext_ln73_1171_fu_1615_p1;
wire   [11:0] sub_ln73_1868_fu_1625_p2;
wire  signed [10:0] sext_ln70_1616_fu_1553_p1;
wire   [11:0] tmp_968_fu_1641_p3;
wire  signed [12:0] sext_ln73_1173_fu_1652_p1;
wire  signed [12:0] sext_ln73_1172_fu_1648_p1;
wire   [10:0] tmp_969_fu_1665_p3;
wire   [8:0] tmp_970_fu_1676_p3;
wire  signed [11:0] sext_ln73_1174_fu_1672_p1;
wire  signed [11:0] sext_ln73_1175_fu_1683_p1;
wire  signed [11:0] sext_ln70_1619_fu_1662_p1;
wire   [11:0] tmp_972_fu_1702_p3;
wire  signed [12:0] sext_ln73_1178_fu_1713_p1;
wire  signed [12:0] sext_ln73_1177_fu_1709_p1;
wire   [10:0] tmp_973_fu_1725_p3;
wire  signed [12:0] sext_ln73_1179_fu_1732_p1;
wire  signed [12:0] sext_ln70_1622_fu_1722_p1;
wire  signed [8:0] tmp_974_fu_1742_p3;
wire  signed [9:0] sext_ln73_1180_fu_1749_p1;
wire   [11:0] tmp_976_fu_1759_p3;
wire  signed [12:0] sext_ln73_1182_fu_1766_p1;
wire  signed [12:0] sext_ln73_1183_fu_1770_p1;
wire   [11:0] add_ln58_fu_1786_p2;
wire  signed [9:0] sext_ln70_fu_1250_p1;
wire   [9:0] sub_ln58_fu_1798_p2;
wire   [11:0] add_ln58_7733_fu_1811_p2;
wire  signed [11:0] sext_ln73_24_fu_1260_p1;
wire  signed [11:0] sext_ln58_390_fu_1804_p1;
wire   [11:0] add_ln58_7736_fu_1826_p2;
wire   [12:0] add_ln73_3_fu_1288_p2;
wire  signed [12:0] sext_ln58_391_fu_1808_p1;
wire   [12:0] add_ln58_7737_fu_1836_p2;
wire  signed [12:0] sext_ln58_397_fu_1823_p1;
wire  signed [12:0] sext_ln58_400_fu_1846_p1;
wire   [12:0] add_ln58_7740_fu_1858_p2;
wire  signed [12:0] sext_ln58_388_fu_1791_p1;
wire  signed [12:0] sext_ln58_401_fu_1849_p1;
wire   [11:0] sub_ln73_1851_fu_1339_p2;
wire   [11:0] add_ln58_7742_fu_1874_p2;
wire  signed [12:0] sext_ln58_9020_fu_1880_p1;
wire   [12:0] add_ln58_7741_fu_1868_p2;
wire   [12:0] sub_ln73_1848_fu_1294_p2;
wire  signed [12:0] sext_ln58_392_fu_1816_p1;
wire  signed [12:0] sext_ln58_9021_fu_1896_p1;
wire   [12:0] add_ln58_7744_fu_1890_p2;
wire   [12:0] add_ln58_7746_fu_1899_p2;
wire   [12:0] add_ln73_fu_1271_p2;
wire  signed [12:0] sext_ln58_389_fu_1795_p1;
wire   [11:0] add_ln58_7748_fu_1915_p2;
wire  signed [12:0] sext_ln58_9022_fu_1921_p1;
wire   [12:0] add_ln58_7747_fu_1909_p2;
wire  signed [12:0] sext_ln58_396_fu_1820_p1;
wire  signed [11:0] sext_ln73_28_fu_1362_p1;
wire   [11:0] add_ln58_7751_fu_1937_p2;
wire  signed [12:0] sext_ln58_9023_fu_1942_p1;
wire   [12:0] add_ln58_7750_fu_1931_p2;
wire   [12:0] add_ln58_7739_fu_1852_p2;
wire   [12:0] sub_ln73_1856_fu_1432_p2;
wire  signed [13:0] sext_ln58_399_fu_1842_p1;
wire  signed [13:0] sext_ln73_33_fu_1465_p1;
wire  signed [12:0] sext_ln73_25_fu_1307_p1;
wire  signed [12:0] sext_ln73_30_fu_1392_p1;
wire   [12:0] add_ln58_7756_fu_1964_p2;
wire  signed [13:0] sext_ln58_9025_fu_1970_p1;
wire   [13:0] add_ln58_7755_fu_1958_p2;
wire  signed [13:0] sext_ln58_405_fu_1905_p1;
wire  signed [13:0] sext_ln73_38_fu_1540_p1;
wire  signed [13:0] sext_ln58_403_fu_1864_p1;
wire  signed [13:0] mul_ln73_1831_cast_i_fu_1396_p1;
wire   [12:0] sub_ln73_1863_fu_1547_p2;
wire   [12:0] add_ln58_7761_fu_1992_p2;
wire  signed [13:0] sext_ln58_9026_fu_1998_p1;
wire   [13:0] add_ln58_7760_fu_1986_p2;
wire  signed [12:0] sext_ln73_29_fu_1382_p1;
wire  signed [12:0] sext_ln58_398_fu_1832_p1;
wire  signed [11:0] sext_ln58_9027_fu_2014_p1;
wire   [11:0] sub_ln73_1857_fu_1442_p2;
wire   [11:0] add_ln58_7765_fu_2017_p2;
wire  signed [12:0] sext_ln58_9028_fu_2023_p1;
wire   [12:0] add_ln58_7763_fu_2008_p2;
wire   [12:0] sub_ln73_1866_fu_1605_p2;
wire   [11:0] sub_ln73_1871_fu_1687_p2;
wire  signed [11:0] sext_ln73_39_fu_1573_p1;
wire   [11:0] add_ln58_7772_fu_2043_p2;
wire   [11:0] sub_ln73_1859_fu_1491_p2;
wire   [9:0] sub_ln73_1875_fu_1753_p2;
wire  signed [10:0] sext_ln58_9032_fu_2055_p1;
wire  signed [10:0] sext_ln58_9105_fu_2059_p1;
wire   [10:0] sub_ln58_3113_fu_2063_p2;
wire  signed [11:0] sext_ln58_9033_fu_2069_p1;
wire   [11:0] sub_ln73_1872_fu_1693_p2;
wire   [11:0] sub_ln73_1867_fu_1619_p2;
wire  signed [11:0] sext_ln73_43_fu_1699_p1;
wire   [11:0] add_ln58_7780_fu_2079_p2;
wire  signed [12:0] sext_ln58_9035_fu_2085_p1;
wire   [12:0] sub_ln73_1878_fu_1774_p2;
wire  signed [12:0] sext_ln73_42_fu_1631_p1;
wire   [12:0] sub_ln58_3114_fu_2095_p2;
wire  signed [13:0] sext_ln58_9106_fu_2101_p1;
wire   [10:0] sub_ln73_1869_fu_1635_p2;
wire   [12:0] sub_ln73_1870_fu_1656_p2;
wire   [12:0] sub_ln73_1879_fu_1780_p2;
wire    ap_CS_fsm_state3;
wire  signed [9:0] tmp_958_fu_2126_p3;
wire  signed [11:0] sext_ln73_1151_fu_2133_p1;
wire  signed [11:0] sext_ln70_1613_fu_2123_p1;
wire  signed [13:0] sext_ln73_1156_fu_2143_p1;
wire  signed [13:0] sext_ln73_1157_fu_2146_p1;
wire   [9:0] tmp_975_fu_2168_p3;
wire  signed [11:0] sext_ln73_1181_fu_2175_p1;
wire   [11:0] sub_ln73_1876_fu_2179_p2;
wire  signed [11:0] sext_ln70_1621_fu_2165_p1;
wire   [11:0] sub_ln73_1877_fu_2185_p2;
wire  signed [13:0] sext_ln58_9024_fu_2208_p1;
wire   [13:0] add_ln58_7754_fu_2211_p2;
wire   [13:0] add_ln73_7_fu_2150_p2;
wire   [13:0] add_ln58_7759_fu_2224_p2;
wire  signed [13:0] sext_ln58_407_fu_2205_p1;
wire  signed [13:0] sext_ln73_34_fu_2156_p1;
wire  signed [13:0] sext_ln58_9029_fu_2245_p1;
wire   [13:0] add_ln58_7767_fu_2239_p2;
wire   [13:0] add_ln58_7769_fu_2248_p2;
wire   [11:0] add_ln73_6_fu_2137_p2;
wire   [11:0] add_ln58_7770_fu_2265_p2;
wire  signed [13:0] sext_ln58_9030_fu_2270_p1;
wire  signed [13:0] sext_ln58_404_fu_2199_p1;
wire  signed [13:0] sext_ln58_9031_fu_2280_p1;
wire   [13:0] add_ln58_7771_fu_2274_p2;
wire   [13:0] add_ln58_7774_fu_2283_p2;
wire  signed [13:0] sext_ln58_406_fu_2202_p1;
wire  signed [13:0] sext_ln58_9034_fu_2298_p1;
wire   [13:0] add_ln58_7775_fu_2293_p2;
wire   [13:0] add_ln58_7777_fu_2301_p2;
wire  signed [14:0] sext_ln58_413_fu_2254_p1;
wire  signed [14:0] sext_ln73_44_fu_2191_p1;
wire   [14:0] add_ln58_7778_fu_2311_p2;
wire  signed [14:0] sext_ln58_408_fu_2217_p1;
wire  signed [14:0] sext_ln73_35_fu_2159_p1;
wire  signed [14:0] sext_ln58_9036_fu_2327_p1;
wire   [14:0] add_ln58_7779_fu_2321_p2;
wire   [14:0] add_ln58_7782_fu_2330_p2;
wire  signed [13:0] sext_ln58_412_fu_2236_p1;
wire  signed [13:0] sext_ln58_415_fu_2262_p1;
wire   [13:0] add_ln58_7783_fu_2340_p2;
wire   [13:0] add_ln58_7784_fu_2346_p2;
wire  signed [14:0] sext_ln58_409_fu_2221_p1;
wire  signed [14:0] sext_ln73_45_fu_2195_p1;
wire  signed [14:0] sext_ln58_9038_fu_2362_p1;
wire   [14:0] add_ln58_7785_fu_2356_p2;
wire   [14:0] add_ln58_7786_fu_2365_p2;
wire  signed [14:0] sext_ln58_410_fu_2229_p1;
wire  signed [14:0] mul_ln73_1860_cast_i_fu_2162_p1;
wire  signed [14:0] sext_ln58_9039_fu_2381_p1;
wire   [14:0] add_ln58_7787_fu_2375_p2;
wire   [14:0] add_ln58_7789_fu_2384_p2;
wire  signed [14:0] sext_ln58_411_fu_2233_p1;
wire  signed [14:0] sext_ln58_414_fu_2258_p1;
wire  signed [14:0] sext_ln58_9040_fu_2400_p1;
wire   [14:0] add_ln58_7790_fu_2394_p2;
wire   [14:0] add_ln58_7792_fu_2403_p2;
wire  signed [20:0] sext_ln58_416_fu_2289_p1;
wire  signed [20:0] sext_ln58_419_fu_2307_p1;
wire  signed [20:0] sext_ln58_420_fu_2317_p1;
wire  signed [20:0] sext_ln58_421_fu_2336_p1;
wire  signed [20:0] sext_ln58_422_fu_2352_p1;
wire  signed [20:0] sext_ln58_423_fu_2371_p1;
wire  signed [20:0] sext_ln58_424_fu_2390_p1;
wire  signed [20:0] sext_ln68_fu_2409_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
end

myproject_mul_8s_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6ns_14_1_1_U1367(
    .din0(sext_ln70_1620_fu_1167_p0),
    .din1(mul_ln73_9_fu_92_p1),
    .dout(mul_ln73_9_fu_92_p2)
);

myproject_mul_8s_5s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_1_U1368(
    .din0(sext_ln70_1614_fu_1080_p0),
    .din1(mul_ln73_6_fu_94_p1),
    .dout(mul_ln73_6_fu_94_p2)
);

myproject_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1369(
    .din0(mul_ln73_fu_95_p0),
    .din1(mul_ln73_fu_95_p1),
    .dout(mul_ln73_fu_95_p2)
);

myproject_mul_8s_5s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_1_U1370(
    .din0(sext_ln70_1618_fu_1140_p0),
    .din1(mul_ln73_7_fu_97_p1),
    .dout(mul_ln73_7_fu_97_p2)
);

myproject_mul_8s_5s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_1_U1371(
    .din0(sext_ln70_1605_fu_991_p0),
    .din1(mul_ln73_1_fu_99_p1),
    .dout(mul_ln73_1_fu_99_p2)
);

myproject_mul_8s_5s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_1_U1372(
    .din0(mul_ln73_4_fu_100_p0),
    .din1(mul_ln73_4_fu_100_p1),
    .dout(mul_ln73_4_fu_100_p2)
);

myproject_mul_8s_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6ns_14_1_1_U1373(
    .din0(sext_ln70_1617_fu_1135_p0),
    .din1(mul_ln73_8_fu_104_p1),
    .dout(mul_ln73_8_fu_104_p2)
);

myproject_mul_8s_5ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5ns_13_1_1_U1374(
    .din0(sext_ln70_1607_fu_1042_p0),
    .din1(mul_ln73_3_fu_105_p1),
    .dout(mul_ln73_3_fu_105_p2)
);

myproject_mul_8s_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6ns_14_1_1_U1375(
    .din0(sext_ln70_1608_fu_1047_p0),
    .din1(mul_ln73_2_fu_108_p1),
    .dout(mul_ln73_2_fu_108_p2)
);

myproject_mul_8s_5s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5s_13_1_1_U1376(
    .din0(mul_ln73_5_fu_109_p0),
    .din1(mul_ln73_5_fu_109_p1),
    .dout(mul_ln73_5_fu_109_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        a_125_reg_2466 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;
        a_126_reg_2477 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;
        a_127_reg_2488 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
        a_128_reg_2497 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14;
        a_129_reg_2506 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;
        a_130_reg_2524 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
        a_131_reg_2533 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;
        a_132_reg_2551 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;
        a_reg_2461 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
        add_ln58_7731_reg_2561 <= add_ln58_7731_fu_1172_p2;
        add_ln58_7732_reg_2567 <= add_ln58_7732_fu_1178_p2;
        add_ln58_7734_reg_2577 <= add_ln58_7734_fu_1200_p2;
        add_ln58_7735_reg_2582 <= add_ln58_7735_fu_1216_p2;
        add_ln58_7738_reg_2587 <= add_ln58_7738_fu_1232_p2;
        add_ln58_7745_reg_2592 <= add_ln58_7745_fu_1238_p2;
        add_ln58_7764_reg_2597 <= add_ln58_7764_fu_1244_p2;
        mul_ln73_1_reg_873 <= mul_ln73_1_fu_99_p2;
        mul_ln73_2_reg_877 <= mul_ln73_2_fu_108_p2;
        mul_ln73_3_reg_881 <= mul_ln73_3_fu_105_p2;
        mul_ln73_4_reg_885 <= mul_ln73_4_fu_100_p2;
        mul_ln73_5_reg_889 <= mul_ln73_5_fu_109_p2;
        mul_ln73_6_reg_893 <= mul_ln73_6_fu_94_p2;
        mul_ln73_7_reg_897 <= mul_ln73_7_fu_97_p2;
        mul_ln73_8_reg_901 <= mul_ln73_8_fu_104_p2;
        mul_ln73_9_reg_905 <= mul_ln73_9_fu_92_p2;
        sext_ln70_1614_reg_2513 <= sext_ln70_1614_fu_1080_p1;
        sub_ln58_3111_reg_2572[11 : 3] <= sub_ln58_3111_fu_1184_p2[11 : 3];
        sub_ln73_1850_reg_2482 <= sub_ln73_1850_fu_1018_p2;
        sub_ln73_1873_reg_2546[10 : 2] <= sub_ln73_1873_fu_1157_p2[10 : 2];
        tmp_952_reg_2472[8 : 1] <= tmp_952_fu_975_p3[8 : 1];
        tmp_964_reg_2518[9 : 2] <= tmp_964_fu_1085_p3[9 : 2];
        tmp_971_reg_2541[9 : 2] <= tmp_971_fu_1145_p3[9 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln58_7743_reg_2632 <= add_ln58_7743_fu_1884_p2;
        add_ln58_7749_reg_2637 <= add_ln58_7749_fu_1925_p2;
        add_ln58_7752_reg_2642 <= add_ln58_7752_fu_1946_p2;
        add_ln58_7753_reg_2647 <= add_ln58_7753_fu_1952_p2;
        add_ln58_7757_reg_2652 <= add_ln58_7757_fu_1974_p2;
        add_ln58_7758_reg_2657 <= add_ln58_7758_fu_1980_p2;
        add_ln58_7762_reg_2662 <= add_ln58_7762_fu_2002_p2;
        add_ln58_7766_reg_2667 <= add_ln58_7766_fu_2027_p2;
        add_ln58_7768_reg_2672 <= add_ln58_7768_fu_2033_p2;
        add_ln58_7773_reg_2682[11 : 1] <= add_ln58_7773_fu_2049_p2[11 : 1];
        add_ln58_7776_reg_2687 <= add_ln58_7776_fu_2073_p2;
        add_ln58_7781_reg_2692[12 : 1] <= add_ln58_7781_fu_2089_p2[12 : 1];
        add_ln58_7788_reg_2702 <= add_ln58_7788_fu_2111_p2;
        add_ln58_7791_reg_2707 <= add_ln58_7791_fu_2117_p2;
        add_ln73_10_reg_2627 <= add_ln73_10_fu_1736_p2;
        add_ln73_8_reg_2607[13 : 2] <= add_ln73_8_fu_1511_p2[13 : 2];
        add_ln73_9_reg_2612[12 : 1] <= add_ln73_9_fu_1525_p2[12 : 1];
        sub_ln58_3115_reg_2697[13 : 3] <= sub_ln58_3115_fu_2105_p2[13 : 3];
        sub_ln73_1860_reg_2617 <= sub_ln73_1860_fu_1535_p2;
        sub_ln73_1874_reg_2622[12 : 2] <= sub_ln73_1874_fu_1716_p2[12 : 2];
        tmp_960_reg_2602[11 : 4] <= tmp_960_fu_1448_p3[11 : 4];
        trunc_ln58_reg_2677 <= trunc_ln58_fu_2039_p1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (1'b0 == ap_ce))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_7731_fu_1172_p2 = ($signed(sext_ln73_fu_927_p1) + $signed(sext_ln70_1603_fu_914_p1));

assign add_ln58_7732_fu_1178_p2 = ($signed(sub_ln73_1844_fu_931_p2) + $signed(12'd3744));

assign add_ln58_7733_fu_1811_p2 = ($signed(add_ln58_7731_reg_2561) + $signed(12'd3968));

assign add_ln58_7734_fu_1200_p2 = ($signed(sext_ln58_fu_1196_p1) + $signed(mul_ln73_fu_95_p2));

assign add_ln58_7735_fu_1216_p2 = ($signed(sext_ln58_9018_fu_1212_p1) + $signed(sub_ln73_1845_fu_949_p2));

assign add_ln58_7736_fu_1826_p2 = ($signed(sext_ln73_24_fu_1260_p1) + $signed(sext_ln58_390_fu_1804_p1));

assign add_ln58_7737_fu_1836_p2 = ($signed(add_ln73_3_fu_1288_p2) + $signed(sext_ln58_391_fu_1808_p1));

assign add_ln58_7738_fu_1232_p2 = ($signed(sext_ln58_9019_fu_1228_p1) + $signed(sub_ln73_1847_fu_961_p2));

assign add_ln58_7739_fu_1852_p2 = ($signed(mul_ln73_1_reg_873) + $signed(sext_ln58_397_fu_1823_p1));

assign add_ln58_7740_fu_1858_p2 = ($signed(mul_ln73_1_reg_873) + $signed(sext_ln58_400_fu_1846_p1));

assign add_ln58_7741_fu_1868_p2 = ($signed(sext_ln58_388_fu_1791_p1) + $signed(sext_ln58_401_fu_1849_p1));

assign add_ln58_7742_fu_1874_p2 = ($signed(sub_ln73_1851_fu_1339_p2) + $signed(sext_ln73_24_fu_1260_p1));

assign add_ln58_7743_fu_1884_p2 = ($signed(sext_ln58_9020_fu_1880_p1) + $signed(add_ln58_7741_fu_1868_p2));

assign add_ln58_7744_fu_1890_p2 = ($signed(sub_ln73_1848_fu_1294_p2) + $signed(sext_ln58_392_fu_1816_p1));

assign add_ln58_7745_fu_1238_p2 = ($signed(add_ln73_4_fu_1032_p2) + $signed(sext_ln73_31_fu_1062_p1));

assign add_ln58_7746_fu_1899_p2 = ($signed(sext_ln58_9021_fu_1896_p1) + $signed(add_ln58_7744_fu_1890_p2));

assign add_ln58_7747_fu_1909_p2 = ($signed(add_ln73_fu_1271_p2) + $signed(sext_ln58_389_fu_1795_p1));

assign add_ln58_7748_fu_1915_p2 = ($signed(sext_ln73_32_fu_1407_p1) + $signed(sext_ln73_1148_fu_1335_p1));

assign add_ln58_7749_fu_1925_p2 = ($signed(sext_ln58_9022_fu_1921_p1) + $signed(add_ln58_7747_fu_1909_p2));

assign add_ln58_7750_fu_1931_p2 = ($signed(mul_ln73_4_reg_885) + $signed(sext_ln58_396_fu_1820_p1));

assign add_ln58_7751_fu_1937_p2 = ($signed(sub_ln73_1850_reg_2482) + $signed(sext_ln73_28_fu_1362_p1));

assign add_ln58_7752_fu_1946_p2 = ($signed(sext_ln58_9023_fu_1942_p1) + $signed(add_ln58_7750_fu_1931_p2));

assign add_ln58_7753_fu_1952_p2 = (add_ln58_7739_fu_1852_p2 + sub_ln73_1856_fu_1432_p2);

assign add_ln58_7754_fu_2211_p2 = ($signed(sext_ln58_9024_fu_2208_p1) + $signed(mul_ln73_2_reg_877));

assign add_ln58_7755_fu_1958_p2 = ($signed(sext_ln58_399_fu_1842_p1) + $signed(sext_ln73_33_fu_1465_p1));

assign add_ln58_7756_fu_1964_p2 = ($signed(sext_ln73_25_fu_1307_p1) + $signed(sext_ln73_30_fu_1392_p1));

assign add_ln58_7757_fu_1974_p2 = ($signed(sext_ln58_9025_fu_1970_p1) + $signed(add_ln58_7755_fu_1958_p2));

assign add_ln58_7758_fu_1980_p2 = ($signed(sext_ln58_405_fu_1905_p1) + $signed(sext_ln73_38_fu_1540_p1));

assign add_ln58_7759_fu_2224_p2 = (add_ln58_7758_reg_2657 + add_ln73_7_fu_2150_p2);

assign add_ln58_7760_fu_1986_p2 = ($signed(sext_ln58_403_fu_1864_p1) + $signed(mul_ln73_1831_cast_i_fu_1396_p1));

assign add_ln58_7761_fu_1992_p2 = (mul_ln73_5_reg_889 + sub_ln73_1863_fu_1547_p2);

assign add_ln58_7762_fu_2002_p2 = ($signed(sext_ln58_9026_fu_1998_p1) + $signed(add_ln58_7760_fu_1986_p2));

assign add_ln58_7763_fu_2008_p2 = ($signed(sext_ln73_29_fu_1382_p1) + $signed(sext_ln58_398_fu_1832_p1));

assign add_ln58_7764_fu_1244_p2 = ($signed(sub_ln73_1862_fu_1107_p2) + $signed(sext_ln73_41_fu_1127_p1));

assign add_ln58_7765_fu_2017_p2 = ($signed(sext_ln58_9027_fu_2014_p1) + $signed(sub_ln73_1857_fu_1442_p2));

assign add_ln58_7766_fu_2027_p2 = ($signed(sext_ln58_9028_fu_2023_p1) + $signed(add_ln58_7763_fu_2008_p2));

assign add_ln58_7767_fu_2239_p2 = ($signed(sext_ln58_407_fu_2205_p1) + $signed(sext_ln73_34_fu_2156_p1));

assign add_ln58_7768_fu_2033_p2 = (sub_ln73_1866_fu_1605_p2 + mul_ln73_7_reg_897);

assign add_ln58_7769_fu_2248_p2 = ($signed(sext_ln58_9029_fu_2245_p1) + $signed(add_ln58_7767_fu_2239_p2));

assign add_ln58_7770_fu_2265_p2 = (trunc_ln58_reg_2677 + add_ln73_6_fu_2137_p2);

assign add_ln58_7771_fu_2274_p2 = ($signed(sext_ln58_9030_fu_2270_p1) + $signed(sext_ln58_404_fu_2199_p1));

assign add_ln58_7772_fu_2043_p2 = ($signed(sub_ln73_1871_fu_1687_p2) + $signed(sext_ln73_39_fu_1573_p1));

assign add_ln58_7773_fu_2049_p2 = (add_ln58_7772_fu_2043_p2 + sub_ln73_1859_fu_1491_p2);

assign add_ln58_7774_fu_2283_p2 = ($signed(sext_ln58_9031_fu_2280_p1) + $signed(add_ln58_7771_fu_2274_p2));

assign add_ln58_7775_fu_2293_p2 = ($signed(add_ln73_8_reg_2607) + $signed(sext_ln58_406_fu_2202_p1));

assign add_ln58_7776_fu_2073_p2 = ($signed(sext_ln58_9033_fu_2069_p1) + $signed(sub_ln73_1872_fu_1693_p2));

assign add_ln58_7777_fu_2301_p2 = ($signed(sext_ln58_9034_fu_2298_p1) + $signed(add_ln58_7775_fu_2293_p2));

assign add_ln58_7778_fu_2311_p2 = ($signed(sext_ln58_413_fu_2254_p1) + $signed(sext_ln73_44_fu_2191_p1));

assign add_ln58_7779_fu_2321_p2 = ($signed(sext_ln58_408_fu_2217_p1) + $signed(sext_ln73_35_fu_2159_p1));

assign add_ln58_7780_fu_2079_p2 = ($signed(sub_ln73_1867_fu_1619_p2) + $signed(sext_ln73_43_fu_1699_p1));

assign add_ln58_7781_fu_2089_p2 = ($signed(sext_ln58_9035_fu_2085_p1) + $signed(sub_ln73_1878_fu_1774_p2));

assign add_ln58_7782_fu_2330_p2 = ($signed(sext_ln58_9036_fu_2327_p1) + $signed(add_ln58_7779_fu_2321_p2));

assign add_ln58_7783_fu_2340_p2 = ($signed(sext_ln58_412_fu_2236_p1) + $signed(sext_ln58_415_fu_2262_p1));

assign add_ln58_7784_fu_2346_p2 = ($signed(add_ln58_7783_fu_2340_p2) + $signed(mul_ln73_8_reg_901));

assign add_ln58_7785_fu_2356_p2 = ($signed(sext_ln58_409_fu_2221_p1) + $signed(sext_ln73_45_fu_2195_p1));

assign add_ln58_7786_fu_2365_p2 = ($signed(sext_ln58_9038_fu_2362_p1) + $signed(add_ln58_7785_fu_2356_p2));

assign add_ln58_7787_fu_2375_p2 = ($signed(sext_ln58_410_fu_2229_p1) + $signed(mul_ln73_1860_cast_i_fu_2162_p1));

assign add_ln58_7788_fu_2111_p2 = ($signed(sub_ln73_1869_fu_1635_p2) + $signed(sext_ln58_9032_fu_2055_p1));

assign add_ln58_7789_fu_2384_p2 = ($signed(sext_ln58_9039_fu_2381_p1) + $signed(add_ln58_7787_fu_2375_p2));

assign add_ln58_7790_fu_2394_p2 = ($signed(sext_ln58_411_fu_2233_p1) + $signed(sext_ln58_414_fu_2258_p1));

assign add_ln58_7791_fu_2117_p2 = (sub_ln73_1870_fu_1656_p2 + sub_ln73_1879_fu_1780_p2);

assign add_ln58_7792_fu_2403_p2 = ($signed(sext_ln58_9040_fu_2400_p1) + $signed(add_ln58_7790_fu_2394_p2));

assign add_ln58_fu_1786_p2 = ($signed(add_ln58_7731_reg_2561) + $signed(12'd3712));

assign add_ln73_10_fu_1736_p2 = ($signed(sext_ln73_1179_fu_1732_p1) + $signed(sext_ln70_1622_fu_1722_p1));

assign add_ln73_3_fu_1288_p2 = ($signed(sext_ln73_1143_fu_1284_p1) + $signed(sext_ln73_1142_fu_1268_p1));

assign add_ln73_4_fu_1032_p2 = ($signed(sext_ln73_1146_fu_1028_p1) + $signed(sext_ln73_26_fu_1024_p1));

assign add_ln73_5_fu_1386_p2 = ($signed(sext_ln73_1150_fu_1366_p1) + $signed(sext_ln70_1611_fu_1314_p1));

assign add_ln73_6_fu_2137_p2 = ($signed(sext_ln73_1151_fu_2133_p1) + $signed(sext_ln70_1613_fu_2123_p1));

assign add_ln73_7_fu_2150_p2 = ($signed(sext_ln73_1156_fu_2143_p1) + $signed(sext_ln73_1157_fu_2146_p1));

assign add_ln73_8_fu_1511_p2 = ($signed(sext_ln73_1160_fu_1504_p1) + $signed(sext_ln73_1161_fu_1508_p1));

assign add_ln73_9_fu_1525_p2 = ($signed(sext_ln73_1162_fu_1517_p1) + $signed(sext_ln73_1163_fu_1521_p1));

assign add_ln73_fu_1271_p2 = ($signed(sext_ln73_1141_fu_1264_p1) + $signed(sext_ln73_1142_fu_1268_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_return_0 = sext_ln58_416_fu_2289_p1;

assign ap_return_1 = sext_ln58_419_fu_2307_p1;

assign ap_return_2 = sext_ln58_420_fu_2317_p1;

assign ap_return_3 = sext_ln58_421_fu_2336_p1;

assign ap_return_4 = sext_ln58_422_fu_2352_p1;

assign ap_return_5 = sext_ln58_423_fu_2371_p1;

assign ap_return_6 = sext_ln58_424_fu_2390_p1;

assign ap_return_7 = sext_ln68_fu_2409_p1;

assign mul_ln73_1831_cast_i_fu_1396_p1 = $signed(mul_ln73_3_reg_881);

assign mul_ln73_1860_cast_i_fu_2162_p1 = $signed(sub_ln73_1874_reg_2622);

assign mul_ln73_1_fu_99_p1 = 13'd8181;

assign mul_ln73_2_fu_108_p1 = 14'd21;

assign mul_ln73_3_fu_105_p1 = 13'd11;

assign mul_ln73_4_fu_100_p0 = sext_ln70_1612_fu_1070_p1;

assign mul_ln73_4_fu_100_p1 = 13'd8181;

assign mul_ln73_5_fu_109_p0 = sext_ln70_1612_fu_1070_p1;

assign mul_ln73_5_fu_109_p1 = 13'd8179;

assign mul_ln73_6_fu_94_p1 = 13'd8179;

assign mul_ln73_7_fu_97_p1 = 13'd8181;

assign mul_ln73_8_fu_104_p1 = 14'd25;

assign mul_ln73_9_fu_92_p1 = 14'd22;

assign mul_ln73_fu_95_p0 = sext_ln70_1603_fu_914_p1;

assign mul_ln73_fu_95_p1 = 12'd4085;

assign sext_ln58_388_fu_1791_p1 = $signed(add_ln58_fu_1786_p2);

assign sext_ln58_389_fu_1795_p1 = $signed(add_ln58_7732_reg_2567);

assign sext_ln58_390_fu_1804_p1 = $signed(sub_ln58_fu_1798_p2);

assign sext_ln58_391_fu_1808_p1 = $signed(sub_ln58_3111_reg_2572);

assign sext_ln58_392_fu_1816_p1 = $signed(add_ln58_7733_fu_1811_p2);

assign sext_ln58_396_fu_1820_p1 = $signed(add_ln58_7734_reg_2577);

assign sext_ln58_397_fu_1823_p1 = $signed(add_ln58_7735_reg_2582);

assign sext_ln58_398_fu_1832_p1 = $signed(add_ln58_7736_fu_1826_p2);

assign sext_ln58_399_fu_1842_p1 = $signed(add_ln58_7737_fu_1836_p2);

assign sext_ln58_400_fu_1846_p1 = $signed(add_ln58_7738_reg_2587);

assign sext_ln58_401_fu_1849_p1 = sub_ln73_1850_reg_2482;

assign sext_ln58_403_fu_1864_p1 = $signed(add_ln58_7740_fu_1858_p2);

assign sext_ln58_404_fu_2199_p1 = $signed(add_ln58_7743_reg_2632);

assign sext_ln58_405_fu_1905_p1 = $signed(add_ln58_7746_fu_1899_p2);

assign sext_ln58_406_fu_2202_p1 = $signed(add_ln58_7749_reg_2637);

assign sext_ln58_407_fu_2205_p1 = $signed(add_ln58_7752_reg_2642);

assign sext_ln58_408_fu_2217_p1 = $signed(add_ln58_7754_fu_2211_p2);

assign sext_ln58_409_fu_2221_p1 = $signed(add_ln58_7757_reg_2652);

assign sext_ln58_410_fu_2229_p1 = $signed(add_ln58_7759_fu_2224_p2);

assign sext_ln58_411_fu_2233_p1 = $signed(add_ln58_7762_reg_2662);

assign sext_ln58_412_fu_2236_p1 = $signed(add_ln58_7766_reg_2667);

assign sext_ln58_413_fu_2254_p1 = $signed(add_ln58_7769_fu_2248_p2);

assign sext_ln58_414_fu_2258_p1 = mul_ln73_8_reg_901;

assign sext_ln58_415_fu_2262_p1 = add_ln73_10_reg_2627;

assign sext_ln58_416_fu_2289_p1 = $signed(add_ln58_7774_fu_2283_p2);

assign sext_ln58_419_fu_2307_p1 = $signed(add_ln58_7777_fu_2301_p2);

assign sext_ln58_420_fu_2317_p1 = $signed(add_ln58_7778_fu_2311_p2);

assign sext_ln58_421_fu_2336_p1 = $signed(add_ln58_7782_fu_2330_p2);

assign sext_ln58_422_fu_2352_p1 = $signed(add_ln58_7784_fu_2346_p2);

assign sext_ln58_423_fu_2371_p1 = $signed(add_ln58_7786_fu_2365_p2);

assign sext_ln58_424_fu_2390_p1 = $signed(add_ln58_7789_fu_2384_p2);

assign sext_ln58_9018_fu_1212_p1 = $signed(sub_ln58_1773_fu_1206_p2);

assign sext_ln58_9019_fu_1228_p1 = $signed(sub_ln58_3112_fu_1222_p2);

assign sext_ln58_9020_fu_1880_p1 = $signed(add_ln58_7742_fu_1874_p2);

assign sext_ln58_9021_fu_1896_p1 = $signed(add_ln58_7745_reg_2592);

assign sext_ln58_9022_fu_1921_p1 = $signed(add_ln58_7748_fu_1915_p2);

assign sext_ln58_9023_fu_1942_p1 = $signed(add_ln58_7751_fu_1937_p2);

assign sext_ln58_9024_fu_2208_p1 = $signed(add_ln58_7753_reg_2647);

assign sext_ln58_9025_fu_1970_p1 = $signed(add_ln58_7756_fu_1964_p2);

assign sext_ln58_9026_fu_1998_p1 = $signed(add_ln58_7761_fu_1992_p2);

assign sext_ln58_9027_fu_2014_p1 = $signed(add_ln58_7764_reg_2597);

assign sext_ln58_9028_fu_2023_p1 = $signed(add_ln58_7765_fu_2017_p2);

assign sext_ln58_9029_fu_2245_p1 = $signed(add_ln58_7768_reg_2672);

assign sext_ln58_9030_fu_2270_p1 = $signed(add_ln58_7770_fu_2265_p2);

assign sext_ln58_9031_fu_2280_p1 = $signed(add_ln58_7773_reg_2682);

assign sext_ln58_9032_fu_2055_p1 = $signed(sub_ln73_1875_fu_1753_p2);

assign sext_ln58_9033_fu_2069_p1 = $signed(sub_ln58_3113_fu_2063_p2);

assign sext_ln58_9034_fu_2298_p1 = $signed(add_ln58_7776_reg_2687);

assign sext_ln58_9035_fu_2085_p1 = $signed(add_ln58_7780_fu_2079_p2);

assign sext_ln58_9036_fu_2327_p1 = $signed(add_ln58_7781_reg_2692);

assign sext_ln58_9038_fu_2362_p1 = $signed(sub_ln58_3115_reg_2697);

assign sext_ln58_9039_fu_2381_p1 = $signed(add_ln58_7788_reg_2702);

assign sext_ln58_9040_fu_2400_p1 = $signed(add_ln58_7791_reg_2707);

assign sext_ln58_9105_fu_2059_p1 = tmp_966_fu_1577_p3;

assign sext_ln58_9106_fu_2101_p1 = $signed(sub_ln58_3114_fu_2095_p2);

assign sext_ln58_fu_1196_p1 = $signed(sub_ln58_1772_fu_1190_p2);

assign sext_ln68_fu_2409_p1 = $signed(add_ln58_7792_fu_2403_p2);

assign sext_ln70_1603_fu_914_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;

assign sext_ln70_1603_fu_914_p1 = sext_ln70_1603_fu_914_p0;

assign sext_ln70_1604_fu_971_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;

assign sext_ln70_1604_fu_971_p1 = sext_ln70_1604_fu_971_p0;

assign sext_ln70_1605_fu_991_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;

assign sext_ln70_1606_fu_996_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;

assign sext_ln70_1606_fu_996_p1 = sext_ln70_1606_fu_996_p0;

assign sext_ln70_1607_fu_1042_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;

assign sext_ln70_1608_fu_1047_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;

assign sext_ln70_1609_fu_1311_p1 = a_127_reg_2488;

assign sext_ln70_1610_fu_1052_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;

assign sext_ln70_1610_fu_1052_p1 = sext_ln70_1610_fu_1052_p0;

assign sext_ln70_1611_fu_1314_p1 = a_127_reg_2488;

assign sext_ln70_1612_fu_1070_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14;

assign sext_ln70_1612_fu_1070_p1 = sext_ln70_1612_fu_1070_p0;

assign sext_ln70_1613_fu_2123_p1 = a_128_reg_2497;

assign sext_ln70_1614_fu_1080_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;

assign sext_ln70_1614_fu_1080_p1 = sext_ln70_1614_fu_1080_p0;

assign sext_ln70_1615_fu_1117_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;

assign sext_ln70_1615_fu_1117_p1 = sext_ln70_1615_fu_1117_p0;

assign sext_ln70_1616_fu_1553_p1 = a_130_reg_2524;

assign sext_ln70_1617_fu_1135_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;

assign sext_ln70_1618_fu_1140_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;

assign sext_ln70_1619_fu_1662_p1 = a_131_reg_2533;

assign sext_ln70_1620_fu_1167_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;

assign sext_ln70_1621_fu_2165_p1 = a_132_reg_2551;

assign sext_ln70_1622_fu_1722_p1 = a_132_reg_2551;

assign sext_ln70_fu_1250_p1 = a_reg_2461;

assign sext_ln73_1140_fu_945_p1 = $signed(tmp_951_fu_937_p3);

assign sext_ln73_1141_fu_1264_p1 = shl_ln_fu_1253_p3;

assign sext_ln73_1142_fu_1268_p1 = tmp_952_reg_2472;

assign sext_ln73_1143_fu_1284_p1 = $signed(tmp_953_fu_1277_p3);

assign sext_ln73_1144_fu_983_p1 = tmp_952_fu_975_p3;

assign sext_ln73_1145_fu_1008_p1 = tmp_954_fu_1000_p3;

assign sext_ln73_1146_fu_1028_p1 = tmp_954_fu_1000_p3;

assign sext_ln73_1147_fu_1324_p1 = $signed(tmp_955_fu_1317_p3);

assign sext_ln73_1148_fu_1335_p1 = $signed(tmp_956_fu_1328_p3);

assign sext_ln73_1149_fu_1352_p1 = tmp_957_fu_1345_p3;

assign sext_ln73_1150_fu_1366_p1 = tmp_957_fu_1345_p3;

assign sext_ln73_1151_fu_2133_p1 = tmp_958_fu_2126_p3;

assign sext_ln73_1152_fu_1411_p1 = shl_ln73_1_fu_1400_p3;

assign sext_ln73_1153_fu_1428_p1 = tmp_959_fu_1421_p3;

assign sext_ln73_1154_fu_1438_p1 = tmp_959_fu_1421_p3;

assign sext_ln73_1155_fu_1455_p1 = tmp_960_fu_1448_p3;

assign sext_ln73_1156_fu_2143_p1 = tmp_960_reg_2602;

assign sext_ln73_1157_fu_2146_p1 = tmp_958_fu_2126_p3;

assign sext_ln73_1158_fu_1476_p1 = tmp_961_fu_1469_p3;

assign sext_ln73_1159_fu_1487_p1 = tmp_962_fu_1480_p3;

assign sext_ln73_1160_fu_1504_p1 = tmp_963_fu_1497_p3;

assign sext_ln73_1161_fu_1508_p1 = tmp_964_reg_2518;

assign sext_ln73_1162_fu_1517_p1 = tmp_961_fu_1469_p3;

assign sext_ln73_1163_fu_1521_p1 = tmp_962_fu_1480_p3;

assign sext_ln73_1164_fu_1531_p1 = tmp_963_fu_1497_p3;

assign sext_ln73_1165_fu_1097_p1 = tmp_964_fu_1085_p3;

assign sext_ln73_1166_fu_1544_p1 = tmp_964_reg_2518;

assign sext_ln73_1167_fu_1563_p1 = tmp_965_fu_1556_p3;

assign sext_ln73_1168_fu_1591_p1 = tmp_967_fu_1584_p3;

assign sext_ln73_1169_fu_1601_p1 = tmp_966_fu_1577_p3;

assign sext_ln73_1170_fu_1611_p1 = tmp_967_fu_1584_p3;

assign sext_ln73_1171_fu_1615_p1 = tmp_966_fu_1577_p3;

assign sext_ln73_1172_fu_1648_p1 = $signed(tmp_968_fu_1641_p3);

assign sext_ln73_1173_fu_1652_p1 = tmp_965_fu_1556_p3;

assign sext_ln73_1174_fu_1672_p1 = $signed(tmp_969_fu_1665_p3);

assign sext_ln73_1175_fu_1683_p1 = $signed(tmp_970_fu_1676_p3);

assign sext_ln73_1176_fu_1153_p1 = tmp_971_fu_1145_p3;

assign sext_ln73_1177_fu_1709_p1 = $signed(tmp_972_fu_1702_p3);

assign sext_ln73_1178_fu_1713_p1 = tmp_971_reg_2541;

assign sext_ln73_1179_fu_1732_p1 = $signed(tmp_973_fu_1725_p3);

assign sext_ln73_1180_fu_1749_p1 = tmp_974_fu_1742_p3;

assign sext_ln73_1181_fu_2175_p1 = $signed(tmp_975_fu_2168_p3);

assign sext_ln73_1182_fu_1766_p1 = $signed(tmp_976_fu_1759_p3);

assign sext_ln73_1183_fu_1770_p1 = tmp_974_fu_1742_p3;

assign sext_ln73_24_fu_1260_p1 = shl_ln_fu_1253_p3;

assign sext_ln73_25_fu_1307_p1 = $signed(shl_ln73_s_fu_1300_p3);

assign sext_ln73_26_fu_1024_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;

assign sext_ln73_26_fu_1024_p1 = sext_ln73_26_fu_1024_p0;

assign sext_ln73_28_fu_1362_p1 = $signed(sub_ln73_1852_fu_1356_p2);

assign sext_ln73_29_fu_1382_p1 = $signed(sub_ln73_1854_fu_1376_p2);

assign sext_ln73_30_fu_1392_p1 = $signed(add_ln73_5_fu_1386_p2);

assign sext_ln73_31_fu_1062_p1 = $signed(sub_ln73_fu_1056_p2);

assign sext_ln73_32_fu_1407_p1 = shl_ln73_1_fu_1400_p3;

assign sext_ln73_33_fu_1465_p1 = $signed(sub_ln73_1858_fu_1459_p2);

assign sext_ln73_34_fu_2156_p1 = $signed(add_ln73_9_reg_2612);

assign sext_ln73_35_fu_2159_p1 = $signed(sub_ln73_1860_reg_2617);

assign sext_ln73_36_fu_1093_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;

assign sext_ln73_36_fu_1093_p1 = sext_ln73_36_fu_1093_p0;

assign sext_ln73_38_fu_1540_p1 = $signed(mul_ln73_6_reg_893);

assign sext_ln73_39_fu_1573_p1 = $signed(sub_ln73_1864_fu_1567_p2);

assign sext_ln73_41_fu_1127_p1 = $signed(sub_ln73_482_fu_1121_p2);

assign sext_ln73_42_fu_1631_p1 = $signed(sub_ln73_1868_fu_1625_p2);

assign sext_ln73_43_fu_1699_p1 = $signed(sub_ln73_1873_reg_2546);

assign sext_ln73_44_fu_2191_p1 = $signed(sub_ln73_1877_fu_2185_p2);

assign sext_ln73_45_fu_2195_p1 = $signed(mul_ln73_9_reg_905);

assign sext_ln73_fu_927_p1 = tmp_fu_919_p3;

assign shl_ln73_1_fu_1400_p3 = {{a_128_reg_2497}, {3'd0}};

assign shl_ln73_s_fu_1300_p3 = {{a_126_reg_2477}, {4'd0}};

assign shl_ln_fu_1253_p3 = {{a_125_reg_2466}, {3'd0}};

assign sub_ln58_1772_fu_1190_p2 = ($signed(9'd96) - $signed(sext_ln70_1604_fu_971_p1));

assign sub_ln58_1773_fu_1206_p2 = ($signed(9'd448) - $signed(sext_ln70_1604_fu_971_p1));

assign sub_ln58_3111_fu_1184_p2 = ($signed(12'd4000) - $signed(sext_ln73_fu_927_p1));

assign sub_ln58_3112_fu_1222_p2 = ($signed(10'd896) - $signed(sext_ln73_1144_fu_983_p1));

assign sub_ln58_3113_fu_2063_p2 = ($signed(sext_ln58_9032_fu_2055_p1) - $signed(sext_ln58_9105_fu_2059_p1));

assign sub_ln58_3114_fu_2095_p2 = ($signed(sext_ln73_42_fu_1631_p1) - $signed(sext_ln73_1177_fu_1709_p1));

assign sub_ln58_3115_fu_2105_p2 = ($signed(sext_ln58_9106_fu_2101_p1) - $signed(sext_ln73_1160_fu_1504_p1));

assign sub_ln58_fu_1798_p2 = ($signed(10'd704) - $signed(sext_ln70_fu_1250_p1));

assign sub_ln73_1844_fu_931_p2 = ($signed(sext_ln70_1603_fu_914_p1) - $signed(sext_ln73_fu_927_p1));

assign sub_ln73_1845_fu_949_p2 = ($signed(sext_ln73_1140_fu_945_p1) - $signed(tmp_fu_919_p3));

assign sub_ln73_1846_fu_955_p2 = ($signed(12'd0) - $signed(sext_ln73_fu_927_p1));

assign sub_ln73_1847_fu_961_p2 = ($signed(sub_ln73_1846_fu_955_p2) - $signed(sext_ln70_1603_fu_914_p1));

assign sub_ln73_1848_fu_1294_p2 = ($signed(sext_ln73_1143_fu_1284_p1) - $signed(sext_ln73_1142_fu_1268_p1));

assign sub_ln73_1849_fu_1012_p2 = ($signed(12'd0) - $signed(sext_ln73_1145_fu_1008_p1));

assign sub_ln73_1850_fu_1018_p2 = ($signed(sub_ln73_1849_fu_1012_p2) - $signed(sext_ln70_1606_fu_996_p1));

assign sub_ln73_1851_fu_1339_p2 = ($signed(sext_ln73_1147_fu_1324_p1) - $signed(sext_ln73_1148_fu_1335_p1));

assign sub_ln73_1852_fu_1356_p2 = ($signed(sext_ln70_1609_fu_1311_p1) - $signed(sext_ln73_1149_fu_1352_p1));

assign sub_ln73_1853_fu_1370_p2 = ($signed(12'd0) - $signed(sext_ln73_1150_fu_1366_p1));

assign sub_ln73_1854_fu_1376_p2 = ($signed(sub_ln73_1853_fu_1370_p2) - $signed(sext_ln70_1611_fu_1314_p1));

assign sub_ln73_1855_fu_1415_p2 = ($signed(13'd0) - $signed(sext_ln73_1152_fu_1411_p1));

assign sub_ln73_1856_fu_1432_p2 = ($signed(sub_ln73_1855_fu_1415_p2) - $signed(sext_ln73_1153_fu_1428_p1));

assign sub_ln73_1857_fu_1442_p2 = ($signed(sext_ln73_32_fu_1407_p1) - $signed(sext_ln73_1154_fu_1438_p1));

assign sub_ln73_1858_fu_1459_p2 = ($signed(sext_ln73_1153_fu_1428_p1) - $signed(sext_ln73_1155_fu_1455_p1));

assign sub_ln73_1859_fu_1491_p2 = ($signed(sext_ln73_1158_fu_1476_p1) - $signed(sext_ln73_1159_fu_1487_p1));

assign sub_ln73_1860_fu_1535_p2 = ($signed(sext_ln73_1164_fu_1531_p1) - $signed(sext_ln70_1614_reg_2513));

assign sub_ln73_1861_fu_1101_p2 = ($signed(11'd0) - $signed(sext_ln73_1165_fu_1097_p1));

assign sub_ln73_1862_fu_1107_p2 = ($signed(sub_ln73_1861_fu_1101_p2) - $signed(sext_ln73_36_fu_1093_p1));

assign sub_ln73_1863_fu_1547_p2 = ($signed(sext_ln73_1166_fu_1544_p1) - $signed(sext_ln73_1164_fu_1531_p1));

assign sub_ln73_1864_fu_1567_p2 = ($signed(11'd0) - $signed(sext_ln73_1167_fu_1563_p1));

assign sub_ln73_1865_fu_1595_p2 = ($signed(13'd0) - $signed(sext_ln73_1168_fu_1591_p1));

assign sub_ln73_1866_fu_1605_p2 = ($signed(sub_ln73_1865_fu_1595_p2) - $signed(sext_ln73_1169_fu_1601_p1));

assign sub_ln73_1867_fu_1619_p2 = ($signed(sext_ln73_1170_fu_1611_p1) - $signed(sext_ln73_1171_fu_1615_p1));

assign sub_ln73_1868_fu_1625_p2 = ($signed(12'd0) - $signed(sext_ln73_1170_fu_1611_p1));

assign sub_ln73_1869_fu_1635_p2 = ($signed(sext_ln70_1616_fu_1553_p1) - $signed(sext_ln73_1167_fu_1563_p1));

assign sub_ln73_1870_fu_1656_p2 = ($signed(sext_ln73_1173_fu_1652_p1) - $signed(sext_ln73_1172_fu_1648_p1));

assign sub_ln73_1871_fu_1687_p2 = ($signed(sext_ln73_1174_fu_1672_p1) - $signed(sext_ln73_1175_fu_1683_p1));

assign sub_ln73_1872_fu_1693_p2 = ($signed(sext_ln73_1174_fu_1672_p1) - $signed(sext_ln70_1619_fu_1662_p1));

assign sub_ln73_1873_fu_1157_p2 = ($signed(11'd0) - $signed(sext_ln73_1176_fu_1153_p1));

assign sub_ln73_1874_fu_1716_p2 = ($signed(sext_ln73_1178_fu_1713_p1) - $signed(sext_ln73_1177_fu_1709_p1));

assign sub_ln73_1875_fu_1753_p2 = ($signed(10'd0) - $signed(sext_ln73_1180_fu_1749_p1));

assign sub_ln73_1876_fu_2179_p2 = ($signed(12'd0) - $signed(sext_ln73_1181_fu_2175_p1));

assign sub_ln73_1877_fu_2185_p2 = ($signed(sub_ln73_1876_fu_2179_p2) - $signed(sext_ln70_1621_fu_2165_p1));

assign sub_ln73_1878_fu_1774_p2 = ($signed(sext_ln73_1182_fu_1766_p1) - $signed(sext_ln73_1183_fu_1770_p1));

assign sub_ln73_1879_fu_1780_p2 = ($signed(sext_ln73_1182_fu_1766_p1) - $signed(sext_ln70_1622_fu_1722_p1));

assign sub_ln73_482_fu_1121_p2 = ($signed(9'd0) - $signed(sext_ln70_1615_fu_1117_p1));

assign sub_ln73_fu_1056_p2 = ($signed(9'd0) - $signed(sext_ln70_1610_fu_1052_p1));

assign tmp_951_fu_937_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;

assign tmp_951_fu_937_p3 = {{tmp_951_fu_937_p1}, {1'd0}};

assign tmp_952_fu_975_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;

assign tmp_952_fu_975_p3 = {{tmp_952_fu_975_p1}, {1'd0}};

assign tmp_953_fu_1277_p3 = {{a_125_reg_2466}, {4'd0}};

assign tmp_954_fu_1000_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;

assign tmp_954_fu_1000_p3 = {{tmp_954_fu_1000_p1}, {2'd0}};

assign tmp_955_fu_1317_p3 = {{a_127_reg_2488}, {3'd0}};

assign tmp_956_fu_1328_p3 = {{a_127_reg_2488}, {1'd0}};

assign tmp_957_fu_1345_p3 = {{a_127_reg_2488}, {2'd0}};

assign tmp_958_fu_2126_p3 = {{a_128_reg_2497}, {2'd0}};

assign tmp_959_fu_1421_p3 = {{a_128_reg_2497}, {1'd0}};

assign tmp_960_fu_1448_p3 = {{a_128_reg_2497}, {4'd0}};

assign tmp_961_fu_1469_p3 = {{a_129_reg_2506}, {3'd0}};

assign tmp_962_fu_1480_p3 = {{a_129_reg_2506}, {1'd0}};

assign tmp_963_fu_1497_p3 = {{a_129_reg_2506}, {4'd0}};

assign tmp_964_fu_1085_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;

assign tmp_964_fu_1085_p3 = {{tmp_964_fu_1085_p1}, {2'd0}};

assign tmp_965_fu_1556_p3 = {{a_130_reg_2524}, {2'd0}};

assign tmp_966_fu_1577_p3 = {{a_130_reg_2524}, {1'd0}};

assign tmp_967_fu_1584_p3 = {{a_130_reg_2524}, {3'd0}};

assign tmp_968_fu_1641_p3 = {{a_130_reg_2524}, {4'd0}};

assign tmp_969_fu_1665_p3 = {{a_131_reg_2533}, {3'd0}};

assign tmp_970_fu_1676_p3 = {{a_131_reg_2533}, {1'd0}};

assign tmp_971_fu_1145_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;

assign tmp_971_fu_1145_p3 = {{tmp_971_fu_1145_p1}, {2'd0}};

assign tmp_972_fu_1702_p3 = {{a_131_reg_2533}, {4'd0}};

assign tmp_973_fu_1725_p3 = {{a_132_reg_2551}, {3'd0}};

assign tmp_974_fu_1742_p3 = {{a_132_reg_2551}, {1'd0}};

assign tmp_975_fu_2168_p3 = {{a_132_reg_2551}, {2'd0}};

assign tmp_976_fu_1759_p3 = {{a_132_reg_2551}, {4'd0}};

assign tmp_fu_919_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;

assign tmp_fu_919_p3 = {{tmp_fu_919_p1}, {3'd0}};

assign trunc_ln58_fu_2039_p1 = add_ln73_10_fu_1736_p2[11:0];

always @ (posedge ap_clk) begin
    tmp_952_reg_2472[0] <= 1'b0;
    tmp_964_reg_2518[1:0] <= 2'b00;
    tmp_971_reg_2541[1:0] <= 2'b00;
    sub_ln73_1873_reg_2546[1:0] <= 2'b00;
    sub_ln58_3111_reg_2572[2:0] <= 3'b000;
    tmp_960_reg_2602[3:0] <= 4'b0000;
    add_ln73_8_reg_2607[1:0] <= 2'b00;
    add_ln73_9_reg_2612[0] <= 1'b0;
    sub_ln73_1874_reg_2622[1:0] <= 2'b00;
    add_ln58_7773_reg_2682[0] <= 1'b0;
    add_ln58_7781_reg_2692[0] <= 1'b0;
    sub_ln58_3115_reg_2697[2:0] <= 3'b000;
end

endmodule //myproject_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s
