// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer4_out_dout,
        layer4_out_empty_n,
        layer4_out_read,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer5_out_din,
        layer5_out_full_n,
        layer5_out_write,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] layer4_out_dout;
input   layer4_out_empty_n;
output   layer4_out_read;
input  [10:0] layer4_out_num_data_valid;
input  [10:0] layer4_out_fifo_cap;
output  [63:0] layer5_out_din;
input   layer5_out_full_n;
output   layer5_out_write;
input  [8:0] layer5_out_num_data_valid;
input  [8:0] layer5_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer4_out_read;
reg layer5_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_7;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_6;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_5;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_4;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_3;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_2;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_1;
reg   [7:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m;
reg   [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;
reg   [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_13;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_12;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_11;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_10;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_9;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_8;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_7;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_6;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_5;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_4;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_3;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_2;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_1;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_s;
reg   [31:0] sX;
reg   [31:0] pX;
reg   [31:0] sY;
reg   [31:0] pY;
reg    layer4_out_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    layer5_out_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln191_reg_1888;
reg   [0:0] and_ln191_1_reg_1892;
reg   [0:0] icmp_ln24351_reg_251;
reg   [7:0] p_0_0_0_0_09349_reg_262;
reg    ap_block_state1;
wire   [7:0] select_ln241_fu_548_p3;
reg   [7:0] select_ln241_reg_1804;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op270_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln241_1_fu_556_p3;
reg   [7:0] select_ln241_1_reg_1809;
wire   [7:0] select_ln241_2_fu_564_p3;
reg   [7:0] select_ln241_2_reg_1814;
wire   [7:0] select_ln241_3_fu_572_p3;
reg   [7:0] select_ln241_3_reg_1819;
wire   [7:0] select_ln241_4_fu_580_p3;
reg   [7:0] select_ln241_4_reg_1824;
wire   [7:0] select_ln241_5_fu_588_p3;
reg   [7:0] select_ln241_5_reg_1829;
wire   [7:0] select_ln241_6_fu_596_p3;
reg   [7:0] select_ln241_6_reg_1834;
wire   [7:0] trunc_ln247_fu_604_p1;
reg   [7:0] trunc_ln247_reg_1839;
wire   [7:0] trunc_ln247_3_fu_608_p4;
reg   [7:0] trunc_ln247_3_reg_1846;
wire   [7:0] trunc_ln247_4_fu_618_p4;
reg   [7:0] trunc_ln247_4_reg_1852;
wire   [7:0] trunc_ln247_5_fu_628_p4;
reg   [7:0] trunc_ln247_5_reg_1858;
wire   [7:0] trunc_ln247_6_fu_638_p4;
reg   [7:0] trunc_ln247_6_reg_1864;
wire   [7:0] trunc_ln247_7_fu_648_p4;
reg   [7:0] trunc_ln247_7_reg_1870;
wire   [7:0] trunc_ln247_8_fu_658_p4;
reg   [7:0] trunc_ln247_8_reg_1876;
wire   [7:0] trunc_ln247_9_fu_668_p4;
reg   [7:0] trunc_ln247_9_reg_1882;
wire   [0:0] icmp_ln191_fu_682_p2;
wire   [0:0] and_ln191_1_fu_730_p2;
wire   [7:0] select_ln0_fu_775_p3;
reg   [7:0] select_ln0_reg_1896;
wire   [7:0] select_ln0_1_fu_803_p3;
reg   [7:0] select_ln0_1_reg_1902;
wire   [7:0] select_ln0_2_fu_823_p3;
reg   [7:0] select_ln0_2_reg_1908;
wire   [7:0] select_ln0_3_fu_843_p3;
reg   [7:0] select_ln0_3_reg_1914;
wire   [7:0] select_ln0_4_fu_863_p3;
reg   [7:0] select_ln0_4_reg_1920;
wire   [7:0] select_ln0_5_fu_883_p3;
reg   [7:0] select_ln0_5_reg_1926;
wire   [7:0] select_ln0_6_fu_903_p3;
reg   [7:0] select_ln0_6_reg_1932;
wire   [7:0] select_ln0_7_fu_923_p3;
reg   [7:0] select_ln0_7_reg_1938;
wire   [7:0] select_ln0_8_fu_943_p3;
reg   [7:0] select_ln0_8_reg_1944;
wire   [7:0] select_ln0_9_fu_963_p3;
reg   [7:0] select_ln0_9_reg_1950;
wire   [7:0] select_ln0_10_fu_983_p3;
reg   [7:0] select_ln0_10_reg_1956;
wire   [7:0] select_ln0_11_fu_1003_p3;
reg   [7:0] select_ln0_11_reg_1962;
wire   [7:0] select_ln0_12_fu_1023_p3;
reg   [7:0] select_ln0_12_reg_1968;
wire   [7:0] select_ln0_13_fu_1043_p3;
reg   [7:0] select_ln0_13_reg_1974;
wire   [7:0] select_ln0_14_fu_1063_p3;
reg   [7:0] select_ln0_14_reg_1980;
wire   [7:0] select_ln0_15_fu_1083_p3;
reg   [7:0] select_ln0_15_reg_1986;
wire   [0:0] icmp_ln212_fu_1097_p2;
wire   [0:0] icmp_ln216_fu_1151_p2;
wire   [0:0] icmp_ln243_fu_1217_p2;
reg   [0:0] icmp_ln243_reg_2000;
wire   [0:0] icmp_ln241_fu_1223_p2;
reg   [0:0] icmp_ln241_reg_2005;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg   [0:0] ap_phi_mux_icmp_ln24351_phi_fu_255_p4;
reg   [7:0] ap_phi_mux_p_0_0_0_0_09349_phi_fu_265_p4;
reg   [31:0] ap_phi_mux_storemerge_i_i_phi_fu_275_p4;
wire   [31:0] select_ln222_fu_1179_p3;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_i_i_reg_272;
wire    ap_CS_fsm_state4;
wire   [31:0] select_ln227_fu_1115_p3;
wire   [31:0] add_ln212_fu_1091_p2;
wire   [31:0] add_ln216_fu_1145_p2;
reg   [9:0] indvar_flatten8_fu_138;
wire   [9:0] add_ln241_fu_692_p2;
reg   [7:0] p_0_7_0_0_016111_fu_142;
reg   [7:0] p_0_6_0_0_015713_fu_146;
reg   [7:0] p_0_5_0_0_015315_fu_150;
reg   [7:0] p_0_4_0_0_014917_fu_154;
reg   [7:0] p_0_3_0_0_014519_fu_158;
reg   [7:0] p_0_2_0_0_014121_fu_162;
reg   [7:0] p_0_1_0_0_013723_fu_166;
reg   [7:0] p_0_0_0_0_013325_fu_170;
reg   [7:0] p_0_7_0_0_010713026_fu_174;
reg   [7:0] p_0_6_0_0_010512728_fu_178;
reg   [7:0] p_0_5_0_0_010312430_fu_182;
reg   [7:0] p_0_4_0_0_010112132_fu_186;
reg   [7:0] p_0_3_0_0_09911834_fu_190;
reg   [7:0] p_0_2_0_0_09711536_fu_194;
reg   [7:0] p_0_1_0_0_09511238_fu_198;
reg   [7:0] p_0_0_0_0_09310940_fu_202;
reg   [7:0] p_0_7_0_0_010742_fu_206;
reg   [7:0] p_0_6_0_0_010543_fu_210;
reg   [7:0] p_0_5_0_0_010344_fu_214;
reg   [7:0] p_0_4_0_0_010145_fu_218;
reg   [7:0] p_0_3_0_0_09946_fu_222;
reg   [7:0] p_0_2_0_0_09747_fu_226;
reg   [7:0] p_0_1_0_0_09548_fu_230;
reg   [5:0] i_iw_fu_234;
wire   [5:0] i_iw_2_fu_1209_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln191_2_fu_712_p2;
wire   [0:0] icmp_ln191_3_fu_718_p2;
wire   [0:0] and_ln191_fu_724_p2;
wire   [0:0] icmp_ln191_1_fu_702_p2;
wire   [0:0] icmp_ln66_fu_763_p2;
wire   [0:0] xor_ln66_fu_769_p2;
wire   [7:0] select_ln24152_fu_783_p3;
wire   [0:0] icmp_ln66_1_fu_791_p2;
wire   [0:0] xor_ln66_1_fu_797_p2;
wire   [0:0] icmp_ln66_3_fu_811_p2;
wire   [0:0] xor_ln66_3_fu_817_p2;
wire   [0:0] icmp_ln66_4_fu_831_p2;
wire   [0:0] xor_ln66_4_fu_837_p2;
wire   [0:0] icmp_ln66_6_fu_851_p2;
wire   [0:0] xor_ln66_6_fu_857_p2;
wire   [0:0] icmp_ln66_7_fu_871_p2;
wire   [0:0] xor_ln66_7_fu_877_p2;
wire   [0:0] icmp_ln66_9_fu_891_p2;
wire   [0:0] xor_ln66_9_fu_897_p2;
wire   [0:0] icmp_ln66_10_fu_911_p2;
wire   [0:0] xor_ln66_10_fu_917_p2;
wire   [0:0] icmp_ln66_12_fu_931_p2;
wire   [0:0] xor_ln66_12_fu_937_p2;
wire   [0:0] icmp_ln66_13_fu_951_p2;
wire   [0:0] xor_ln66_13_fu_957_p2;
wire   [0:0] icmp_ln66_15_fu_971_p2;
wire   [0:0] xor_ln66_15_fu_977_p2;
wire   [0:0] icmp_ln66_16_fu_991_p2;
wire   [0:0] xor_ln66_16_fu_997_p2;
wire   [0:0] icmp_ln66_18_fu_1011_p2;
wire   [0:0] xor_ln66_18_fu_1017_p2;
wire   [0:0] icmp_ln66_19_fu_1031_p2;
wire   [0:0] xor_ln66_19_fu_1037_p2;
wire   [0:0] icmp_ln66_21_fu_1051_p2;
wire   [0:0] xor_ln66_21_fu_1057_p2;
wire   [0:0] icmp_ln66_22_fu_1071_p2;
wire   [0:0] xor_ln66_22_fu_1077_p2;
wire   [31:0] add_ln227_fu_1109_p2;
wire   [0:0] icmp_ln222_fu_1167_p2;
wire   [31:0] add_ln222_fu_1173_p2;
wire   [5:0] add_ln243_fu_1203_p2;
wire   [0:0] icmp_ln66_2_fu_1354_p2;
wire   [0:0] xor_ln66_2_fu_1358_p2;
wire   [0:0] icmp_ln66_5_fu_1370_p2;
wire   [0:0] xor_ln66_5_fu_1374_p2;
wire   [0:0] icmp_ln66_8_fu_1386_p2;
wire   [0:0] xor_ln66_8_fu_1390_p2;
wire   [0:0] icmp_ln66_11_fu_1402_p2;
wire   [0:0] xor_ln66_11_fu_1406_p2;
wire   [0:0] icmp_ln66_14_fu_1418_p2;
wire   [0:0] xor_ln66_14_fu_1422_p2;
wire   [0:0] icmp_ln66_17_fu_1434_p2;
wire   [0:0] xor_ln66_17_fu_1438_p2;
wire   [0:0] icmp_ln66_20_fu_1450_p2;
wire   [0:0] xor_ln66_20_fu_1454_p2;
wire   [0:0] icmp_ln66_23_fu_1466_p2;
wire   [0:0] xor_ln66_23_fu_1470_p2;
wire   [7:0] res_pack_7_fu_1476_p3;
wire   [7:0] res_pack_6_fu_1460_p3;
wire   [7:0] res_pack_5_fu_1444_p3;
wire   [7:0] res_pack_4_fu_1428_p3;
wire   [7:0] res_pack_3_fu_1412_p3;
wire   [7:0] res_pack_2_fu_1396_p3;
wire   [7:0] res_pack_1_fu_1380_p3;
wire   [7:0] res_pack_fu_1364_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_139;
reg    ap_condition_293;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_7 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_6 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_5 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_4 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_3 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_2 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_1 = 8'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m = 8'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 = 8'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_13 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_12 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_11 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_10 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_9 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_8 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_7 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_6 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_5 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_4 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_3 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_2 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_1 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_s = 8'd0;
#0 sX = 32'd0;
#0 pX = 32'd0;
#0 sY = 32'd0;
#0 pY = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 indvar_flatten8_fu_138 = 10'd0;
#0 p_0_7_0_0_016111_fu_142 = 8'd0;
#0 p_0_6_0_0_015713_fu_146 = 8'd0;
#0 p_0_5_0_0_015315_fu_150 = 8'd0;
#0 p_0_4_0_0_014917_fu_154 = 8'd0;
#0 p_0_3_0_0_014519_fu_158 = 8'd0;
#0 p_0_2_0_0_014121_fu_162 = 8'd0;
#0 p_0_1_0_0_013723_fu_166 = 8'd0;
#0 p_0_0_0_0_013325_fu_170 = 8'd0;
#0 p_0_7_0_0_010713026_fu_174 = 8'd0;
#0 p_0_6_0_0_010512728_fu_178 = 8'd0;
#0 p_0_5_0_0_010312430_fu_182 = 8'd0;
#0 p_0_4_0_0_010112132_fu_186 = 8'd0;
#0 p_0_3_0_0_09911834_fu_190 = 8'd0;
#0 p_0_2_0_0_09711536_fu_194 = 8'd0;
#0 p_0_1_0_0_09511238_fu_198 = 8'd0;
#0 p_0_0_0_0_09310940_fu_202 = 8'd0;
#0 p_0_7_0_0_010742_fu_206 = 8'd0;
#0 p_0_6_0_0_010543_fu_210 = 8'd0;
#0 p_0_5_0_0_010344_fu_214 = 8'd0;
#0 p_0_4_0_0_010145_fu_218 = 8'd0;
#0 p_0_3_0_0_09946_fu_222 = 8'd0;
#0 p_0_2_0_0_09747_fu_226 = 8'd0;
#0 p_0_1_0_0_09548_fu_230 = 8'd0;
#0 i_iw_fu_234 = 6'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_iw_fu_234 <= 6'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_iw_fu_234 <= i_iw_2_fu_1209_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2005 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln24351_reg_251 <= icmp_ln243_reg_2000;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln24351_reg_251 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten8_fu_138 <= 10'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten8_fu_138 <= add_ln241_fu_692_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_139)) begin
        if ((icmp_ln212_fu_1097_p2 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln212_fu_1097_p2 == 1'd0)) begin
            pX <= add_ln212_fu_1091_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_293)) begin
        if ((icmp_ln216_fu_1151_p2 == 1'd1)) begin
            pY <= 32'd0;
        end else if ((icmp_ln216_fu_1151_p2 == 1'd0)) begin
            pY <= add_ln216_fu_1145_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0_0_013325_fu_170 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_7;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0_0_013325_fu_170 <= trunc_ln247_fu_604_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0_0_09310940_fu_202 <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0_0_09310940_fu_202 <= ap_phi_mux_p_0_0_0_0_09349_phi_fu_265_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2005 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0_0_09349_reg_262 <= trunc_ln247_reg_1839;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0_0_09349_reg_262 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_1_0_0_013723_fu_166 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_6;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_013723_fu_166 <= {{layer4_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_1_0_0_09511238_fu_198 <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_09511238_fu_198 <= select_ln241_6_fu_596_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_1_0_0_09548_fu_230 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_6;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_09548_fu_230 <= {{layer4_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_2_0_0_014121_fu_162 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_5;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_2_0_0_014121_fu_162 <= {{layer4_out_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_2_0_0_09711536_fu_194 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_13;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_2_0_0_09711536_fu_194 <= select_ln241_5_fu_588_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_2_0_0_09747_fu_226 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_5;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_2_0_0_09747_fu_226 <= {{layer4_out_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_3_0_0_014519_fu_158 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_4;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_3_0_0_014519_fu_158 <= {{layer4_out_dout[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_3_0_0_09911834_fu_190 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_12;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_3_0_0_09911834_fu_190 <= select_ln241_4_fu_580_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_3_0_0_09946_fu_222 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_4;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_3_0_0_09946_fu_222 <= {{layer4_out_dout[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_4_0_0_010112132_fu_186 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_11;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_4_0_0_010112132_fu_186 <= select_ln241_3_fu_572_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_4_0_0_010145_fu_218 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_4_0_0_010145_fu_218 <= {{layer4_out_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_4_0_0_014917_fu_154 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_4_0_0_014917_fu_154 <= {{layer4_out_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_5_0_0_010312430_fu_182 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_10;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_5_0_0_010312430_fu_182 <= select_ln241_2_fu_564_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_5_0_0_010344_fu_214 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_5_0_0_010344_fu_214 <= {{layer4_out_dout[47:40]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_5_0_0_015315_fu_150 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_5_0_0_015315_fu_150 <= {{layer4_out_dout[47:40]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_6_0_0_010512728_fu_178 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_9;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_6_0_0_010512728_fu_178 <= select_ln241_1_fu_556_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_6_0_0_010543_fu_210 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_6_0_0_010543_fu_210 <= {{layer4_out_dout[55:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_6_0_0_015713_fu_146 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_6_0_0_015713_fu_146 <= {{layer4_out_dout[55:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_7_0_0_010713026_fu_174 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_8;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_7_0_0_010713026_fu_174 <= select_ln241_fu_548_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_7_0_0_010742_fu_206 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_7_0_0_010742_fu_206 <= {{layer4_out_dout[63:56]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_7_0_0_016111_fu_142 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_s;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_7_0_0_016111_fu_142 <= {{layer4_out_dout[63:56]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_139)) begin
        if ((icmp_ln212_fu_1097_p2 == 1'd1)) begin
            sX <= 32'd0;
        end else if ((icmp_ln212_fu_1097_p2 == 1'd0)) begin
            sX <= select_ln227_fu_1115_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln191_1_reg_1892 <= and_ln191_1_fu_730_p2;
        icmp_ln191_reg_1888 <= icmp_ln191_fu_682_p2;
        icmp_ln241_reg_2005 <= icmp_ln241_fu_1223_p2;
        select_ln0_10_reg_1956 <= select_ln0_10_fu_983_p3;
        select_ln0_11_reg_1962 <= select_ln0_11_fu_1003_p3;
        select_ln0_12_reg_1968 <= select_ln0_12_fu_1023_p3;
        select_ln0_13_reg_1974 <= select_ln0_13_fu_1043_p3;
        select_ln0_14_reg_1980 <= select_ln0_14_fu_1063_p3;
        select_ln0_15_reg_1986 <= select_ln0_15_fu_1083_p3;
        select_ln0_1_reg_1902 <= select_ln0_1_fu_803_p3;
        select_ln0_2_reg_1908 <= select_ln0_2_fu_823_p3;
        select_ln0_3_reg_1914 <= select_ln0_3_fu_843_p3;
        select_ln0_4_reg_1920 <= select_ln0_4_fu_863_p3;
        select_ln0_5_reg_1926 <= select_ln0_5_fu_883_p3;
        select_ln0_6_reg_1932 <= select_ln0_6_fu_903_p3;
        select_ln0_7_reg_1938 <= select_ln0_7_fu_923_p3;
        select_ln0_8_reg_1944 <= select_ln0_8_fu_943_p3;
        select_ln0_9_reg_1950 <= select_ln0_9_fu_963_p3;
        select_ln0_reg_1896 <= select_ln0_fu_775_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln243_reg_2000 <= icmp_ln243_fu_1217_p2;
        select_ln241_1_reg_1809 <= select_ln241_1_fu_556_p3;
        select_ln241_2_reg_1814 <= select_ln241_2_fu_564_p3;
        select_ln241_3_reg_1819 <= select_ln241_3_fu_572_p3;
        select_ln241_4_reg_1824 <= select_ln241_4_fu_580_p3;
        select_ln241_5_reg_1829 <= select_ln241_5_fu_588_p3;
        select_ln241_6_reg_1834 <= select_ln241_6_fu_596_p3;
        select_ln241_reg_1804 <= select_ln241_fu_548_p3;
        trunc_ln247_3_reg_1846 <= {{layer4_out_dout[15:8]}};
        trunc_ln247_4_reg_1852 <= {{layer4_out_dout[23:16]}};
        trunc_ln247_5_reg_1858 <= {{layer4_out_dout[31:24]}};
        trunc_ln247_6_reg_1864 <= {{layer4_out_dout[39:32]}};
        trunc_ln247_7_reg_1870 <= {{layer4_out_dout[47:40]}};
        trunc_ln247_8_reg_1876 <= {{layer4_out_dout[55:48]}};
        trunc_ln247_9_reg_1882 <= {{layer4_out_dout[63:56]}};
        trunc_ln247_reg_1839 <= trunc_ln247_fu_604_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m <= trunc_ln247_9_reg_1882;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_1 <= trunc_ln247_8_reg_1876;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_2 <= trunc_ln247_7_reg_1870;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_3 <= trunc_ln247_6_reg_1864;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_4 <= trunc_ln247_5_reg_1858;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_5 <= trunc_ln247_4_reg_1852;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_6 <= trunc_ln247_3_reg_1846;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_o_m_7 <= trunc_ln247_reg_1839;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_1 <= trunc_ln247_8_reg_1876;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_10 <= select_ln241_2_reg_1814;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_11 <= select_ln241_3_reg_1819;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_12 <= select_ln241_4_reg_1824;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_13 <= select_ln241_5_reg_1829;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_2 <= trunc_ln247_7_reg_1870;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_3 <= trunc_ln247_6_reg_1864;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_4 <= trunc_ln247_5_reg_1858;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_5 <= trunc_ln247_4_reg_1852;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_6 <= trunc_ln247_3_reg_1846;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_7 <= trunc_ln247_reg_1839;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_8 <= select_ln241_reg_1804;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_9 <= select_ln241_1_reg_1809;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi8ELi3EL9ap_q_mode5EL9ap_s <= trunc_ln247_9_reg_1882;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel <= select_ln241_6_reg_1834;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 <= p_0_0_0_0_09349_reg_262;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln212_fu_1097_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sY <= ap_phi_mux_storemerge_i_i_phi_fu_275_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln241_fu_1223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln241_reg_2005 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_icmp_ln24351_phi_fu_255_p4 = icmp_ln243_reg_2000;
    end else begin
        ap_phi_mux_icmp_ln24351_phi_fu_255_p4 = icmp_ln24351_reg_251;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln241_reg_2005 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_0_0_0_0_09349_phi_fu_265_p4 = trunc_ln247_reg_1839;
    end else begin
        ap_phi_mux_p_0_0_0_0_09349_phi_fu_265_p4 = p_0_0_0_0_09349_reg_262;
    end
end

always @ (*) begin
    if ((icmp_ln212_fu_1097_p2 == 1'd1)) begin
        if ((icmp_ln216_fu_1151_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_i_i_phi_fu_275_p4 = 32'd0;
        end else if ((icmp_ln216_fu_1151_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_i_i_phi_fu_275_p4 = select_ln222_fu_1179_p3;
        end else begin
            ap_phi_mux_storemerge_i_i_phi_fu_275_p4 = ap_phi_reg_pp0_iter0_storemerge_i_i_reg_272;
        end
    end else begin
        ap_phi_mux_storemerge_i_i_phi_fu_275_p4 = ap_phi_reg_pp0_iter0_storemerge_i_i_reg_272;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln191_reg_1888 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln191_1_reg_1892))) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op270_write_state3 == 1'b1))) begin
        layer5_out_write = 1'b1;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln212_fu_1091_p2 = (pX + 32'd1);

assign add_ln216_fu_1145_p2 = (pY + 32'd1);

assign add_ln222_fu_1173_p2 = (sY + 32'd1);

assign add_ln227_fu_1109_p2 = (sX + 32'd1);

assign add_ln241_fu_692_p2 = (indvar_flatten8_fu_138 + 10'd1);

assign add_ln243_fu_1203_p2 = (i_iw_fu_234 + 6'd1);

assign and_ln191_1_fu_730_p2 = (icmp_ln191_1_fu_702_p2 & and_ln191_fu_724_p2);

assign and_ln191_fu_724_p2 = (icmp_ln191_3_fu_718_p2 & icmp_ln191_2_fu_712_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (layer4_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((layer5_out_full_n == 1'b0) & (ap_predicate_op270_write_state3 == 1'b1));
end

always @ (*) begin
    ap_condition_139 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_293 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln212_fu_1097_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_storemerge_i_i_reg_272 = 'bx;

always @ (*) begin
    ap_predicate_op270_write_state3 = ((icmp_ln191_reg_1888 == 1'd1) & (1'd1 == and_ln191_1_reg_1892));
end

assign ap_ready = internal_ap_ready;

assign i_iw_2_fu_1209_p3 = ((ap_phi_mux_icmp_ln24351_phi_fu_255_p4[0:0] == 1'b1) ? 6'd1 : add_ln243_fu_1203_p2);

assign icmp_ln191_1_fu_702_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln191_2_fu_712_p2 = (($signed(pY) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln191_3_fu_718_p2 = (($signed(pX) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_682_p2 = ((sX == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln212_fu_1097_p2 = ((add_ln212_fu_1091_p2 == 32'd61) ? 1'b1 : 1'b0);

assign icmp_ln216_fu_1151_p2 = ((add_ln216_fu_1145_p2 == 32'd11) ? 1'b1 : 1'b0);

assign icmp_ln222_fu_1167_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_1223_p2 = ((indvar_flatten8_fu_138 == 10'd670) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_1217_p2 = ((i_iw_2_fu_1209_p3 == 6'd61) ? 1'b1 : 1'b0);

assign icmp_ln66_10_fu_911_p2 = (($signed(p_0_3_0_0_014519_fu_158) < $signed(trunc_ln247_5_fu_628_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_11_fu_1402_p2 = (($signed(select_ln0_6_reg_1932) < $signed(select_ln0_7_reg_1938)) ? 1'b1 : 1'b0);

assign icmp_ln66_12_fu_931_p2 = (($signed(p_0_4_0_0_010112132_fu_186) < $signed(select_ln241_3_fu_572_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_13_fu_951_p2 = (($signed(p_0_4_0_0_014917_fu_154) < $signed(trunc_ln247_6_fu_638_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_14_fu_1418_p2 = (($signed(select_ln0_8_reg_1944) < $signed(select_ln0_9_reg_1950)) ? 1'b1 : 1'b0);

assign icmp_ln66_15_fu_971_p2 = (($signed(p_0_5_0_0_010312430_fu_182) < $signed(select_ln241_2_fu_564_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_16_fu_991_p2 = (($signed(p_0_5_0_0_015315_fu_150) < $signed(trunc_ln247_7_fu_648_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_17_fu_1434_p2 = (($signed(select_ln0_10_reg_1956) < $signed(select_ln0_11_reg_1962)) ? 1'b1 : 1'b0);

assign icmp_ln66_18_fu_1011_p2 = (($signed(p_0_6_0_0_010512728_fu_178) < $signed(select_ln241_1_fu_556_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_19_fu_1031_p2 = (($signed(p_0_6_0_0_015713_fu_146) < $signed(trunc_ln247_8_fu_658_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_1_fu_791_p2 = (($signed(select_ln24152_fu_783_p3) < $signed(trunc_ln247_fu_604_p1)) ? 1'b1 : 1'b0);

assign icmp_ln66_20_fu_1450_p2 = (($signed(select_ln0_12_reg_1968) < $signed(select_ln0_13_reg_1974)) ? 1'b1 : 1'b0);

assign icmp_ln66_21_fu_1051_p2 = (($signed(p_0_7_0_0_010713026_fu_174) < $signed(select_ln241_fu_548_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_22_fu_1071_p2 = (($signed(p_0_7_0_0_016111_fu_142) < $signed(trunc_ln247_9_fu_668_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_23_fu_1466_p2 = (($signed(select_ln0_14_reg_1980) < $signed(select_ln0_15_reg_1986)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_1354_p2 = (($signed(select_ln0_reg_1896) < $signed(select_ln0_1_reg_1902)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_811_p2 = (($signed(p_0_1_0_0_09511238_fu_198) < $signed(select_ln241_6_fu_596_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_4_fu_831_p2 = (($signed(p_0_1_0_0_013723_fu_166) < $signed(trunc_ln247_3_fu_608_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_5_fu_1370_p2 = (($signed(select_ln0_2_reg_1908) < $signed(select_ln0_3_reg_1914)) ? 1'b1 : 1'b0);

assign icmp_ln66_6_fu_851_p2 = (($signed(p_0_2_0_0_09711536_fu_194) < $signed(select_ln241_5_fu_588_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_7_fu_871_p2 = (($signed(p_0_2_0_0_014121_fu_162) < $signed(trunc_ln247_4_fu_618_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_8_fu_1386_p2 = (($signed(select_ln0_4_reg_1920) < $signed(select_ln0_5_reg_1926)) ? 1'b1 : 1'b0);

assign icmp_ln66_9_fu_891_p2 = (($signed(p_0_3_0_0_09911834_fu_190) < $signed(select_ln241_4_fu_580_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_763_p2 = (($signed(p_0_0_0_0_09310940_fu_202) < $signed(ap_phi_mux_p_0_0_0_0_09349_phi_fu_265_p4)) ? 1'b1 : 1'b0);

assign layer5_out_din = {{{{{{{{res_pack_7_fu_1476_p3}, {res_pack_6_fu_1460_p3}}, {res_pack_5_fu_1444_p3}}, {res_pack_4_fu_1428_p3}}, {res_pack_3_fu_1412_p3}}, {res_pack_2_fu_1396_p3}}, {res_pack_1_fu_1380_p3}}, {res_pack_fu_1364_p3}};

assign res_pack_1_fu_1380_p3 = ((xor_ln66_5_fu_1374_p2[0:0] == 1'b1) ? select_ln0_2_reg_1908 : select_ln0_3_reg_1914);

assign res_pack_2_fu_1396_p3 = ((xor_ln66_8_fu_1390_p2[0:0] == 1'b1) ? select_ln0_4_reg_1920 : select_ln0_5_reg_1926);

assign res_pack_3_fu_1412_p3 = ((xor_ln66_11_fu_1406_p2[0:0] == 1'b1) ? select_ln0_6_reg_1932 : select_ln0_7_reg_1938);

assign res_pack_4_fu_1428_p3 = ((xor_ln66_14_fu_1422_p2[0:0] == 1'b1) ? select_ln0_8_reg_1944 : select_ln0_9_reg_1950);

assign res_pack_5_fu_1444_p3 = ((xor_ln66_17_fu_1438_p2[0:0] == 1'b1) ? select_ln0_10_reg_1956 : select_ln0_11_reg_1962);

assign res_pack_6_fu_1460_p3 = ((xor_ln66_20_fu_1454_p2[0:0] == 1'b1) ? select_ln0_12_reg_1968 : select_ln0_13_reg_1974);

assign res_pack_7_fu_1476_p3 = ((xor_ln66_23_fu_1470_p2[0:0] == 1'b1) ? select_ln0_14_reg_1980 : select_ln0_15_reg_1986);

assign res_pack_fu_1364_p3 = ((xor_ln66_2_fu_1358_p2[0:0] == 1'b1) ? select_ln0_reg_1896 : select_ln0_1_reg_1902);

assign select_ln0_10_fu_983_p3 = ((xor_ln66_15_fu_977_p2[0:0] == 1'b1) ? p_0_5_0_0_010312430_fu_182 : select_ln241_2_fu_564_p3);

assign select_ln0_11_fu_1003_p3 = ((xor_ln66_16_fu_997_p2[0:0] == 1'b1) ? p_0_5_0_0_015315_fu_150 : trunc_ln247_7_fu_648_p4);

assign select_ln0_12_fu_1023_p3 = ((xor_ln66_18_fu_1017_p2[0:0] == 1'b1) ? p_0_6_0_0_010512728_fu_178 : select_ln241_1_fu_556_p3);

assign select_ln0_13_fu_1043_p3 = ((xor_ln66_19_fu_1037_p2[0:0] == 1'b1) ? p_0_6_0_0_015713_fu_146 : trunc_ln247_8_fu_658_p4);

assign select_ln0_14_fu_1063_p3 = ((xor_ln66_21_fu_1057_p2[0:0] == 1'b1) ? p_0_7_0_0_010713026_fu_174 : select_ln241_fu_548_p3);

assign select_ln0_15_fu_1083_p3 = ((xor_ln66_22_fu_1077_p2[0:0] == 1'b1) ? p_0_7_0_0_016111_fu_142 : trunc_ln247_9_fu_668_p4);

assign select_ln0_1_fu_803_p3 = ((xor_ln66_1_fu_797_p2[0:0] == 1'b1) ? select_ln24152_fu_783_p3 : trunc_ln247_fu_604_p1);

assign select_ln0_2_fu_823_p3 = ((xor_ln66_3_fu_817_p2[0:0] == 1'b1) ? p_0_1_0_0_09511238_fu_198 : select_ln241_6_fu_596_p3);

assign select_ln0_3_fu_843_p3 = ((xor_ln66_4_fu_837_p2[0:0] == 1'b1) ? p_0_1_0_0_013723_fu_166 : trunc_ln247_3_fu_608_p4);

assign select_ln0_4_fu_863_p3 = ((xor_ln66_6_fu_857_p2[0:0] == 1'b1) ? p_0_2_0_0_09711536_fu_194 : select_ln241_5_fu_588_p3);

assign select_ln0_5_fu_883_p3 = ((xor_ln66_7_fu_877_p2[0:0] == 1'b1) ? p_0_2_0_0_014121_fu_162 : trunc_ln247_4_fu_618_p4);

assign select_ln0_6_fu_903_p3 = ((xor_ln66_9_fu_897_p2[0:0] == 1'b1) ? p_0_3_0_0_09911834_fu_190 : select_ln241_4_fu_580_p3);

assign select_ln0_7_fu_923_p3 = ((xor_ln66_10_fu_917_p2[0:0] == 1'b1) ? p_0_3_0_0_014519_fu_158 : trunc_ln247_5_fu_628_p4);

assign select_ln0_8_fu_943_p3 = ((xor_ln66_12_fu_937_p2[0:0] == 1'b1) ? p_0_4_0_0_010112132_fu_186 : select_ln241_3_fu_572_p3);

assign select_ln0_9_fu_963_p3 = ((xor_ln66_13_fu_957_p2[0:0] == 1'b1) ? p_0_4_0_0_014917_fu_154 : trunc_ln247_6_fu_638_p4);

assign select_ln0_fu_775_p3 = ((xor_ln66_fu_769_p2[0:0] == 1'b1) ? p_0_0_0_0_09310940_fu_202 : ap_phi_mux_p_0_0_0_0_09349_phi_fu_265_p4);

assign select_ln222_fu_1179_p3 = ((icmp_ln222_fu_1167_p2[0:0] == 1'b1) ? 32'd0 : add_ln222_fu_1173_p2);

assign select_ln227_fu_1115_p3 = ((icmp_ln191_fu_682_p2[0:0] == 1'b1) ? 32'd0 : add_ln227_fu_1109_p2);

assign select_ln24152_fu_783_p3 = ((ap_phi_mux_icmp_ln24351_phi_fu_255_p4[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0_0_09349_phi_fu_265_p4 : p_0_0_0_0_013325_fu_170);

assign select_ln241_1_fu_556_p3 = ((ap_phi_mux_icmp_ln24351_phi_fu_255_p4[0:0] == 1'b1) ? p_0_6_0_0_015713_fu_146 : p_0_6_0_0_010543_fu_210);

assign select_ln241_2_fu_564_p3 = ((ap_phi_mux_icmp_ln24351_phi_fu_255_p4[0:0] == 1'b1) ? p_0_5_0_0_015315_fu_150 : p_0_5_0_0_010344_fu_214);

assign select_ln241_3_fu_572_p3 = ((ap_phi_mux_icmp_ln24351_phi_fu_255_p4[0:0] == 1'b1) ? p_0_4_0_0_014917_fu_154 : p_0_4_0_0_010145_fu_218);

assign select_ln241_4_fu_580_p3 = ((ap_phi_mux_icmp_ln24351_phi_fu_255_p4[0:0] == 1'b1) ? p_0_3_0_0_014519_fu_158 : p_0_3_0_0_09946_fu_222);

assign select_ln241_5_fu_588_p3 = ((ap_phi_mux_icmp_ln24351_phi_fu_255_p4[0:0] == 1'b1) ? p_0_2_0_0_014121_fu_162 : p_0_2_0_0_09747_fu_226);

assign select_ln241_6_fu_596_p3 = ((ap_phi_mux_icmp_ln24351_phi_fu_255_p4[0:0] == 1'b1) ? p_0_1_0_0_013723_fu_166 : p_0_1_0_0_09548_fu_230);

assign select_ln241_fu_548_p3 = ((ap_phi_mux_icmp_ln24351_phi_fu_255_p4[0:0] == 1'b1) ? p_0_7_0_0_016111_fu_142 : p_0_7_0_0_010742_fu_206);

assign start_out = real_start;

assign trunc_ln247_3_fu_608_p4 = {{layer4_out_dout[15:8]}};

assign trunc_ln247_4_fu_618_p4 = {{layer4_out_dout[23:16]}};

assign trunc_ln247_5_fu_628_p4 = {{layer4_out_dout[31:24]}};

assign trunc_ln247_6_fu_638_p4 = {{layer4_out_dout[39:32]}};

assign trunc_ln247_7_fu_648_p4 = {{layer4_out_dout[47:40]}};

assign trunc_ln247_8_fu_658_p4 = {{layer4_out_dout[55:48]}};

assign trunc_ln247_9_fu_668_p4 = {{layer4_out_dout[63:56]}};

assign trunc_ln247_fu_604_p1 = layer4_out_dout[7:0];

assign xor_ln66_10_fu_917_p2 = (icmp_ln66_10_fu_911_p2 ^ 1'd1);

assign xor_ln66_11_fu_1406_p2 = (icmp_ln66_11_fu_1402_p2 ^ 1'd1);

assign xor_ln66_12_fu_937_p2 = (icmp_ln66_12_fu_931_p2 ^ 1'd1);

assign xor_ln66_13_fu_957_p2 = (icmp_ln66_13_fu_951_p2 ^ 1'd1);

assign xor_ln66_14_fu_1422_p2 = (icmp_ln66_14_fu_1418_p2 ^ 1'd1);

assign xor_ln66_15_fu_977_p2 = (icmp_ln66_15_fu_971_p2 ^ 1'd1);

assign xor_ln66_16_fu_997_p2 = (icmp_ln66_16_fu_991_p2 ^ 1'd1);

assign xor_ln66_17_fu_1438_p2 = (icmp_ln66_17_fu_1434_p2 ^ 1'd1);

assign xor_ln66_18_fu_1017_p2 = (icmp_ln66_18_fu_1011_p2 ^ 1'd1);

assign xor_ln66_19_fu_1037_p2 = (icmp_ln66_19_fu_1031_p2 ^ 1'd1);

assign xor_ln66_1_fu_797_p2 = (icmp_ln66_1_fu_791_p2 ^ 1'd1);

assign xor_ln66_20_fu_1454_p2 = (icmp_ln66_20_fu_1450_p2 ^ 1'd1);

assign xor_ln66_21_fu_1057_p2 = (icmp_ln66_21_fu_1051_p2 ^ 1'd1);

assign xor_ln66_22_fu_1077_p2 = (icmp_ln66_22_fu_1071_p2 ^ 1'd1);

assign xor_ln66_23_fu_1470_p2 = (icmp_ln66_23_fu_1466_p2 ^ 1'd1);

assign xor_ln66_2_fu_1358_p2 = (icmp_ln66_2_fu_1354_p2 ^ 1'd1);

assign xor_ln66_3_fu_817_p2 = (icmp_ln66_3_fu_811_p2 ^ 1'd1);

assign xor_ln66_4_fu_837_p2 = (icmp_ln66_4_fu_831_p2 ^ 1'd1);

assign xor_ln66_5_fu_1374_p2 = (icmp_ln66_5_fu_1370_p2 ^ 1'd1);

assign xor_ln66_6_fu_857_p2 = (icmp_ln66_6_fu_851_p2 ^ 1'd1);

assign xor_ln66_7_fu_877_p2 = (icmp_ln66_7_fu_871_p2 ^ 1'd1);

assign xor_ln66_8_fu_1390_p2 = (icmp_ln66_8_fu_1386_p2 ^ 1'd1);

assign xor_ln66_9_fu_897_p2 = (icmp_ln66_9_fu_891_p2 ^ 1'd1);

assign xor_ln66_fu_769_p2 = (icmp_ln66_fu_763_p2 ^ 1'd1);

endmodule //myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_8_3_5_3_0_8u_config5_s
