// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer6_out_dout,
        layer6_out_empty_n,
        layer6_out_read,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer8_out_din,
        layer8_out_full_n,
        layer8_out_write,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [383:0] layer6_out_dout;
input   layer6_out_empty_n;
output   layer6_out_read;
input  [8:0] layer6_out_num_data_valid;
input  [8:0] layer6_out_fifo_cap;
output  [127:0] layer8_out_din;
input   layer8_out_full_n;
output   layer8_out_write;
input  [31:0] layer8_out_num_data_valid;
input  [31:0] layer8_out_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg layer6_out_read;
reg layer8_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_737_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer6_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    layer8_out_blk_n;
wire   [7:0] select_ln51_fu_363_p3;
reg   [7:0] select_ln51_reg_776;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [7:0] select_ln51_32_fu_387_p3;
reg   [7:0] select_ln51_32_reg_781;
wire   [7:0] select_ln51_33_fu_411_p3;
reg   [7:0] select_ln51_33_reg_786;
wire   [7:0] select_ln51_34_fu_435_p3;
reg   [7:0] select_ln51_34_reg_791;
wire   [7:0] select_ln51_35_fu_459_p3;
reg   [7:0] select_ln51_35_reg_796;
wire   [7:0] select_ln51_36_fu_483_p3;
reg   [7:0] select_ln51_36_reg_801;
wire   [7:0] select_ln51_37_fu_507_p3;
reg   [7:0] select_ln51_37_reg_806;
wire   [7:0] select_ln51_38_fu_531_p3;
reg   [7:0] select_ln51_38_reg_811;
wire   [7:0] select_ln51_39_fu_555_p3;
reg   [7:0] select_ln51_39_reg_816;
wire   [7:0] select_ln51_40_fu_579_p3;
reg   [7:0] select_ln51_40_reg_821;
wire   [7:0] select_ln51_41_fu_603_p3;
reg   [7:0] select_ln51_41_reg_826;
wire   [7:0] select_ln51_42_fu_627_p3;
reg   [7:0] select_ln51_42_reg_831;
wire   [7:0] select_ln51_43_fu_651_p3;
reg   [7:0] select_ln51_43_reg_836;
wire   [7:0] select_ln51_44_fu_675_p3;
reg   [7:0] select_ln51_44_reg_841;
wire   [7:0] select_ln51_45_fu_699_p3;
reg   [7:0] select_ln51_45_reg_846;
wire   [7:0] select_ln51_46_fu_723_p3;
reg   [7:0] select_ln51_46_reg_851;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] i_fu_168;
wire   [7:0] i_12_fu_731_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_11;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [23:0] trunc_ln44_fu_193_p1;
wire   [0:0] icmp_ln51_fu_347_p2;
wire   [7:0] trunc_ln3_fu_353_p4;
wire   [23:0] trunc_ln44_s_fu_197_p4;
wire   [0:0] icmp_ln51_32_fu_371_p2;
wire   [7:0] trunc_ln52_s_fu_377_p4;
wire   [23:0] trunc_ln44_31_fu_207_p4;
wire   [0:0] icmp_ln51_33_fu_395_p2;
wire   [7:0] trunc_ln52_31_fu_401_p4;
wire   [23:0] trunc_ln44_32_fu_217_p4;
wire   [0:0] icmp_ln51_34_fu_419_p2;
wire   [7:0] trunc_ln52_32_fu_425_p4;
wire   [23:0] trunc_ln44_33_fu_227_p4;
wire   [0:0] icmp_ln51_35_fu_443_p2;
wire   [7:0] trunc_ln52_33_fu_449_p4;
wire   [23:0] trunc_ln44_34_fu_237_p4;
wire   [0:0] icmp_ln51_36_fu_467_p2;
wire   [7:0] trunc_ln52_34_fu_473_p4;
wire   [23:0] trunc_ln44_35_fu_247_p4;
wire   [0:0] icmp_ln51_37_fu_491_p2;
wire   [7:0] trunc_ln52_35_fu_497_p4;
wire   [23:0] trunc_ln44_36_fu_257_p4;
wire   [0:0] icmp_ln51_38_fu_515_p2;
wire   [7:0] trunc_ln52_36_fu_521_p4;
wire   [23:0] trunc_ln44_37_fu_267_p4;
wire   [0:0] icmp_ln51_39_fu_539_p2;
wire   [7:0] trunc_ln52_37_fu_545_p4;
wire   [23:0] trunc_ln44_38_fu_277_p4;
wire   [0:0] icmp_ln51_40_fu_563_p2;
wire   [7:0] trunc_ln52_38_fu_569_p4;
wire   [23:0] trunc_ln44_39_fu_287_p4;
wire   [0:0] icmp_ln51_41_fu_587_p2;
wire   [7:0] trunc_ln52_39_fu_593_p4;
wire   [23:0] trunc_ln44_40_fu_297_p4;
wire   [0:0] icmp_ln51_42_fu_611_p2;
wire   [7:0] trunc_ln52_40_fu_617_p4;
wire   [23:0] trunc_ln44_41_fu_307_p4;
wire   [0:0] icmp_ln51_43_fu_635_p2;
wire   [7:0] trunc_ln52_41_fu_641_p4;
wire   [23:0] trunc_ln44_42_fu_317_p4;
wire   [0:0] icmp_ln51_44_fu_659_p2;
wire   [7:0] trunc_ln52_42_fu_665_p4;
wire   [23:0] trunc_ln44_43_fu_327_p4;
wire   [0:0] icmp_ln51_45_fu_683_p2;
wire   [7:0] trunc_ln52_43_fu_689_p4;
wire   [23:0] trunc_ln44_44_fu_337_p4;
wire   [0:0] icmp_ln51_46_fu_707_p2;
wire   [7:0] trunc_ln52_44_fu_713_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_145;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_168 = 8'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_145)) begin
        i_fu_168 <= i_12_fu_731_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln51_32_reg_781 <= select_ln51_32_fu_387_p3;
        select_ln51_33_reg_786 <= select_ln51_33_fu_411_p3;
        select_ln51_34_reg_791 <= select_ln51_34_fu_435_p3;
        select_ln51_35_reg_796 <= select_ln51_35_fu_459_p3;
        select_ln51_36_reg_801 <= select_ln51_36_fu_483_p3;
        select_ln51_37_reg_806 <= select_ln51_37_fu_507_p3;
        select_ln51_38_reg_811 <= select_ln51_38_fu_531_p3;
        select_ln51_39_reg_816 <= select_ln51_39_fu_555_p3;
        select_ln51_40_reg_821 <= select_ln51_40_fu_579_p3;
        select_ln51_41_reg_826 <= select_ln51_41_fu_603_p3;
        select_ln51_42_reg_831 <= select_ln51_42_fu_627_p3;
        select_ln51_43_reg_836 <= select_ln51_43_fu_651_p3;
        select_ln51_44_reg_841 <= select_ln51_44_fu_675_p3;
        select_ln51_45_reg_846 <= select_ln51_45_fu_699_p3;
        select_ln51_46_reg_851 <= select_ln51_46_fu_723_p3;
        select_ln51_reg_776 <= select_ln51_fu_363_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_737_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_11 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_11 = i_fu_168;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_read = 1'b1;
    end else begin
        layer6_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_blk_n = layer8_out_full_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_write = 1'b1;
    end else begin
        layer8_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((ap_done_reg == 1'b1) | (layer6_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_145 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_12_fu_731_p2 = (ap_sig_allocacmp_i_11 + 8'd1);

assign icmp_ln41_fu_737_p2 = ((ap_sig_allocacmp_i_11 == 8'd149) ? 1'b1 : 1'b0);

assign icmp_ln51_32_fu_371_p2 = (($signed(trunc_ln44_s_fu_197_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_395_p2 = (($signed(trunc_ln44_31_fu_207_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_419_p2 = (($signed(trunc_ln44_32_fu_217_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_35_fu_443_p2 = (($signed(trunc_ln44_33_fu_227_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_36_fu_467_p2 = (($signed(trunc_ln44_34_fu_237_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_37_fu_491_p2 = (($signed(trunc_ln44_35_fu_247_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_38_fu_515_p2 = (($signed(trunc_ln44_36_fu_257_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_39_fu_539_p2 = (($signed(trunc_ln44_37_fu_267_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_40_fu_563_p2 = (($signed(trunc_ln44_38_fu_277_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_41_fu_587_p2 = (($signed(trunc_ln44_39_fu_287_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_42_fu_611_p2 = (($signed(trunc_ln44_40_fu_297_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_43_fu_635_p2 = (($signed(trunc_ln44_41_fu_307_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_44_fu_659_p2 = (($signed(trunc_ln44_42_fu_317_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_45_fu_683_p2 = (($signed(trunc_ln44_43_fu_327_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_46_fu_707_p2 = (($signed(trunc_ln44_44_fu_337_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_347_p2 = (($signed(trunc_ln44_fu_193_p1) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign layer8_out_din = {{{{{{{{{{{{{{{{select_ln51_46_reg_851}, {select_ln51_45_reg_846}}, {select_ln51_44_reg_841}}, {select_ln51_43_reg_836}}, {select_ln51_42_reg_831}}, {select_ln51_41_reg_826}}, {select_ln51_40_reg_821}}, {select_ln51_39_reg_816}}, {select_ln51_38_reg_811}}, {select_ln51_37_reg_806}}, {select_ln51_36_reg_801}}, {select_ln51_35_reg_796}}, {select_ln51_34_reg_791}}, {select_ln51_33_reg_786}}, {select_ln51_32_reg_781}}, {select_ln51_reg_776}};

assign select_ln51_32_fu_387_p3 = ((icmp_ln51_32_fu_371_p2[0:0] == 1'b1) ? trunc_ln52_s_fu_377_p4 : 8'd0);

assign select_ln51_33_fu_411_p3 = ((icmp_ln51_33_fu_395_p2[0:0] == 1'b1) ? trunc_ln52_31_fu_401_p4 : 8'd0);

assign select_ln51_34_fu_435_p3 = ((icmp_ln51_34_fu_419_p2[0:0] == 1'b1) ? trunc_ln52_32_fu_425_p4 : 8'd0);

assign select_ln51_35_fu_459_p3 = ((icmp_ln51_35_fu_443_p2[0:0] == 1'b1) ? trunc_ln52_33_fu_449_p4 : 8'd0);

assign select_ln51_36_fu_483_p3 = ((icmp_ln51_36_fu_467_p2[0:0] == 1'b1) ? trunc_ln52_34_fu_473_p4 : 8'd0);

assign select_ln51_37_fu_507_p3 = ((icmp_ln51_37_fu_491_p2[0:0] == 1'b1) ? trunc_ln52_35_fu_497_p4 : 8'd0);

assign select_ln51_38_fu_531_p3 = ((icmp_ln51_38_fu_515_p2[0:0] == 1'b1) ? trunc_ln52_36_fu_521_p4 : 8'd0);

assign select_ln51_39_fu_555_p3 = ((icmp_ln51_39_fu_539_p2[0:0] == 1'b1) ? trunc_ln52_37_fu_545_p4 : 8'd0);

assign select_ln51_40_fu_579_p3 = ((icmp_ln51_40_fu_563_p2[0:0] == 1'b1) ? trunc_ln52_38_fu_569_p4 : 8'd0);

assign select_ln51_41_fu_603_p3 = ((icmp_ln51_41_fu_587_p2[0:0] == 1'b1) ? trunc_ln52_39_fu_593_p4 : 8'd0);

assign select_ln51_42_fu_627_p3 = ((icmp_ln51_42_fu_611_p2[0:0] == 1'b1) ? trunc_ln52_40_fu_617_p4 : 8'd0);

assign select_ln51_43_fu_651_p3 = ((icmp_ln51_43_fu_635_p2[0:0] == 1'b1) ? trunc_ln52_41_fu_641_p4 : 8'd0);

assign select_ln51_44_fu_675_p3 = ((icmp_ln51_44_fu_659_p2[0:0] == 1'b1) ? trunc_ln52_42_fu_665_p4 : 8'd0);

assign select_ln51_45_fu_699_p3 = ((icmp_ln51_45_fu_683_p2[0:0] == 1'b1) ? trunc_ln52_43_fu_689_p4 : 8'd0);

assign select_ln51_46_fu_723_p3 = ((icmp_ln51_46_fu_707_p2[0:0] == 1'b1) ? trunc_ln52_44_fu_713_p4 : 8'd0);

assign select_ln51_fu_363_p3 = ((icmp_ln51_fu_347_p2[0:0] == 1'b1) ? trunc_ln3_fu_353_p4 : 8'd0);

assign start_out = real_start;

assign trunc_ln3_fu_353_p4 = {{layer6_out_dout[12:5]}};

assign trunc_ln44_31_fu_207_p4 = {{layer6_out_dout[71:48]}};

assign trunc_ln44_32_fu_217_p4 = {{layer6_out_dout[95:72]}};

assign trunc_ln44_33_fu_227_p4 = {{layer6_out_dout[119:96]}};

assign trunc_ln44_34_fu_237_p4 = {{layer6_out_dout[143:120]}};

assign trunc_ln44_35_fu_247_p4 = {{layer6_out_dout[167:144]}};

assign trunc_ln44_36_fu_257_p4 = {{layer6_out_dout[191:168]}};

assign trunc_ln44_37_fu_267_p4 = {{layer6_out_dout[215:192]}};

assign trunc_ln44_38_fu_277_p4 = {{layer6_out_dout[239:216]}};

assign trunc_ln44_39_fu_287_p4 = {{layer6_out_dout[263:240]}};

assign trunc_ln44_40_fu_297_p4 = {{layer6_out_dout[287:264]}};

assign trunc_ln44_41_fu_307_p4 = {{layer6_out_dout[311:288]}};

assign trunc_ln44_42_fu_317_p4 = {{layer6_out_dout[335:312]}};

assign trunc_ln44_43_fu_327_p4 = {{layer6_out_dout[359:336]}};

assign trunc_ln44_44_fu_337_p4 = {{layer6_out_dout[383:360]}};

assign trunc_ln44_fu_193_p1 = layer6_out_dout[23:0];

assign trunc_ln44_s_fu_197_p4 = {{layer6_out_dout[47:24]}};

assign trunc_ln52_31_fu_401_p4 = {{layer6_out_dout[60:53]}};

assign trunc_ln52_32_fu_425_p4 = {{layer6_out_dout[84:77]}};

assign trunc_ln52_33_fu_449_p4 = {{layer6_out_dout[108:101]}};

assign trunc_ln52_34_fu_473_p4 = {{layer6_out_dout[132:125]}};

assign trunc_ln52_35_fu_497_p4 = {{layer6_out_dout[156:149]}};

assign trunc_ln52_36_fu_521_p4 = {{layer6_out_dout[180:173]}};

assign trunc_ln52_37_fu_545_p4 = {{layer6_out_dout[204:197]}};

assign trunc_ln52_38_fu_569_p4 = {{layer6_out_dout[228:221]}};

assign trunc_ln52_39_fu_593_p4 = {{layer6_out_dout[252:245]}};

assign trunc_ln52_40_fu_617_p4 = {{layer6_out_dout[276:269]}};

assign trunc_ln52_41_fu_641_p4 = {{layer6_out_dout[300:293]}};

assign trunc_ln52_42_fu_665_p4 = {{layer6_out_dout[324:317]}};

assign trunc_ln52_43_fu_689_p4 = {{layer6_out_dout[348:341]}};

assign trunc_ln52_44_fu_713_p4 = {{layer6_out_dout[372:365]}};

assign trunc_ln52_s_fu_377_p4 = {{layer6_out_dout[36:29]}};

endmodule //myproject_relu_array_ap_fixed_16u_array_ap_fixed_8_3_5_3_0_16u_relu_config8_s
