// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_transfer_idx_config15_s (
        ap_clk,
        ap_rst,
        index,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [8:0] index;
output  [8:0] ap_return;
input   ap_ce;

reg[8:0] ap_return;

reg   [8:0] index_read_reg_125;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] index_read_reg_125_pp0_iter1_reg;
reg   [8:0] index_read_reg_125_pp0_iter2_reg;
reg   [8:0] index_read_reg_125_pp0_iter3_reg;
reg   [8:0] index_read_reg_125_pp0_iter4_reg;
reg   [8:0] index_read_reg_125_pp0_iter5_reg;
reg   [8:0] index_read_reg_125_pp0_iter6_reg;
reg   [8:0] index_read_reg_125_pp0_iter7_reg;
reg   [8:0] index_read_reg_125_pp0_iter8_reg;
reg   [8:0] index_read_reg_125_pp0_iter9_reg;
reg   [8:0] index_read_reg_125_pp0_iter10_reg;
reg   [8:0] index_read_reg_125_pp0_iter11_reg;
wire   [4:0] grp_fu_40_p1;
wire    ap_block_pp0_stage0;
wire   [8:0] mul_ln23_fu_49_p0;
wire   [10:0] mul_ln23_fu_49_p1;
wire   [18:0] mul_ln23_fu_49_p2;
wire   [22:0] zext_ln18_fu_55_p1;
wire   [0:0] tmp_1_fu_59_p3;
wire   [3:0] grp_fu_40_p2;
wire   [3:0] trunc_ln22_fu_85_p1;
wire   [7:0] shl_ln_fu_89_p3;
wire   [8:0] select_ln22_fu_77_p3;
wire   [8:0] zext_ln22_fu_97_p1;
wire   [8:0] add_ln22_fu_101_p2;
wire   [4:0] tmp_fu_107_p4;
wire   [3:0] trunc_ln18_1_fu_67_p4;
reg    grp_fu_40_ce;
wire   [8:0] idx_fu_117_p3;
reg    ap_ce_reg;
reg   [8:0] index_int_reg;
reg   [8:0] ap_return_int_reg;
wire   [18:0] mul_ln23_fu_49_p00;

myproject_urem_9ns_5ns_4_13_0 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_9ns_5ns_4_13_0_U2078(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(index_int_reg),
    .din1(grp_fu_40_p1),
    .ce(grp_fu_40_ce),
    .dout(grp_fu_40_p2)
);

myproject_mul_9ns_11ns_19_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
mul_9ns_11ns_19_1_0_U2079(
    .din0(mul_ln23_fu_49_p0),
    .din1(mul_ln23_fu_49_p1),
    .dout(mul_ln23_fu_49_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= idx_fu_117_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        index_int_reg <= index;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        index_read_reg_125 <= index_int_reg;
        index_read_reg_125_pp0_iter10_reg <= index_read_reg_125_pp0_iter9_reg;
        index_read_reg_125_pp0_iter11_reg <= index_read_reg_125_pp0_iter10_reg;
        index_read_reg_125_pp0_iter1_reg <= index_read_reg_125;
        index_read_reg_125_pp0_iter2_reg <= index_read_reg_125_pp0_iter1_reg;
        index_read_reg_125_pp0_iter3_reg <= index_read_reg_125_pp0_iter2_reg;
        index_read_reg_125_pp0_iter4_reg <= index_read_reg_125_pp0_iter3_reg;
        index_read_reg_125_pp0_iter5_reg <= index_read_reg_125_pp0_iter4_reg;
        index_read_reg_125_pp0_iter6_reg <= index_read_reg_125_pp0_iter5_reg;
        index_read_reg_125_pp0_iter7_reg <= index_read_reg_125_pp0_iter6_reg;
        index_read_reg_125_pp0_iter8_reg <= index_read_reg_125_pp0_iter7_reg;
        index_read_reg_125_pp0_iter9_reg <= index_read_reg_125_pp0_iter8_reg;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = idx_fu_117_p3;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_40_ce = 1'b1;
    end else begin
        grp_fu_40_ce = 1'b0;
    end
end

assign add_ln22_fu_101_p2 = (select_ln22_fu_77_p3 + zext_ln22_fu_97_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign grp_fu_40_p1 = 9'd15;

assign idx_fu_117_p3 = {{tmp_fu_107_p4}, {trunc_ln18_1_fu_67_p4}};

assign mul_ln23_fu_49_p0 = mul_ln23_fu_49_p00;

assign mul_ln23_fu_49_p00 = index_read_reg_125_pp0_iter11_reg;

assign mul_ln23_fu_49_p1 = 19'd547;

assign select_ln22_fu_77_p3 = ((tmp_1_fu_59_p3[0:0] == 1'b1) ? 9'd240 : 9'd0);

assign shl_ln_fu_89_p3 = {{trunc_ln22_fu_85_p1}, {4'd0}};

assign tmp_1_fu_59_p3 = zext_ln18_fu_55_p1[32'd13];

assign tmp_fu_107_p4 = {{add_ln22_fu_101_p2[8:4]}};

assign trunc_ln18_1_fu_67_p4 = {{mul_ln23_fu_49_p2[17:14]}};

assign trunc_ln22_fu_85_p1 = grp_fu_40_p2[3:0];

assign zext_ln18_fu_55_p1 = mul_ln23_fu_49_p2;

assign zext_ln22_fu_97_p1 = shl_ln_fu_89_p3;

endmodule //myproject_transfer_idx_config15_s
