// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_compute_output_buffer_2d_array_array_ap_fixed_21_11_5_3_0_8u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        in_elem_0_0_0_0_0_val,
        layer2_out_din,
        layer2_out_full_n,
        layer2_out_write,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer2_out_blk_n
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [7:0] in_elem_0_0_0_0_0_val;
output  [167:0] layer2_out_din;
input   layer2_out_full_n;
output   layer2_out_write;
input  [10:0] layer2_out_num_data_valid;
input  [10:0] layer2_out_fifo_cap;
output   layer2_out_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer2_out_write;
reg layer2_out_blk_n;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;
reg   [31:0] sX_3;
reg   [31:0] sY_3;
reg   [31:0] pY_3;
reg   [31:0] pX_3;
wire    ap_block_pp0_stage0_grp1;
reg   [0:0] icmp_ln284_reg_358;
reg   [0:0] and_ln284_2_reg_368;
wire   [0:0] icmp_ln284_fu_146_p2;
reg    ap_predicate_op58_write_state5;
reg    ap_block_state5_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [31:0] sY_3_load_reg_362;
wire   [0:0] and_ln284_2_fu_208_p2;
wire   [0:0] icmp_ln303_fu_220_p2;
reg   [0:0] icmp_ln303_reg_372;
wire   [0:0] icmp_ln307_fu_270_p2;
reg   [0:0] icmp_ln307_reg_376;
reg   [20:0] res_out_reg_380;
wire    ap_block_pp0_stage3_11001;
reg   [20:0] res_out_1_reg_385;
reg   [20:0] res_out_2_reg_390;
reg   [20:0] res_out_3_reg_395;
reg   [20:0] res_out_4_reg_400;
reg   [20:0] res_out_5_reg_405;
reg   [20:0] res_out_6_reg_410;
reg   [20:0] res_out_7_reg_415;
reg    ap_block_pp0_stage0_subdone;
reg    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_start;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_done;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_idle;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_ready;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld;
reg    call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_ce;
reg    ap_block_state5_pp0_stage0_iter1_ignore_call2_grp1;
reg    ap_block_pp0_stage0_11001_ignoreCallOp8;
wire    ap_block_pp0_stage0_11001_ignoreCallOp8_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg_iter0;
reg    ap_block_pp0_stage0_subdone_grp0;
wire    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_start;
wire    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_done;
wire    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_idle;
wire    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_ready;
wire   [20:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_0;
wire   [20:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_1;
wire   [20:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_2;
wire   [20:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_3;
wire   [20:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_4;
wire   [20:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_5;
wire   [20:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_6;
wire   [20:0] grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_7;
reg    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_ce;
reg    ap_predicate_op40_call_state2;
wire    ap_block_pp0_stage1_11001_ignoreCallOp40;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage2_11001_ignoreCallOp47;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage3_11001_ignoreCallOp48;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_85_p4;
wire   [31:0] select_ln313_fu_298_p3;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage0_grp0;
wire    ap_block_pp0_stage0_ignoreCallOp8_grp0;
reg    grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_start_reg;
reg    ap_block_pp0_stage0_11001;
reg    ap_predicate_op40_call_state2_state1;
wire    ap_block_pp0_stage1_ignoreCallOp40;
wire   [31:0] select_ln318_fu_238_p3;
wire   [31:0] add_ln307_fu_264_p2;
wire   [31:0] add_ln303_fu_214_p2;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [30:0] tmp_979_fu_170_p4;
wire   [30:0] tmp_980_fu_186_p4;
wire   [0:0] icmp_ln284_5_fu_180_p2;
wire   [0:0] icmp_ln284_6_fu_196_p2;
wire   [0:0] and_ln284_fu_202_p2;
wire   [0:0] icmp_ln284_4_fu_164_p2;
wire   [31:0] add_ln318_fu_232_p2;
wire    ap_block_pp0_stage1;
wire   [0:0] icmp_ln313_fu_288_p2;
wire   [31:0] add_ln313_fu_293_p2;
wire    ap_block_pp0_stage3;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_init_pp0;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
reg    ap_condition_255;
reg    ap_condition_310;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10 = 8'd0;
#0 sX_3 = 32'd0;
#0 sY_3 = 32'd0;
#0 pY_3 = 32'd0;
#0 pX_3 = 32'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 = 1'b0;
#0 grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_start_reg = 1'b0;
end

myproject_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_start),
    .ap_done(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_done),
    .ap_idle(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_idle),
    .ap_ready(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_ready),
    .in_elem_0_0_0_0_0_val(in_elem_0_0_0_0_0_val),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld),
    .ap_ce(call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_ce)
);

myproject_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_start),
    .ap_done(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_done),
    .ap_idle(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_idle),
    .ap_ready(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_ready),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10),
    .ap_return_0(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_7),
    .ap_ce(grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op40_call_state2_state1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_ready == 1'b1)) begin
            grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_255)) begin
        if ((icmp_ln303_fu_220_p2 == 1'd1)) begin
            pX_3 <= 32'd0;
        end else if ((icmp_ln303_fu_220_p2 == 1'd0)) begin
            pX_3 <= add_ln303_fu_214_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_310)) begin
        if ((icmp_ln307_fu_270_p2 == 1'd1)) begin
            pY_3 <= 32'd0;
        end else if ((icmp_ln307_fu_270_p2 == 1'd0)) begin
            pY_3 <= add_ln307_fu_264_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_255)) begin
        if ((icmp_ln303_fu_220_p2 == 1'd1)) begin
            sX_3 <= 32'd0;
        end else if ((icmp_ln303_fu_220_p2 == 1'd0)) begin
            sX_3 <= select_ln318_fu_238_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln284_2_reg_368 <= and_ln284_2_fu_208_p2;
        icmp_ln284_reg_358 <= icmp_ln284_fu_146_p2;
        icmp_ln303_reg_372 <= icmp_ln303_fu_220_p2;
        icmp_ln307_reg_376 <= icmp_ln307_fu_270_p2;
        sY_3_load_reg_362 <= sY_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        res_out_1_reg_385 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_1;
        res_out_2_reg_390 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_2;
        res_out_3_reg_395 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_3;
        res_out_4_reg_400 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_4;
        res_out_5_reg_405 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_5;
        res_out_6_reg_410 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_6;
        res_out_7_reg_415 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_7;
        res_out_reg_380 <= grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln303_reg_372 == 1'd1))) begin
        sY_3 <= ap_phi_mux_storemerge_phi_fu_85_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10 <= call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11 <= call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12 <= call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13 <= call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14 <= call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15 <= call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16 <= call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17 <= call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 <= call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln307_reg_376 == 1'd0) & (icmp_ln303_reg_372 == 1'd1))) begin
        ap_phi_mux_storemerge_phi_fu_85_p4 = select_ln313_fu_298_p3;
    end else begin
        ap_phi_mux_storemerge_phi_fu_85_p4 = 32'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_idle_pp0_0to0 == 1'b1)) begin
        ap_reset_init_pp0 = 1'b1;
    end else begin
        ap_reset_init_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp8_grp0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_ce = 1'b1;
    end else begin
        call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_start = 1'b1;
    end else begin
        call_ln281_shift_line_buffer_array_ap_fixed_8_3_5_3_0_1u_config2_s_fu_92_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp48) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp47) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp40) & (1'b1 == ap_CS_fsm_pp0_stage1))))) begin
        grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln284_2_reg_368) & (icmp_ln284_reg_358 == 1'd1) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_out_blk_n = layer2_out_full_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op58_write_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_out_write = 1'b1;
    end else begin
        layer2_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_reset_init_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_reset_init_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln303_fu_214_p2 = (pX_3 + 32'd1);

assign add_ln307_fu_264_p2 = (pY_3 + 32'd1);

assign add_ln313_fu_293_p2 = (sY_3_load_reg_362 + 32'd1);

assign add_ln318_fu_232_p2 = (sX_3 + 32'd1);

assign and_ln284_2_fu_208_p2 = (icmp_ln284_4_fu_164_p2 & and_ln284_fu_202_p2);

assign and_ln284_fu_202_p2 = (icmp_ln284_6_fu_196_p2 & icmp_ln284_5_fu_180_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1_ignore_call2_grp1));
end

assign ap_block_pp0_stage0_11001_ignoreCallOp8_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp8_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp0 = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp40 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_ignoreCallOp40 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2_11001_ignoreCallOp47 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp48 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (1'b0 == ap_ce);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1_grp1 = ((ap_predicate_op58_write_state5 == 1'b1) & (layer2_out_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1_ignore_call2_grp1 = ((ap_predicate_op58_write_state5 == 1'b1) & (layer2_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_255 = ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_310 = ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln303_fu_220_p2 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op40_call_state2 = ((1'd1 == and_ln284_2_reg_368) & (icmp_ln284_reg_358 == 1'd1));
end

always @ (*) begin
    ap_predicate_op40_call_state2_state1 = ((icmp_ln284_fu_146_p2 == 1'd1) & (1'd1 == and_ln284_2_fu_208_p2));
end

always @ (*) begin
    ap_predicate_op58_write_state5 = ((1'd1 == and_ln284_2_reg_368) & (icmp_ln284_reg_358 == 1'd1));
end

assign grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_start = grp_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_21_11_5_3_0_config2_mult_s_fu_120_ap_start_reg;

assign icmp_ln284_4_fu_164_p2 = ((sY_3 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln284_5_fu_180_p2 = (($signed(tmp_979_fu_170_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_6_fu_196_p2 = (($signed(tmp_980_fu_186_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_fu_146_p2 = ((sX_3 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln303_fu_220_p2 = ((add_ln303_fu_214_p2 == 32'd63) ? 1'b1 : 1'b0);

assign icmp_ln307_fu_270_p2 = ((add_ln307_fu_264_p2 == 32'd13) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_288_p2 = ((sY_3_load_reg_362 == 32'd2) ? 1'b1 : 1'b0);

assign layer2_out_din = {{{{{{{{res_out_7_reg_415}, {res_out_6_reg_410}}, {res_out_5_reg_405}}, {res_out_4_reg_400}}, {res_out_3_reg_395}}, {res_out_2_reg_390}}, {res_out_1_reg_385}}, {res_out_reg_380}};

assign select_ln313_fu_298_p3 = ((icmp_ln313_fu_288_p2[0:0] == 1'b1) ? 32'd2 : add_ln313_fu_293_p2);

assign select_ln318_fu_238_p3 = ((icmp_ln284_fu_146_p2[0:0] == 1'b1) ? 32'd2 : add_ln318_fu_232_p2);

assign tmp_979_fu_170_p4 = {{pY_3[31:1]}};

assign tmp_980_fu_186_p4 = {{pX_3[31:1]}};

endmodule //myproject_compute_output_buffer_2d_array_array_ap_fixed_21_11_5_3_0_8u_config2_s
